.circleci/config.yml
This should not be necessary anymore.
=> Don't do a shallow clone on CircleCI

.jenkins/cscs/batch.sh, cmake/pika_add_module.cmake
=> Remove debug output

tools/perftests_ci/perftest/plot.py
I'm not quite sure how this happened...
=> Fix garbled symbols in performance CI output

README.rst
Fixes #46. I hope it doesn't need a more elaborate explanation?
=> Add short section about the name to the README

examples/jacobi_smp/jacobi_nonuniform.cpp, examples/quickstart/fibonacci_await.cpp, examples/quickstart/fibonacci_dataflow.cpp, examples/quickstart/fibonacci_futures.cpp, libs/pika/algorithms/tests/performance/foreach_report.cpp, libs/pika/algorithms/tests/performance/foreach_scaling.cpp, libs/pika/init_runtime/CMakeLists.txt, libs/pika/init_runtime/include/pika/init_runtime/scoped_finalize.hpp, libs/pika/init_runtime/src/scoped_finalize.cpp, libs/pika/init_runtime/tests/unit/CMakeLists.txt, libs/pika/init_runtime/tests/unit/scoped_finalize.cpp
Fixes #94.
Somewhat quickly put together RAII helper. I don't think there's so much more to it though...
=> Add `scoped_finalize` helper struct for calling `pika::finalize`

libs/pika/execution/include/pika/execution/algorithms/make_future.hpp
=> Release operation state after `set_*` is called in `make_future_receiver`

libs/pika/datastructures/include/pika/datastructures/detail/small_vector.hpp
This cherry-picks the fix from https://github.com/STEllAR-GROUP/hpx/pull/5769. The performance in DLA-Future is almost restored, but not 100% so I'm still keeping pika's own `small_vector` disabled. Related to #78.
=> Fix memory allocation in `small_vector`

libs/pika/async_combinators/include/pika/async_combinators/future_wait.hpp, libs/pika/async_combinators/include/pika/async_combinators/split_future.hpp, libs/pika/async_combinators/include/pika/async_combinators/wait_each.hpp, libs/pika/async_combinators/include/pika/async_combinators/wait_some.hpp, libs/pika/async_combinators/include/pika/async_combinators/when_all.hpp, libs/pika/async_combinators/include/pika/async_combinators/when_any.hpp, libs/pika/async_combinators/include/pika/async_combinators/when_each.hpp, libs/pika/async_combinators/include/pika/async_combinators/when_some.hpp
=> Clean up `async_combinators` module

tools/inspect/inspect.cpp
As a flyby gets rid of the occasional warnings about the spelling of `referrer` in the commented out url.
=> Remove commented-out code in `inspect.cpp`

cmake/pika_setup_cuda.cmake, libs/pika/async_cuda/include/pika/async_cuda/cuda_pool.hpp, libs/pika/async_cuda/include/pika/async_cuda/cuda_scheduler_bulk.hpp, libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp, libs/pika/concurrency/include/pika/concurrency/concurrentqueue.hpp, libs/pika/config/include/pika/config/compiler_specific.hpp, libs/pika/coroutines/include/pika/coroutines/thread_id_type.hpp, libs/pika/errors/include/pika/errors/exception_fwd.hpp, libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp, libs/pika/functional/include/pika/functional/bind.hpp, libs/pika/functional/include/pika/functional/bind_back.hpp, libs/pika/functional/include/pika/functional/bind_front.hpp, libs/pika/functional/include/pika/functional/deferred_call.hpp, libs/pika/futures/include/pika/futures/future.hpp, libs/pika/iterator_support/include/pika/iterator_support/counting_shape.hpp, libs/pika/iterator_support/include/pika/iterator_support/iterator_facade.hpp, libs/pika/tag_invoke/include/pika/functional/detail/tag_fallback_invoke.hpp, libs/pika/tag_invoke/include/pika/functional/detail/tag_priority_invoke.hpp, libs/pika/tag_invoke/include/pika/functional/tag_invoke.hpp
(Eventually) fixes #161. Not tested, will run CI to see what this does initially.
=> Remove `-w` flag to disable all warnings with CUDA

CHANGELOG.md
@aurianer could you please have a look to see if I've missed something? Still open PRs are not listed, but will likely be added.
=> Release notes for 0.3.0

.circleci/config.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_hip.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_sanitizers.yml, tools/docker/Dockerfile
=> Replace with slimmer docker image

.circleci/config.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_hip.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_sanitizers.yml, tools/docker/Dockerfile
Just realized #193 is using the version 1 recently updated to the version 2 (technically the same images but still)
=> Update to the version 2

libs/pika/async_base/include/pika/async_base/scheduling_properties.hpp, libs/pika/async_base/tests/regressions/CMakeLists.txt, libs/pika/async_base/tests/regressions/prefer_scheduling_properties.cpp
=> Allow using `prefer` on scheduling properties

.circleci/config.yml
=> Enable MPI on CircleCI

CHANGELOG.md
The release date is still tentative as it might be a little tight to get this out by tomorrow. ~#243 is still unmerged and can be left out if it doesn't work correctly yet, though it should be quite straightforward.~
=> Add release notes for 0.5.0

libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
#243 also removed the SFINAE prematurely from `then_with_cuda_stream_sender`. It will be possible to remove it once https://github.com/eth-cscs/DLA-Future/pull/459 is in, but before that the SFINAE is still required.
=> Add back SFINAE to `then_with_cuda_stream_sender` for DLA-Future

.github/bors.toml, .jenkins/cscs/Jenkinsfile, .jenkins/cscs/env-gcc-12.sh, .jenkins/cscs/slurm-constraint-gcc-12.sh, CMakeLists.txt, libs/pika/debugging/src/print.cpp, libs/pika/futures/include/pika/futures/future.hpp
Fixes #229.
This uses C++20 and enables `PIKA_WITH_P2300_REFERENCE_IMPLEMENTATION`.
=> Add GCC 12 to Jenkins

README.rst
=> Add Codacy badge to README.rst

libs/pika/execution/CMakeLists.txt
Removes some parts that were not removed in #223.
=> Remove leftover parts of Vc

libs/pika/algorithms/include/pika/parallel/algorithms/detail/adjacent_difference.hpp, libs/pika/algorithms/include/pika/parallel/algorithms/detail/find.hpp, libs/pika/algorithms/include/pika/parallel/datapar/adjacent_difference.hpp, libs/pika/coroutines/include/pika/coroutines/thread_enums.hpp, libs/pika/ini/include/pika/ini/ini.hpp, libs/pika/logging/include/pika/logging/format/destinations.hpp, libs/pika/version/include/pika/version.hpp
=> Remove some unnecessary iostream includes

libs/pika/async_cuda/include/pika/async_cuda/cuda_pool.hpp, libs/pika/async_cuda/include/pika/async_cuda/cuda_stream.hpp, libs/pika/async_cuda/include/pika/async_cuda/custom_gpu_api.hpp, libs/pika/async_cuda/src/cuda_pool.cpp, libs/pika/async_cuda/src/cuda_stream.cpp, libs/pika/async_cuda/tests/unit/cuda_pool.cu, libs/pika/async_cuda/tests/unit/cuda_stream.cu
=> Allow setting flags on `cuda_stream` and streams in `cuda_pool`

CHANGELOG.md
@aurianer anything missing? Anything you'd like to see changed?
=> Add release notes for 0.6.0

libs/pika/config/include/pika/config/compiler_specific.hpp, libs/pika/init_runtime/src/init_runtime.cpp, libs/pika/schedulers/include/pika/schedulers/local_queue_scheduler.hpp, libs/pika/topology/include/pika/topology/topology.hpp
=> Remove KNL-specific `ifdef`s

cmake/pika_setup_p2300.cmake
It seems like no changes are required in pika. I'm bumping it just to try to keep up with the changes that are made upstream.
=> Update P2300 reference implementation commit

.circleci/config.yml, .github/workflows/linux_coverage.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_sanitizers.yml, .github/workflows/linux_tracy.yml, README.rst
Part of #4. Not fully tested, but I got some reporting already to Codacy so there is hope that this works...
To do:
=> Add Codacy coverage report

.jenkins/cscs-perftests/ctest.cmake, .jenkins/cscs-perftests/entry.sh, .jenkins/cscs/ctest.cmake, .jenkins/cscs/entry.sh
Fixes #311.
In progress, testing changes.
=> Add PR numbers to CDash build names for `staging` and `trying` branches

libs/pika/algorithms/include/pika/algorithms/traits/projected_range.hpp, libs/pika/datastructures/include/pika/datastructures/detail/variant.hpp, libs/pika/debugging/include/pika/debugging/demangle_helper.hpp, libs/pika/debugging/include/pika/debugging/print.hpp, libs/pika/execution/include/pika/execution/algorithms/detail/is_negative.hpp, libs/pika/format/include/pika/util/from_string.hpp, libs/pika/iterator_support/include/pika/iterator_support/counting_iterator.hpp, libs/pika/iterator_support/include/pika/iterator_support/traits/is_iterator.hpp, libs/pika/iterator_support/tests/unit/iterator_adaptor.cpp, libs/pika/iterator_support/tests/unit/iterator_facade.cpp, libs/pika/pack_traversal/include/pika/pack_traversal/detail/pack_traversal_impl.hpp, libs/pika/pack_traversal/tests/unit/pack_traversal.cpp, libs/pika/thread_support/include/pika/thread_support/assert_owns_lock.hpp
I could only get the ones that were on  one line, I haven't yet figure out how to include several lines.
=> Replace some std::enable_if<>::type by std::enable_if_t

libs/pika/debugging/src/print.cpp
=> Fix `print_dec` template instantiation on macOS

libs/pika/executors/tests/unit/limiting_executor.cpp
Description about the problem added to the test itself.
Note: the problem can easily be reproduced by adding a `std::chrono::sleep_for` after this line: https://github.com/pika-org/pika/blob/72834132ec83a3d09db8808b53233fc27b9e149d/libs/pika/executors/include/pika/executors/limiting_executor.hpp#L58.
=> Reduce chance of false positives in `limiting_executor` test

libs/pika/algorithms/include/pika/parallel/algorithms/nth_element.hpp, libs/pika/algorithms/tests/unit/algorithms/nth_element.cpp, libs/pika/algorithms/tests/unit/container_algorithms/nth_element_range.cpp
The follow-up to #412 for the non-ranges version.
=> Update the `nth_element` test to check for corner cases

libs/pika/synchronization/tests/unit/shared_mutex/shared_mutex2.cpp
The failure can be reproduced (before these changes) by adding `std::this_thread::sleep_for` here: https://github.com/pika-org/pika/blob/887eb9c56097bccdde92a90ca56c73a8e1334104/libs/pika/synchronization/tests/unit/shared_mutex/shared_mutex_locking_thread.hpp#L52. The test previously only did `pika::this_thread::yield()` to wait for the spawned threads to start running but this is not always sufficient. This adds synchronization using the already available condition variable, and adds additional sleeping to allow the other thread to run (though it shouldn't run if things are working correctly).
=> Fix `shared_mutex2` test

.jenkins/cscs-ault/env-common.sh, .jenkins/cscs/env-common.sh
Makes it easier to `source env-common.sh` for testing CI
=> Set spack user config and cache path only if not set

README.rst
=> Update minimum CMake version requirement in readme

cmake/pika_setup_hip.cmake, libs/pika/async_cuda/CMakeLists.txt, libs/pika/async_cuda/include/pika/async_cuda/custom_blas_api.hpp, libs/pika/async_cuda/src/cublas_exception.cpp, libs/pika/async_cuda/tests/performance/cuda_scheduler_throughput.cpp, libs/pika/async_cuda/tests/unit/cublas_handle.cu, libs/pika/async_cuda/tests/unit/cublas_matmul.cpp, libs/pika/async_cuda/tests/unit/then_with_stream.cu
Necessary as first step for https://github.com/eth-cscs/DLA-Future/issues/577 to avoid redefinition of the macros.
Will wait for #67 to be merged.
=> Replace hipblas by rocblas

libs/pika/runtime/include/pika/runtime/runtime.hpp, libs/pika/runtime/include/pika/runtime/runtime_fwd.hpp, libs/pika/runtime/include/pika/runtime/state.hpp, libs/pika/runtime/src/custom_exception_info.cpp, libs/pika/runtime/src/runtime.cpp, libs/pika/runtime/src/state.cpp, libs/pika/thread_manager/include/pika/modules/thread_manager.hpp, libs/pika/thread_manager/src/thread_manager.cpp, libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool.hpp, libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool_impl.hpp, libs/pika/thread_pools/include/pika/thread_pools/scheduling_loop.hpp, libs/pika/threading_base/include/pika/threading_base/scheduler_base.hpp, libs/pika/threading_base/include/pika/threading_base/scheduler_state.hpp, libs/pika/threading_base/include/pika/threading_base/thread_pool_base.hpp, libs/pika/threading_base/src/scheduler_base.cpp, libs/pika/threading_base/src/thread_pool_base.cpp
Based on #445
Fix partially #447
=> Rename `state` to `runtime_state`

.circleci/config.yml, libs/pika/hardware/tests/CMakeLists.txt
Based on top of #393  
Build and run tests on arm64 circleci machine
=> Build and run tests on CircleCI arm64 workflow

libs/pika/thread_pools/include/pika/thread_pools/detail/scoped_background_timer.hpp, libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool_impl.hpp, libs/pika/thread_pools/include/pika/thread_pools/scheduling_loop.hpp
=> Clean up `thread_pools` module

.circleci/config.yml, libs/pika/coroutines/include/pika/coroutines/detail/context_impl.hpp, libs/pika/coroutines/include/pika/coroutines/detail/context_posix.hpp, libs/pika/coroutines/src/detail/context_posix.cpp, libs/pika/coroutines/src/swapcontext.cpp
I have no idea if the posix implementation actually works on arm, but we'll find out... This should probably wait for #430 so that we see if this not just compiles but also runs correctly.
May fix #331.
=> Attempt to use generic posix context switching implementation for arm

.github/bors.toml, .jenkins/cscs/Jenkinsfile, .jenkins/cscs/env-clang-15.sh, .jenkins/cscs/slurm-constraint-clang-15.sh, libs/pika/threading/tests/unit/jthread1.cpp, libs/pika/threading/tests/unit/jthread2.cpp
Fixes #437. The clang 15 configuration also uses Boost 1.80.0. Neither clang 15 nor Boost 1.80.0 seem to cause any problems.
=> Add clang 15 Jenkins CI configuration

.github/bors.toml, .github/workflows/macos_arm64_debug.yml, libs/pika/coroutines/include/pika/coroutines/detail/context_generic_context.hpp, libs/pika/coroutines/include/pika/coroutines/detail/context_impl.hpp
Fixes #459. Some tests seem to be segfaulting and I fear that we'll have to simply ignore those tests in CI.
If someone bumps into this PR at a later point and has an interest in looking into the failures that would be very much appreciated.
=> Add macOS M1 CI workflow

libs/pika/execution/tests/unit/algorithm_start_detached.cpp
=> Add a const reference handling test for `start_detached`

.circleci/config.yml, .github/workflows/linux_coverage.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_sanitizers.yml, .github/workflows/linux_tracy.yml, CMakeLists.txt, cmake/pika_setup_stdexec.cmake, cmake/templates/pika-config.cmake.in, libs/pika/execution/tests/unit/algorithm_ensure_started.cpp, libs/pika/execution/tests/unit/algorithm_split.cpp, libs/pika/execution_base/include/pika/execution_base/p2300_forward.hpp
=> Update `P2300` dependency to `STDEXEC`

CHANGELOG.md
Small release this time, no new features...
@aurianer, @biddisco let me know if you think I've missed something or if you think I should change something.
=> Add release notes for 0.10.0

CMakeLists.txt
Fixes #465.
I quickly checked and it _seems_ like we don't need this. I'm counting on CI telling us otherwise if it is actually needed.
=> Remove python dependency

libs/pika/async_cuda/tests/unit/CMakeLists.txt, libs/pika/async_cuda/tests/unit/cublas_matmul.cpp, libs/pika/async_cuda/tests/unit/cuda_sender.cu
=> Re-enable `cublas_matmul_test` with HIP

.cmake-format.py, cmake/pika_add_module.cmake, libs/create_module_skeleton.py
It's currently unused and can easily be added back if needed again in the future.
=> Remove `COMPAT_HEADERS` `pika_add_module` option

libs/pika/resource_partitioner/tests/unit/shutdown_suspended_pus.cpp, libs/pika/resource_partitioner/tests/unit/suspend_disabled.cpp, libs/pika/resource_partitioner/tests/unit/suspend_pool.cpp, libs/pika/resource_partitioner/tests/unit/suspend_pool_external.cpp, libs/pika/resource_partitioner/tests/unit/suspend_thread.cpp, libs/pika/resource_partitioner/tests/unit/suspend_thread_external.cpp, libs/pika/resource_partitioner/tests/unit/suspend_thread_timed.cpp, libs/pika/thread_pool_util/include/pika/thread_pool_util/thread_pool_suspension_helpers.hpp, libs/pika/thread_pool_util/src/thread_pool_suspension_helpers.cpp
Is there anything more to do here?
=> Clean up `thread_pool_util` module

.github/bors.toml, .github/workflows/macos_arm64_debug.yml
=> Re-enable mac M1 CI workflow

cmake/pika_find_package.cmake
Same reason as https://github.com/pika-org/pika-algorithms/pull/16.
=> Make `pika_find_package` a macro

libs/pika/execution/include/pika/execution/algorithms/when_all.hpp, libs/pika/execution_base/include/pika/execution_base/any_sender.hpp, libs/pika/execution_base/tests/unit/any_sender.cpp
Ports fixes from https://github.com/STEllAR-GROUP/hpx/pull/6124.
=> Fix `when_all` and `any_operation_state` typedefs and forwarding

.jenkins/cscs/env-clang-13.sh, .jenkins/cscs/env-clang-14-cuda.sh
stdexec was not pinned, any update to stdexec@main on ault can break CI
=> Pin stdexec version for CI

libs/pika/concurrency/include/pika/concurrency/deque.hpp
=> Remove volatile in deque

libs/pika/init_runtime/tests/unit/finalize_non_pika_thread.cpp, libs/pika/threading/tests/unit/stop_token_race2.cpp, testing/testing/include/pika/testing.hpp, testing/testing/src/testing.cpp
=> Clean up testing module

libs/pika/concurrency/include/pika/concurrency/concurrentqueue.hpp
This is version bf1fe24c8eb413494884dc151712a3ed526fc5a3 from https://github.com/cameron314/concurrentqueue.git
I replaced std::move and std::forward and replaced `typedefs` with `using` but did not make more changes as you (@msimberg )appear to have done with the last version.
No real reason for upgrading other than to pick up small incremental differences
=> Update `moodycamel::concurrentqueue` to latest version

libs/pika/coroutines/include/pika/coroutines/detail/posix_utility.hpp
As in https://github.com/STEllAR-GROUP/hpx/pull/6147.
=> Make posix coroutine stacks non-executable

libs/pika/concurrency/include/pika/concurrency/spinlock_pool.hpp, libs/pika/hashing/docs/index.rst, libs/pika/hashing/include/pika/hashing/fibhash.hpp, libs/pika/synchronization/include/pika/synchronization/spinlock_pool.hpp
=> Clean up the `hashing` module

examples/quickstart/shared_mutex.cpp, libs/pika/affinity/src/parse_affinity_options.cpp, libs/pika/command_line_handling/src/command_line_handling.cpp, libs/pika/coroutines/include/pika/coroutines/detail/context_posix.hpp, libs/pika/coroutines/include/pika/coroutines/detail/context_windows_fibers.hpp, libs/pika/coroutines/include/pika/coroutines/stackless_coroutine.hpp, libs/pika/execution_base/tests/unit/basic_schedule.cpp, libs/pika/lcos/include/pika/lcos/channel.hpp, libs/pika/pack_traversal/tests/unit/pack_traversal_async.cpp, libs/pika/resource_partitioner/tests/unit/named_pool_executor.cpp, libs/pika/synchronization/include/pika/synchronization/condition_variable.hpp, libs/pika/synchronization/src/detail/condition_variable.cpp, libs/pika/synchronization/src/mutex.cpp, libs/pika/synchronization/tests/regressions/ignore_while_locked_1485.cpp, libs/pika/synchronization/tests/regressions/shared_mutex_1702.cpp, libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool_impl.hpp, libs/pika/thread_support/include/pika/thread_support/assert_owns_lock.hpp, libs/pika/threading/tests/unit/thread.cpp, libs/pika/threading_base/include/pika/threading_base/thread_init_data.hpp, libs/pika/threading_base/src/execution_agent.cpp
I did that with a script so I probably missed some occurrences
=> Replace some `PIKA_UNUSED` with [[maybe_unused]]

libs/pika/schedulers/include/pika/schedulers/queue_helpers.hpp, libs/pika/schedulers/include/pika/schedulers/thread_queue.hpp, libs/pika/schedulers/src/deadlock_detection.cpp
=> Fix `dump_suspended_threads`

libs/pika/synchronization/include/pika/synchronization/async_rw_mutex.hpp
This allows access of `async_rw_mutex` from non-pika threads. This is a requirement to use DLA-Future in CP2K, where the cholesky decomposition and eigensolver are spawned from a non-pika thread (main).
=> Use `pika::spinlock` instead of `pika::mutex` in `async_rw_mutex`

libs/pika/debugging/src/print.cpp, libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp, libs/pika/threading_base/src/print.cpp
Just some flyby cleanups that are separated from other PRs
=> Debug print cleanup

.circleci/config.yml, .github/workflows/linux_coverage.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_hip.yml, .github/workflows/linux_leaksanitizer.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_sanitizers.yml, .github/workflows/linux_tracy.yml, .jenkins/cscs-ault/env-hipcc.sh, .jenkins/cscs/env-clang-13.sh, .jenkins/cscs/env-clang-14-cuda.sh, .jenkins/cscs/env-gcc-13.sh, .jenkins/cscs/env-nvhpc.sh, README.rst
=> Update stdexec commit tested in CI to `48c52df0f81c6151eecf4f39fa5eed2dc0216204`

docs/usage.rst
Part of #49. Adds a section on how to control the number of threads (with `--pika:threads`) and how to work with the process mask (`--pika:process-mask`, `--pika:ignore-process-mask`). Also mentions `--pika:print-bind`.
=> Add documentation about `--pika:threads` and thread bindings

libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
It has seemingly caused issues in DLA-Future. Until we can be sure that it's (more) bug-free I'm disabling it to avoid further headaches. The performance impact seems to be minimal.
=> Disable SBO in `any_sender`, `any_receiver`, `any_operation_state`

docs/index.rst, examples/quickstart/CMakeLists.txt, examples/quickstart/hello_world_documentation.cpp
=> Add simple example to overview page in documentation

.jenkins/cscs/env-clang-16.sh
Fixes #756 once https://github.com/spack/spack/pull/40078 is merged
=> Change one Jenkins CI configuration to use C++23

tools/perftests_ci/requirements.txt
Fixing a critical CVE reported by snyk
=> Fix critical CVE matplotlib

.github/linters/.yamllint.yml, .github/workflows/linter.yml, .gitlab/pipeline.yml
Attempt to give more useful error messages than CSCS-CI when the yml file is not correct. Only lints modified files.
=> Add linter for yaml files

libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
Add `using is_receiver = void` to `any_receiver`.
=> Opt-in `any_receiver` to newer stdexec receiver concept

libs/pika/runtime/src/runtime.cpp
In #774 I noticed the following failure case that is badly reported by the runtime:
- `pika_main` starts some work that depends on later work being scheduled
- `pika_main` throws an exception
- the runtime stores the exception so that it can report it in `pika::init` or `pika::stop`
- `pika_main` never schedules the work that would allow the previously scheduled work to finish
- `pika::init` or `pika::stop` waits for the runtime to be empty
- the runtime hangs waiting for the runtime to be empty _and_ the error is never reported
I'm not attempting to change how we terminate the runtime here, but I'm simply reporting the caught exception as soon as the runtime gets it. I still let the runtime _attempt_ to shut down cleanly, but at least the error message has been printed.
I think this is …
=> Report exceptions caught by `pika_main` immediately

.github/workflows/linux_valgrind.yml, libs/pika/tag_invoke/tests/unit/CMakeLists.txt
=> Enable valgrind testing in `tag_invoke` module

.github/workflows/linux_valgrind.yml, libs/pika/memory/tests/unit/CMakeLists.txt, libs/pika/string_util/tests/unit/CMakeLists.txt
=> Enable valgrind testing for `memory` and `string_util` module

.github/workflows/linux_valgrind.yml, libs/pika/debugging/tests/unit/CMakeLists.txt, libs/pika/properties/tests/unit/CMakeLists.txt
=> Enable valgrind testing for `properties` and `debugging` module

.cmake-format.py, cmake/pika_add_executable.cmake, cmake/pika_add_library.cmake
=> Remove `AUTOGLOB` cmake option

CMakeLists.txt
https://cmake.org/cmake/help/latest/policy/CMP0144.html
=> Set cmake policy CMP0144 to suppress warning

.gitlab/includes/clang14_cuda11_pipeline.yml, .gitlab/pipeline.yml
=> Add Clang 14 CUDA 11 pipeline with CSCS CI

tests/performance/local/task_size.cpp
Only a single number is printed for the timing "series": the task size which results in at least the target efficiency. Since the test is run multiple times with increasing task sizes, this number should be relatively stable (at least if the growth factor of the task size is small).
=> Add command line option to output json for performance CI to `task_size` test

.github/workflows/linux_valgrind.yml, libs/pika/schedulers/tests/unit/CMakeLists.txt
=> Enable valgrind testing in schedulers module

.github/workflows/linux_valgrind.yml, libs/pika/command_line_handling/tests/regressions/CMakeLists.txt, libs/pika/command_line_handling/tests/unit/CMakeLists.txt
=> Enable valgrind testing in `command_line_handling` module

.github/workflows/linux_valgrind.yml, libs/pika/synchronization/tests/performance/CMakeLists.txt, libs/pika/synchronization/tests/regressions/CMakeLists.txt, libs/pika/synchronization/tests/unit/CMakeLists.txt, libs/pika/synchronization/tests/unit/shared_mutex/CMakeLists.txt
=> Enable valgrind testing in synchronization module

.github/workflows/linux_valgrind.yml, libs/pika/runtime/tests/unit/CMakeLists.txt
=> Enable valgrind testing in `runtime` module

.github/workflows/linux_valgrind.yml, libs/pika/program_options/examples/CMakeLists.txt, libs/pika/program_options/tests/regressions/CMakeLists.txt, libs/pika/program_options/tests/unit/CMakeLists.txt, tools/valgrind/memcheck.supp
=> Enable valgrind testing in `program_options` module

.github/workflows/linux_valgrind.yml, examples/1d_stencil/CMakeLists.txt, examples/balancing/CMakeLists.txt, examples/documentation/CMakeLists.txt, examples/future_reduce/CMakeLists.txt, examples/jacobi_smp/CMakeLists.txt, examples/quickstart/CMakeLists.txt, libs/pika/program_options/examples/CMakeLists.txt
=> Enable valgrind testing for all examples

.gitlab/docker/Dockerfile.spack_build, .gitlab/docker/Dockerfile.spack_build_performance, .gitlab/docker/Dockerfile.spack_dependencies, .gitlab/includes/clang11_pipeline.yml, .gitlab/includes/clang12_pipeline.yml, .gitlab/includes/clang13_pipeline.yml, .gitlab/includes/clang14_cuda11_pipeline.yml, .gitlab/includes/clang15_pipeline.yml, .gitlab/includes/clang16_pipeline.yml, .gitlab/includes/gcc10_apex_pipeline.yml, .gitlab/includes/gcc11_pipeline.yml, .gitlab/includes/gcc12_cuda12_pipeline.yml, .gitlab/includes/gcc12_pipeline.yml, .gitlab/includes/gcc13_pipeline.yml, .gitlab/includes/gcc9_cuda11_pipeline.yml, .gitlab/includes/gcc9_pipeline.yml, .gitlab/includes/hip_pipeline.yml
=> Add a spack environment for determinism in CI

libs/pika/schedulers/include/pika/schedulers/local_queue_scheduler.hpp
The masks are written and read potentially concurrently, by the `on_start_thread` and by the work stealing in the scheduling loop. Since the masks are bitmasks, and not simply arrays of independent bools, reading and writing different indices of the masks still may access the same underlying bytes, leading to data races. This commit protects the writes to the masks with a mutex, and synchronizes the exit of `on_start_thread` with a barrier. The latter allows work stealing to read the masks without locks.
=> Protect access to stealing masks in `local_queue_scheduler.hpp`

.gitlab/docker/Dockerfile.spack_build, .gitlab/scripts/collect_file_sizes.sh, .gitlab/scripts/run_performance_benchmarks.sh, .gitlab/scripts/utilities.sh
=> Report library and executable file sizes to elastic from CI

libs/pika/threading/tests/unit/condition_variable2.cpp
The `t1_feedback` variable is read and written without synchronization. Use relaxed atomics for the variable instead.
=> Fix data race in `condition_variable2` test

.github/workflows/linux_valgrind.yml, libs/pika/init_runtime/tests/unit/CMakeLists.txt
=> Enable valgrind testing for `init_runtime` module

.gitlab/docker/Dockerfile.spack_build
=> Install pika in CSCS CI configurations

libs/pika/thread_manager/tests/unit/thread_num.cpp
https://github.com/pika-org/pika/pull/1016#discussion_r1478919473.
=> Fix copyright in `thread_num` test

.gitlab/scripts/run_performance_benchmarks.sh, tests/performance/local/CMakeLists.txt, tests/performance/local/task_latency.cpp
Also add it to performance CI jobs. See commit description for more details about the benchmark.
=> Add task latency benchmark

README.rst
Also removes the no longer used bors badge.
=> Add Zenodo badge to README

.github/workflows/linux_tsan_blacklist.txt, .gitlab/includes/clang11_pipeline.yml, .gitlab/includes/clang12_pipeline.yml, .gitlab/includes/clang13_pipeline.yml, .gitlab/includes/clang15_pipeline.yml, .gitlab/includes/clang16_pipeline.yml, .gitlab/includes/clang17_pipeline.yml, .gitlab/includes/common_pipeline.yml, .gitlab/includes/dockerhub_pipeline.yml, .gitlab/includes/gcc10_apex_pipeline.yml, .gitlab/includes/gcc11_pipeline.yml, .gitlab/includes/gcc12_pipeline.yml, .gitlab/includes/gcc13_pipeline.yml, .gitlab/includes/gcc9_pipeline.yml, .gitlab/includes/performance_gcc13_pipeline.yml, libs/pika/runtime/tests/unit/CMakeLists.txt, tests/regressions/threads/CMakeLists.txt
Part of #926
On eiger jobs are submitted through firecrest. The related tokens are on the setup page and were added by Andreas so that the job is submitted through the jenkssl account.
=> Move mc pipelines to eiger in CSCS CI

libs/pika/async_cuda/src/cuda_pool.cpp
When constructing the pool of CUDA streams and cuBLAS/SOLVER handles, we previously pass a stream/handle to a vector constructor, which is then copied to construct each element in the vector. The stream/handle that is passed to the `vector` constructor is otherwise unused and released after the vector has been constructed. This is not a performance issue, but the creation is unnecessary and can be surprising when looking e.g. at profiles. This PR moves the filling of the vectors to a `reserve` + for-loop + `emplace_back` in the body of the pool constructor to avoid the extra stream/handle.
=> Avoid unnecessary copies of CUDA streams and handles

CMakeLists.txt, cmake/templates/pika-config.cmake.in
=> Clean up CMake policies

libs/pika/debugging/include/pika/debugging/demangle_helper.hpp
=> Fix reserved syntax violation

libs/pika/type_support/include/pika/type_support/pack.hpp
Credits to @isidorostsa for spotting this in https://github.com/STEllAR-GROUP/hpx/commit/e253726214f38b3097024e593128dced38c54a7e.
=> Fix type pack `append_t` definition to append instead of prepend

libs/pika/coroutines/include/pika/coroutines/thread_enums.hpp, libs/pika/coroutines/src/thread_enums.cpp, libs/pika/schedulers/include/pika/schedulers/queue_holder_thread.hpp, libs/pika/schedulers/include/pika/schedulers/thread_queue.hpp, libs/pika/thread_manager/include/pika/modules/thread_manager.hpp, libs/pika/thread_manager/include/pika/thread_manager/thread_manager_fwd.hpp, libs/pika/thread_pools/include/pika/thread_pools/scheduling_loop.hpp
=> Remove depleted thread state

.gitlab/scripts/run_performance_benchmarks.sh, tests/performance/local/CMakeLists.txt, tests/performance/local/condition_variable_overhead.cpp
Test makes pairs of tasks wait and signal each other in a loop and times many iterations of it
```
bin/condition_variable_overhead_test --loops=100000 --repetitions=10 --pika:threads=9
```
```
bin/condition_variable_overhead_test --loops=1 --repetitions=500 --pika:threads=3 --pika:queuing=shared
bin/condition_variable_overhead_test --loops=1 --repetitions=500 --pika:threads=3 --pika:queuing=local-priority
```
=> Adding a performance test for condition variable

tests/performance/local/task_size.cpp
This doesn't change the timing used for the performance tests in CI.
=> Add task spawn time to `task_size` benchmark output

.gitlab/includes/gcc14_pipeline.yml, .gitlab/pipelines_on_merge.yml, .gitlab/pipelines_on_push.yml
=> Add gcc14 configuration in CI

.gitlab/scripts/run_performance_benchmarks.sh
I'm hoping this makes it a bit easier to see if one of the performance tests fails.
=> Print performance test output and print error codes if non-zero in CI

.gitlab/scripts/run_performance_benchmarks.sh
Fixes #1256 by doing a simple filtering of the test output before passing it to `jq`. In this case we don't try to detect the json output specifically, but simply assume that non-json output comes first and does not contain a single `{` on any line. Anything from (and including) a `{` is considered to be the json output we care about, and we keep everything after that line.
=> Filter out APEX output in performance tests before parsing json

.github/workflows/macos_debug.yml
`macos-12` will be removed in December 2024.
=> Update macOS CI workflow to use macos-15

.gitlab/scripts/run_performance_benchmarks.sh
Currently, if a performance test fails (exits with non-zero exit code) we still attempt to submit the json output from the test. Usually the json output will be incomplete and the submission will fail. This PR makes sure we only submit performance results when the test succeeds (which anyway is the only thing that makes sense). Failures are still tracked and if at least one performance test fails, the job still fails.
=> Don't attempt to submit performance test results to elastic on failure

docs/api.rst, examples/documentation/CMakeLists.txt, examples/documentation/drop_operation_state_documentation.cpp, libs/pika/execution/include/pika/execution/algorithms/drop_operation_state.hpp
=> Add documentation for `drop_operation_state`

.circleci/config.yml, .devcontainer/devcontainer.json, .github/workflows/linux_asan_ubsan_lsan.yml, .github/workflows/linux_coverage.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_tracy.yml, .github/workflows/linux_tsan.yml, .github/workflows/linux_valgrind.yml, .gitlab/includes/clang13_pipeline.yml, .gitlab/includes/dockerhub_pipeline.yml, .gitlab/includes/gcc12_hip5_pipeline.yml, .gitlab/includes/gcc12_hip6_pipeline.yml, .gitlab/includes/gcc13_pipeline.yml, .gitlab/includes/gcc13_santis_pipeline.yml, .gitlab/includes/gcc14_pipeline.yml, .gitlab/includes/nvhpc24_7_pipeline.yml, docs/usage.rst, tools/pre-commit
=> Update CI configurations to use stdexec with tag nvhpc-24.09

libs/pika/execution/include/pika/execution/algorithms/let_error.hpp, libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
Minimizes the size of the receivers to be just pointers/references to the operation state, and makes them cheaper to copy around.
This is based on #1337 and has to wait for that to be merged first.
=> Move callable and receiver to operation state in `let_value`/`let_error`

.github/workflows/linux_hip.yml
=> Restore GitHub actions HIP workflow

libs/pika/runtime/tests/unit/CMakeLists.txt
=> Relax expected process masks on configuration precedence test for Grace CPU

.gitlab/includes/common_spack_pipeline.yml
Separating the commit update from #1363.
=> Update spack commit used in CI

docs/usage.rst
Based on #1411.
Naming of options to do based on what will be implemented in #1411.
=> Add basic documentation on debugging with pika

.circleci/config.yml, .gitlab/includes/gcc11_pipeline.yml, cmake/pika_check_cxx_standard.cmake, cmake/pika_setup_boost.cmake, docs/usage.rst, libs/pika/config/include/pika/config.hpp
=> Require C++20
