- .github/bors.toml
The catchall `%` means that when _any_ (one) matching build has succeeded bors will decide to merge. What we're looking for is all matching builds to succeed. This changes the list to an explicit list of the required builds.
> Fix specification of bors checks

- .github/bors.toml
It's a guideline and can be broken in certain cases (and it sometimes reports false positives). This removes it as a requirement when bors merging.
> Remove spellcheck from required bors checks

- .circleci/config.yml
Should be against `main`, not `master`.
> Fix spellcheck branch comparison

- libs/pika/async_mpi/CMakeLists.txt
- libs/pika/async_mpi/include/pika/async_mpi/mpi_exception.hpp
- libs/pika/async_mpi/src/mpi_exception.cpp
An inline keyword would fix it as well, but this moves the function into a
source file and `PIKA_EXPORT`s the function instead. I've also moved the other functions in `mpi_exception` to the source file.
> Fix missing inline for `pika::mpi::experimental::detail::error_message`

- CMakeLists.txt
- cmake/pika_setup_mpi.cmake
- libs/pika/async_mpi/CMakeLists.txt
- libs/pika/mpi_base/CMakeLists.txt
- libs/pika/mpi_base/src/mpi_environment.cpp
- libs/pika/version/CMakeLists.txt
Fixes #5.
Renames `PIKA_WITH_ASYNC_MPI` to `PIKA_WITH_MPI`, `PIKA_WITH_PARCELPORT_MPI_X` to `PIKA_WITH_MPI_X` and removes a few unnecessary config options. I'm keeping the setting of the other MPI-related config options (e.g. `pika.parcel.mpi.multithreaded`) for now as they may be useful at some point. They should probably be renamed eventually though.
> Rename `PIKA_WITH_ASYNC_MPI` to `PIKA_WITH_MPI`

- libs/pika/synchronization/tests/unit/shared_mutex/shared_mutex1.cpp
- libs/pika/threading/tests/unit/condition_variable2.cpp
- libs/pika/threading/tests/unit/stop_token_cb1.cpp
- libs/pika/threading/tests/unit/thread.cpp
- tests/performance/local/CMakeLists.txt
Attempts to fix #23. One test I've disabled because I did not understand what could be causing the failure. The timed tests mostly seem to pass now, but may still fail occasionally.
> Adjust tests with sleeps

- .circleci/config.yml
- tools/inspect/CMakeLists.txt
This only renames the binary/target. Folder names still contain `Local`, see #50.
> Rename inspect_local to inspect

- libs/pika/affinity/src/parse_affinity_options.cpp
On the `gcc-11` builder `std::round` was not visible due to the missing include.
> Fix missing include in parse_affinity_options.cpp

- cmake/pika_add_module.cmake
The private flags were mistakenly propagated out from modules.
> Don't propagate private build flags to consumers

- libs/pika/datastructures/include/pika/datastructures/detail/small_vector.hpp
- libs/pika/datastructures/tests/unit/small_vector.cpp
This temporarily "fixes" a performance regression caused by using the new `small_vector` by forcing the use of Boost's `small_vector`. See #78 for details on the regression.
> Force the use of Boost's small_vector for performance

- libs/pika/async_cuda/src/cuda_event_callback.cpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_executor.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_future.hpp
- libs/pika/async_mpi/src/mpi_future.cpp
Fixes #41. Instead uses atomic counts for the vector/queue sizes. This means that `get_work_count` will never accidentally return zero if it can't take the lock. Related to https://github.com/eth-cscs/DLA-Future/issues/448.
Still waiting for some DLA-Future runs, but this at least improves (not necessarily fixes) the shutdown behaviour in miniapps.
> Don't try to take lock when getting work counts from MPI/CUDA polling

- README.rst
- shell.nix
Fixes #65, fixes #54.
@aurianer do you remember what version of HIP we require? If not, I suppose we just document the version that we test, which I think is 4.4 on GitHub actions. What are you using on ault?
Note, I've also included a `shell.nix` file. It's quite convenient for getting a development shell without the rebuilding hell that spack comes with. Once nix is installed you can get a development shell with all the dependencies installed with `nix-shell <path-to-repo>`.
> Document dependencies in README

- .github/workflows/linux_debug.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/macos_debug.yml
Finishes builds faster in case of timeouts (the default is 1500 seconds).
> Add shorter timeouts to GitHub actions tests

- .gitignore
When using `spack develop` spack creates various `spack-*` files and directories in the root of the repo that can be ignored.
> Ignore spack files

- .jenkins/cscs-perftests/Jenkinsfile
- .jenkins/cscs/Jenkinsfile
To avoid jobs like these taking 13 hours: https://lisone.cscs.ch/blue/organizations/jenkins/ssl%2Fpika/detail/pika/26/pipeline.
The underlying problem of the filesystem quota being full should of course also be addressed...
> Set conservative timeout on build steps in Jenkins

- .github/workflows/macos_debug.yml
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
- libs/pika/topology/src/topology.cpp
Also enables `PIKA_WITH_COMPILER_WARNINGS_AS_ERRORS` on CI.
> Fix unused parameters on macOS

- libs/pika/algorithms/tests/performance/foreach_report.cpp
This is a bit of a shot in the dark. The `perftests_report` utility already does one warmup iteration which I would've thought would be enough, but it's typically the `scheduler_executor` test on `foreach_report` which fails, and it's the first executor to run.
Maybe fixes #84.
> Add warmup iterations to foreach performance test

- libs/pika/execution/include/pika/execution/algorithms/bulk.hpp
- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/just.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/include/pika/execution/algorithms/then.hpp
- libs/pika/execution/include/pika/execution/algorithms/transfer.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all.hpp
- libs/pika/execution/tests/include/algorithm_test_utils.hpp
- libs/pika/execution/tests/unit/algorithm_bulk.cpp
- libs/pika/execution/tests/unit/algorithm_just.cpp
- libs/pika/execution/tests/unit/algorithm_let_error.cpp
- libs/pika/execution/tests/unit/algorithm_let_value.cpp
- libs/pika/execution/tests/unit/algorithm_split.cpp
- libs/pika/execution/tests/unit/algorithm_then.cpp
- libs/pika/execution/tests/unit/algorithm_transfer.cpp
- libs/pika/execution/tests/unit/algorithm_transfer_just.cpp
- libs/pika/execution/tests/unit/algorithm_when_all.cpp
Fixes #75.
See https://brycelelbach.github.io/wg21_p2300_std_execution/std_execution.html#spec-library for details (particularly the part about "arguments are not associated entities").
This does uglify the code quite a bit unfortunately, but is useful. In short, this means that for some e.g. sender type `template <typename... Ts>` any of the types `Ts...` will not contribute to ADL in e.g. a `tag_invoke(tag_t, sender<Ts...>`) call, only the namespace of `sender` itself contributes to ADL.
> Add ADL isolation to P2300 CPOs

- libs/pika/resource_partitioner/include/pika/resource_partitioner/detail/partitioner.hpp
The affinity data value of pus_needed should be returned instead.
> An uninitialized variable was being used for setting up pools

- libs/pika/runtime/src/custom_exception_info.cpp
- libs/pika/runtime/src/runtime.cpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
Fixes # too much annoying output on error.
> Set default verbosity to 1, stacktrace, but not all env{vars}

- .jenkins/cscs-perftests/env-perftests.sh
- .jenkins/cscs/env-clang-10.sh
- .jenkins/cscs/env-clang-12.sh
- .jenkins/cscs/env-clang-13.sh
- .jenkins/cscs/env-clang-9.sh
- .jenkins/cscs/env-clang-apex.sh
- .jenkins/cscs/env-clang-cuda.sh
- .jenkins/cscs/env-common.sh
- .jenkins/cscs/env-gcc-10.sh
- .jenkins/cscs/env-gcc-11.sh
- .jenkins/cscs/env-gcc-9.sh
- .jenkins/cscs/env-gcc-cuda.sh
Hopefully fixes Jenkins CI. `ccache` will also be updated separately (#104), but it does not seem to be required right now.
> Use even more specific spec for cmake and ninja in Jenkins CI

- libs/pika/threading_base/src/execution_agent.cpp
- libs/pika/threading_base/src/set_thread_state.cpp
- libs/pika/threading_base/tests/unit/CMakeLists.txt
- libs/pika/threading_base/tests/unit/resume_suspended_same_thread.cpp
This used to work but the changes seem to have been lost at some point. This also adds a test to verify the behaviour with the static scheduler (static since we want to guarantee that a thread runs where it's scheduled).
This is not super critical but I noticed this was missing when working on DLA-Future (https://github.com/eth-cscs/DLA-Future/pull/475).
> Reschedule threads on the worker thread where they were suspended again

- libs/pika/async_cuda/tests/unit/cuda_scheduler.cu
- libs/pika/execution/CMakeLists.txt
- libs/pika/execution/include/pika/execution/scheduler_queries.hpp
- libs/pika/execution/tests/unit/CMakeLists.txt
- libs/pika/execution/tests/unit/scheduler_queries.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
- libs/pika/tag_invoke/include/pika/functional/tag_invoke.hpp
Fixes #96 and #80.
Adds
- `forward_progress_guarantee` enum
- `get_forward_progress_guarantee` query
- `forwarding_scheduler_query` query
The last is currently not used anywhere (it's intended for checking generically if a query on a scheduler should be forwarded or not).
> Add P2300 scheduler queries

- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/tests/unit/algorithm_split.cpp
Fixes the reference counting for the shared state of `split`/`ensure_started`. It was being held with an additional unnecessary reference count by the `split_receiver` which is connected to the predecessor sender. This made the shared state stay alive longer than necessary.
Additionally it resets the operation state (resulting from connecting the predecessor sender to `split`/`ensure_started` to `split_receiver`) as soon as `set_x` has been called on `split_receiver`. This releases resources as early as possible, since the operation state is no longer needed after `set_x` has been called.
This was triggered by the work in https://github.com/eth-cscs/DLA-Future/pull/475 where the RAII nature of `Tile` revealed deadlocks unless the operation state is released as early as possible.
Note that …
> Fix `split`/`ensure_started` shared state reference counting

- libs/pika/coroutines/include/pika/coroutines/detail/context_base.hpp
- libs/pika/runtime/include/pika/runtime/custom_exception_info.hpp
- libs/pika/runtime/src/custom_exception_info.cpp
- libs/pika/threading_base/src/execution_agent.cpp
This is also related to the work in https://github.com/eth-cscs/DLA-Future/pull/475. The underlying bug is fixed separately, but this fixes a side effect that was revealed by the bug, which I don't see a reason to allow, namely yielding pika threads with uncaught exceptions.
This was triggered by a test:
- throwing an exception
- the destructor for an unsatisfied promise running
- the destructor trying to construct an exception
- the exception construction trying to collect a stacktrace
- the stacktrace collection being launched on another thread
- the exception construction waiting for the completion of the stacktrace by suspending/yielding
- the exception construction thread waking up on another worker thread (this happens sometimes with the stealing schedulers, also see #110)
Since the …
> Don't allow yielding with uncaught exceptions

- libs/pika/config/include/pika/config.hpp
- libs/pika/execution_base/include/pika/execution_base/detail/spinlock_deadlock_detection.hpp
- libs/pika/execution_base/include/pika/execution_base/this_thread.hpp
- libs/pika/execution_base/src/spinlock_deadlock_detection.cpp
- libs/pika/execution_base/src/this_thread.cpp
- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/runtime_configuration/include/pika/runtime_configuration/runtime_configuration.hpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
- libs/pika/synchronization/src/stop_token.cpp
- libs/pika/threading/tests/unit/condition_variable2.cpp
- libs/pika/threading/tests/unit/condition_variable3.cpp
- libs/pika/threading/tests/unit/condition_variable4.cpp
- libs/pika/threading/tests/unit/condition_variable_race.cpp
- libs/pika/threading/tests/unit/jthread1.cpp
- libs/pika/threading/tests/unit/jthread2.cpp
Attemps to fix the deadlocks that seem to happen occasionally in the `condition_variable2/4` tests. The deadlocks seem related to `stop_token` in the sense that previously if a stop request comes in at a bad moment compared to when a `stop_callback` is created, the `stop_callback` will execute but will not mark itself as executed. While removing the callback it will then wait (in vain) for the callback to first have been executed (which it has, but it has not been marked as executed).
The first three commits of this PR slightly refactor the deadlock detection mechanism we have to first print a warning at a lower iteration count. This also reduces the limit at which an exception is thrown when deadlock detection is enabled. I hope I've not reduced the limit too far but it's still …
> Attempt to fix deadlocks in `condition_variable`

- libs/pika/topology/src/topology.cpp
The struct is unused (it used to be used for thread-local storage, but that's long gone). I've also moved the helper struct `hw_concurrency` into `detail`.
> Remove unused `hardware_concurrency_tag`

- .jenkins/cscs-perftests/env-perftests.sh
- .jenkins/cscs/env-clang-cuda.sh
- .jenkins/cscs/env-gcc-cuda.sh
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
Some of the modules have changed and been removed, so I'm being lazy with Boost and hwloc by just hardcoding their roots for the configurations where they were previously loaded through modules.
This is even more reason to just fully move over to spack environments (#121).
> Update jenkins configurations after Piz Daint upgrade

- libs/pika/execution/CMakeLists.txt
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/execution/tests/include/algorithm_test_utils.hpp
- libs/pika/execution/tests/unit/CMakeLists.txt
- libs/pika/execution/tests/unit/algorithm_when_all_vector.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
This is an adaptor like when_all, but specialized to take a vector of senders and signal the continuation when all senders in the vector have completed. It requires that the senders send a single type, or none at all. If they send nothing, the sender returned by when_all_vector also sends nothing.
Fixes #86, at least the minimum required case for DLA-Future.
Note that this currently only works with a vector of senders. Open questions for future work are:
1. Can this be optimized to allocate less? There are currently many separate heap allocations within this adaptor which could potentially be unified.
2. Can this be generalized in some reasonable way? It could handle any ranges or iterator/sentinel pairs. What container should it send in that case? It could handle nested senders, like …
> Add `when_all_vector` sender adaptor

- libs/pika/include/include/pika/runtime.hpp
Fixes #59. This simply adds the headers to `pika/runtime.hpp` as I think they should all be considered one inseparable unit.
> Add threadmanager and resource partitioner headers to `pika/runtime.hpp`

- libs/pika/async_cuda/CMakeLists.txt
- libs/pika/async_cuda/include/pika/async_cuda/cuda_pool.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/src/cuda_pool.cpp
- libs/pika/async_cuda/src/then_with_stream.cpp
After the initial attempt of having a global pool of streams in `cuda_pool` I'm reverting it back to what DLA-Future used originally, i.e. thread-local streams. To avoid having to create the `cuda_pool` after the pika runtime I simply create a vector with `hardware_concurrency * num_streams_per_thread`. pika worker threads will have their thread number set and index into the vector with the thread number. non-pika threads will have their thread number set to `-1` and will all use the same "thread-local" streams, but at least they will fall back to a valid stream. I create one vector of streams instead of using `thread_local` streams to avoid calling CUDA API functions at arbitrary points when the `thread_local`s are accessed the first time.
I've also moved the `thread_local` …
> Thread-local streams in `cuda_pool`

- CMakeLists.txt
- libs/pika/async_cuda/tests/performance/cuda_executor_throughput.cpp
- libs/pika/async_cuda/tests/performance/synchronize.cu
- libs/pika/async_cuda/tests/unit/cublas_handle.cu
- libs/pika/async_cuda/tests/unit/cublas_matmul.cpp
- libs/pika/async_cuda/tests/unit/cuda_bulk.cu
- libs/pika/async_cuda/tests/unit/cuda_future.cpp
- libs/pika/async_cuda/tests/unit/cuda_pool.cu
- libs/pika/async_cuda/tests/unit/cuda_scheduler.cu
- libs/pika/async_cuda/tests/unit/cuda_stream.cu
- libs/pika/async_cuda/tests/unit/cusolver_handle.cu
- libs/pika/async_cuda/tests/unit/saxpy.cu
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
- libs/pika/async_cuda/tests/unit/trivial_demo.cu
- libs/pika/async_mpi/tests/unit/algorithm_transform_mpi.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_executor.cpp
- libs/pika/include/CMakeLists.txt
- libs/pika/include/include/pika/cuda.hpp
- libs/pika/include/include/pika/mpi.hpp
Fixes #57.
Also updates tests and examples to use them.
I'm calling the "GPU" header `pika/cuda.hpp` still at the moment because all the functionality has `cuda` the names or lives in the `cuda` namespace. We should, however, start considering replacing the `cuda` terminology with a more generic `gpu` (as has been started e.g. with `PIKA_WITH_GPU_SUPPORT`). See #116.
As a flyby I've changed some more `pika/modules/x.hpp` includes in the MPI/CUDA tests and examples to use the API headers.
> Add `pika/cuda.hpp` and `pika/mpi.hpp` API headers

- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/execution/tests/unit/algorithm_when_all_vector.cpp
> Make sure `when_all_vector` works with noncopyable types

- libs/pika/include/CMakeLists.txt
`pika_async_cuda` was being linked when `pika_async_mpi` should've been linked.
> Fix typo in include module CMakeLists.txt

- CHANGELOG.md
Assuming CI gets back soon on daint I think we're close to a 0.2.0 release. I've started putting together release notes for it.
Do we like this format? Do we want to list and link PRs/issues like we used to do in HPX? Any other comments?
> Release notes for 0.2.0

- libs/pika/functional/include/pika/functional/bind_front.hpp
Fixes #130.
Flyby: replaced `::type` and `::value` uses with `_t` and `_v` in the `bind_front.hpp` file.
> Don't unwrap reference_wrapper in bind_front

- libs/pika/async_mpi/src/mpi_future.cpp
Minor debugging help. It was previously only checked when using futures, not when using senders. Helps with https://github.com/eth-cscs/DLA-Future/pull/497.
> Check that MPI polling has been registered also when using senders

- libs/pika/init_runtime/include/pika/init_runtime/init_runtime.hpp
- libs/pika/init_runtime/tests/unit/CMakeLists.txt
- libs/pika/init_runtime/tests/unit/const_args_init.cpp
> Make argc and argv const in init to avoid having to cast

- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/tests/unit/CMakeLists.txt
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
The checks for invocability were not correctly testing with lvalue references. This meant that functions which take references to noncopyable types would incorrectly be diagnosed as not invocable. This also adds a regression test. Fixes #136.
> Fix SFINAE in `then_with_stream`

- .jenkins/cscs/env-clang-cuda.sh
At least this seems to work even with the oldest supported CMake 3.18.
> Remove explicit architecture flag for clang CUDA jenkins config because `CMAKE_CUDA_ARCHITECTURES` is enough

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
Fixes #93. The two share no code now. As an optimization `split` could use the shared state of `ensure_started`, but I'm leaving that for maybe-in-the-future.
> Separate `split` and `ensure_started`

- libs/pika/affinity/include/pika/affinity/affinity_data.hpp
- libs/pika/affinity/include/pika/affinity/parse_affinity_options.hpp
- libs/pika/affinity/src/affinity_data.cpp
- libs/pika/affinity/src/parse_affinity_options.cpp
- libs/pika/executors/tests/unit/standalone_thread_pool_executor.cpp
- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/detail/create_partitioner.hpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/detail/partitioner.hpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/partitioner.hpp
- libs/pika/resource_partitioner/src/detail_partitioner.cpp
- libs/pika/resource_partitioner/src/partitioner.cpp
- libs/pika/schedulers/include/pika/schedulers/local_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/local_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp
- libs/pika/threading_base/include/pika/threading_base/thread_pool_base.hpp
Move all functionality to detail namespace, replace typedef with using, use compact C++17 namespace declarations. Part of #16.
> Clean up affinity module

- libs/pika/algorithms/tests/unit/container_algorithms/foreach_tests.hpp
- libs/pika/async_cuda/tests/performance/synchronize.cu
- libs/pika/async_cuda/tests/unit/cuda_bulk.cu
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
- libs/pika/async_mpi/tests/unit/algorithm_transform_mpi.cpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/tests/unit/algorithm_split.cpp
- libs/pika/execution/tests/unit/algorithm_sync_wait.cpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
- libs/pika/executors/include/pika/executors/scheduler_executor.hpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
- libs/pika/synchronization/tests/unit/async_rw_mutex.cpp
- libs/pika/threading_base/tests/unit/annotation_check.cpp
P2300 defines `sync_wait` in `std::this_thread`. This moves our `sync_wait` to `pika::this_thread` to be analogous to the proposed one.
> Move `sync_wait` to `pika::this_thread` namespace

- .circleci/config.yml
- CMakeLists.txt
- cmake/pika_setup_vc.cmake
The `filesystem` module does not have a `pika/modules/filesystem.hpp` header (and I don't think it needs one), so I've removed it from the precompiled header.
> Fix compilation with precompiled headers

- .circleci/config.yml
- cmake/templates/config_defines_strings.hpp.in
- cmake/templates/global_module_header.hpp.in
- cmake/templates/modules_enabled.hpp.in
- libs/pika/async_cuda/tests/unit/cuda_scheduler.cu
- libs/pika/async_cuda/tests/unit/cuda_stream.cu
- libs/pika/async_cuda/tests/unit/saxpy.cu
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
- libs/pika/config/cmake/templates/config_defines.hpp.in
- libs/pika/config/cmake/templates/config_version.hpp.in
- tests/performance/local/htts_v2/htts2.hpp
This expands the existing check to include all C++/CUDA files, not just C++ files in modules. The templates needed some `clang-format off` to avoid reformatting the actual template parts of them (`clang-format` wants to turn `@var@` into `@var @`).
Fixes #168.
> Format all C++ files and enforce it in CI

- libs/pika/async_cuda/include/pika/async_cuda/cuda_scheduler_bulk.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
Fixes #138 together with #156. The changes here are very similar to in #156, i.e. instead of storing the callable, the successor receiver, the scheduler, and the values sent from the predecessor in the `then_with_cuda_stream_receiver` they are now stored in the operation state. This simplifies the handling of the callback as we can just capture a reference to the operation state in the event callback.
> Store values sent from predecessor to `then_with_stream` in operation state

- libs/pika/version/CMakeLists.txt
- libs/pika/version/include/pika/version.hpp
- libs/pika/version/src/version.cpp
- libs/pika/version/tests/CMakeLists.txt
- libs/pika/version/tests/unit/CMakeLists.txt
- libs/pika/version/tests/unit/constexpr_version.cpp
Part of #16. Removes hwloc, boost and mpi dependency in the `version` module.
> Clean up `version` module

- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
I missed this in #156 :/ Potentially worth a 0.3.1, or at least a patch in the spack package.
> Add missing includes to `transform_mpi.hpp`

- libs/pika/execution/include/pika/execution/algorithms/then.hpp
- libs/pika/execution/tests/unit/algorithm_then.cpp
Fixes #181
The problem is that `tag_invoke` of any tag instantiates the enable_if, before the function is excluded from the overload set. For generic lambdas the body has to be instantiated to get the return type which is a hard error.
To my understanding there is nothing to disambiguate in the `then::tag_invoke(set_value, ...)` and it can be removed (alternatively the enabler can be put in a trailing return type).
Maybe this is a general problem of the tag_invoke mechanism? C++20 constraints have the same problem. I am wondering about compile time of codes with many tag_invoke overloads if all non-trailing constraints might have to be evaluated. Or am I missing something?
> Remove enabler in `then`'s `set_value`

- cmake/pika_setup_boost.cmake
Fixes #183. `thread` and `chrono` are not needed anymore. They may be an artifact of missing dependencies with previous Boost CMake configurations. These dependencies were added when requiring Boost 1.51.0 in HPX.
> Remove unnecessary boost dependencies when `PIKA_WITH_GENERIC_CONTEXT_COROUTINES=ON`

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
Keep one reference alive in the `ensure_started_receiver` in case the `ensure_started_sender` is discarded without being connected.
Fixes #174. I improved the situation for `split` in #111, but made it worse for `ensure_started`. If the sender from `ensure_started` is discarded (which is allowed) the shared state would be released immediately because the receiver from `ensure_started` only kept a reference to the shared state (not a counted reference). This makes the reference an `intrusive_ptr` again. After #143 `ensure_started` sends rvalues to connected receivers which means that the `ensure_started_receiver` holding onto stored values is less of a concern. ~Just in case, I'm still resetting the shared state after continuations have been signaled.~ (Edit: the extra reset is not …
> Change reference counting again in ensure_started

- libs/pika/executors/include/pika/executors/thread_pool_scheduler.hpp
- libs/pika/threading_base/include/pika/threading_base/scoped_annotation.hpp
- libs/pika/threading_base/tests/unit/CMakeLists.txt
- libs/pika/threading_base/tests/unit/annotation_check_futures.cpp
- libs/pika/threading_base/tests/unit/annotation_check_senders.cpp
Fixes #172.
Changes the behaviour of `execute` and `schedule` for `thread_pool_sheduler` to take a fallback annotation from the calling context. Also customizes `schedule_from` for `thread_pool_scheduler` in order to get the fallback annotation from the context where `transfer` is called. The default `transfer` implementation otherwise calls `schedule` only when it's time to schedule the new task, which would inherit the wrong annotation without the `schedule_from` customization.
Open issues that will likely be left out from this PR:
- APEX develop seems to have changed the output format when screen output is enabled. I think we will have to change how the annotation tests check for correct output, but I'm still targeting this against the latest release of APEX.
- The `schedule_from` …
> Inherit annotations from scheduling task instead of spawning task in `transfer` for `thread_pool_scheduler`

- .circleci/config.yml
- .github/bors.toml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_hip.yml
- .github/workflows/linux_release_fetchcontent.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/macos_debug.yml
Draft. Requires #23 before this makes sense. Testing that the Jenkins commit statuses etc. work correctly.
Fixes #31.
> Require Jenkins jobs for bors merges

- libs/pika/executors/include/pika/executors/thread_pool_scheduler_bulk.hpp
- libs/pika/threading_base/include/pika/threading_base/scoped_annotation.hpp
- libs/pika/threading_base/tests/unit/CMakeLists.txt
- libs/pika/threading_base/tests/unit/annotation_check_senders.cpp
Also fixes #172.
This sets the annotations for "bulk regions" spawned by the `bulk` customization for `thread_pool_scheduler` as described in https://github.com/pika-org/pika/issues/172#issuecomment-1096447599. Annotations set on the element-wise function are lifted up to a scoped annotation around the work loop on each worker thread, and annotations already set on the pika thread are propagated to the worker threads as well.
A quirk of how APEX counts functions means that the counts that are checked for the test may not immediately make sense. APEX counts "calls" only for newly created annotations which happens when spawning a pika thread. "Nested" annotations (created e.g. with `scoped_annotation`) count as "yields". They don't show up in the APEX screen output in the latest version of …
> Update annotations for thread_pool_scheduler bulk customization

- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
I think I used this for testing at some point. It's no longer needed.
> Remove leftover `using pika::functional::tag_invoke` from `thread_pool_scheduler` test

- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/tests/regressions/CMakeLists.txt
- libs/pika/execution/tests/regressions/split_continuation_clear.cpp
Fixes another lifetime bug in the `split` sender adaptor. The comments in the code and regression test explain the failure mode. The regression test fails almost every run without the fix and does not fail with the fix.
> Fix lifetime bug in `split`

- libs/pika/executors/CMakeLists.txt
- libs/pika/executors/include/pika/executors/std_thread_scheduler.hpp
- libs/pika/executors/tests/unit/CMakeLists.txt
- libs/pika/executors/tests/unit/std_thread_scheduler.cpp
Fixes #167. This has no fancy features (does not reuse threads, no annotations, no bulk customization, etc.). The forward progress guarantee is `weakly_parallel` because of the serial (default) bulk implementation.
> Add `std_thread_scheduler`

- tools/pre-commit
just updates the hook script with a new VAR that we can update each time the clang-format requirement/version changes
> Bump pre-commit hook script clang-format version to 11

- libs/pika/resource_partitioner/tests/unit/cross_pool_injection.cpp
Reduces the number of iterations, but hopefully still keeps the test useful for triggering bugs. With 1000 iterations the test takes around 2 minutes on CircleCI and is clearly the longest-running test we have. I'm hoping this will bring it down to around a minute.
> Reduce the number of iterations in `cross_pool_injection` test

- .github/workflows/macos_debug.yml
Attempt to slightly shorten the time taken by the macOS configuration.
> Run tests in parallel on macOS CI configuration

- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/command_line_handling/src/parse_command_line.cpp
Fixes #199. Don't accept arguments to `--pika:help` anymore since dynamically loaded command line options aren't supported.
> Fix `--pika:help` command line argument

- README.rst
Part of #49.
I've listed a subset of the headers in the `include` module. I've left out `pika/future.hpp` and `pika/unwrap.hpp` as they're due for removal (though DLA-Future is free to keep using it until then). I've also left out all the utilities that don't really require special versions for user-level threads, meaning `functional`, `any`, `optional`, `chrono`, `exception`, `stop_token`, `system_error`, `tuple`, and `type_traits`. I've left out `task_block` as it's similar in spirit to the proposed `async_scope` and could probably be removed if that works as a replacement.
Fixes a few typos as a flyby in the README.
> Add list of public API headers to README

- tools/perftests_ci/perftest/plot.py
They got garbled in https://github.com/pika-org/pika/pull/224, though it's not clearly black that is the cause of it. Running black again on the file did not change the symbols, so I'm not quite sure what happened.
> Fix unicode symbols in `plot.py`

- cmake/pika_setup_hip.cmake
- libs/pika/async_cuda/CMakeLists.txt
- libs/pika/async_cuda/include/pika/async_cuda/cuda_scheduler_bulk.hpp
- libs/pika/async_cuda/include/pika/async_cuda/cusolver_exception.hpp
- libs/pika/async_cuda/include/pika/async_cuda/cusolver_handle.hpp
- libs/pika/async_cuda/include/pika/async_cuda/custom_blas_api.hpp
- libs/pika/async_cuda/include/pika/async_cuda/custom_lapack_api.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/src/cusolver_exception.cpp
- libs/pika/async_cuda/src/cusolver_handle.cpp
- libs/pika/async_cuda/src/then_with_stream.cpp
- libs/pika/async_cuda/tests/performance/cuda_scheduler_throughput.cpp
- libs/pika/async_cuda/tests/unit/CMakeLists.txt
- libs/pika/async_cuda/tests/unit/cublas_handle.cu
- libs/pika/async_cuda/tests/unit/cublas_matmul.cpp
- libs/pika/async_cuda/tests/unit/cuda_scheduler.cu
- libs/pika/async_cuda/tests/unit/cuda_sender.cu
- libs/pika/async_cuda/tests/unit/cusolver_handle.cu
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
> Add `then_with_cusolver` support for HIP

- .github/bors.toml
- .github/workflows/macos_debug.yml
- libs/pika/algorithms/tests/unit/algorithms/CMakeLists.txt
- libs/pika/algorithms/tests/unit/algorithms/detail/CMakeLists.txt
- libs/pika/algorithms/tests/unit/algorithms/util/CMakeLists.txt
Further reduces the waiting time for the macOS builds, bringing the total time down from roughly 45-60 minutes to 20-30 minutes. Note the comments in the workflow file. There's duplication that I'm not willing to remove at this point.
This also fixes the intermediate targets for `tests.unit.modules.algorithms.algorithms.{util,detail}`.
> Split up macOS CI tests into multiple jobs

- .github/workflows/linux_hip.yml
- .github/workflows/linux_sanitizers.yml
- README.rst
Part of #4. Adds a "bors enabled" badge, CircleCI, and GitHub actions badges.
> Add CircleCI and GitHub actions status badges

- libs/pika/executors/tests/unit/std_thread_scheduler.cpp
I think this fixes part of #191 (the `std_thread_scheduler_test` failures). The sender is still discarded immediately so that part is still somewhat tested, but we attempt to wait for the detached `std::thread` to avoid having it possibly start after exiting main.
> Attempt to wait for detached thread to finish in `std_thread_scheduler_test`

- cmake/pika_setup_p2300.cmake
- libs/pika/async_cuda/include/pika/async_cuda/cuda_scheduler.hpp
- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
- libs/pika/execution/tests/unit/algorithm_execute.cpp
- libs/pika/execution/tests/unit/algorithm_then.cpp
- Use fixed commit from upstream repository
- Add a few more ADL-isolation tests
- Make P2300 includes system includes
- Remove unnecessary default constructor for an operation state
- Remove unused test struct for `execution::then`
> Small modifications to P2300 integration

- examples/1d_stencil/1d_stencil_4.cpp
- examples/transpose/transpose_smp.cpp
- examples/transpose/transpose_smp_block.cpp
- libs/pika/algorithms/include/pika/parallel/spmd_block.hpp
- libs/pika/iterator_support/CMakeLists.txt
- libs/pika/iterator_support/include/pika/iterator_support/irange.hpp
- libs/pika/iterator_support/tests/performance/stencil3_iterators.cpp
- libs/pika/iterator_support/tests/unit/CMakeLists.txt
- libs/pika/iterator_support/tests/unit/irange.cpp
Part of #12. Adds a simple replacement for `boost::ranges::irange` (`pika::detail::irange` and `pika::detail::strided_irange`).
> Add simple `boost::ranges::irange` replacement

- libs/pika/threading/tests/unit/tss.cpp
I broke this in #257. I'm doing the smallest change to fix the used namespace here. The `threading_base` module will anyway be cleaned up at a later point, so I'm not moving the functionality to actually be in `detail` here.
> Fix compilation of tss test

- libs/pika/futures/tests/regressions/wait_for_1751.cpp
This often fails with waiting times just above the tolerance (~1.15) so I'm increasing it.
> Increase time tolerance in `wait_for_1751` test

- cmake/pika_setup_allocator.cmake
Not necessary since we are not relying on mimalloc APIs, but only linking to it for a faster malloc.
> Remove mimalloc version constraint

- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
The helpers deduce the types sent by the given sender and instantiate a `(unique_)any_sender` with the appropriate type. A deduction guide is not sufficient for this purpose.
> Add `make(_unique)_any_sender` helper functions

- libs/pika/execution/CMakeLists.txt
- libs/pika/execution/include/pika/execution/algorithms/drop_value.hpp
- libs/pika/execution/tests/unit/CMakeLists.txt
- libs/pika/execution/tests/unit/algorithm_drop_value.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
Adds a `drop_value` sender adaptor. It ignores any values sent by a predecessor sender. E.g.:
```
just(1, "hello", Tile{}) | drop_value() | then([](/* nothing here */) {...});
```
This is useful for https://github.com/eth-cscs/DLA-Future/pull/572.
I went for singular `value` instead of `values` to mirror `let_value/error` and `upon_error/stopped` (`then` is "`upon_value`") which all use singular and it mirrors the "channel name" (`value`, `error`, `stopped`). An alternative to `drop` would perhaps be `ignore`.
Note that I'm not adding `drop_error` and `drop_stopped` because 1. I don't want to encourage that and 2. it's not quite clear what they would do (sending no values in `set_value` is fine, but sending no error in `set_error` makes no sense and isn't allowed).
Opinions?
> Add `drop_value` sender adaptor

- libs/pika/command_line_handling/include/pika/command_line_handling/command_line_handling.hpp
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/init_runtime/include/pika/init_runtime/init_runtime.hpp
- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/init_runtime/tests/unit/const_args_init.cpp
Removes const on the values themselves passed in `argc` and the pointer for `argv`. Adds `const` to the _pointees_ in `argv`.
> Fix constness in `init`/`start` overloads

- .circleci/config.yml
Temporarily testing to see if disabling glibc's tcache would reduce the error rate on the `std_thread_scheduler` test (see https://github.com/pika-org/pika/pull/250#issuecomment-1150765258). Cf. https://github.com/pika-org/pika/issues/281.
> Disable glibc's tcache temporarily in CircleCI

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/tests/include/algorithm_test_utils.hpp
- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
- libs/pika/execution/tests/unit/algorithm_transfer.cpp
Fixes handling of reference types sent to `ensure_started` and `schedule_from`. Other algorithms also need to be checked for the same problem, but I'm doing it in separate PRs.
> Fix handling on reference types in sent by predecessors to `ensure_started` and `schedule_from`

- libs/pika/affinity/include/pika/affinity/affinity_data.hpp
- libs/pika/affinity/src/affinity_data.cpp
- libs/pika/command_line_handling/include/pika/command_line_handling/command_line_handling.hpp
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/init_runtime/src/init_runtime.cpp
The process mask was being taken into account for the _number_ of threads, but not for the actual affinity data (in `affinity_data`). This lead me to believe that things were working ok, but things were apparently slightly off. This meant that e.g. multiple ranks on a single node had overlapping thread bindings.
In an attempt to simplify things I've renamed some variables back to what they were before #242. Now everything internal is again called `use_process_mask` whereas _only_ the command line and configuration options are called `ignore_process_mask`, and the given options are translated to `use_process_mask` as soon as possible. I prefer `use_process_mask` internally since it's the "positive" form.
> Fix `--pika:ignore-process-mask`

- libs/pika/async_mpi/include/pika/async_mpi/mpi_executor.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_future.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/src/mpi_future.cpp
- libs/pika/async_mpi/tests/unit/CMakeLists.txt
- libs/pika/async_mpi/tests/unit/mpi_async_storage.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_executor.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
- libs/pika/debugging/include/pika/debugging/print.hpp
- libs/pika/debugging/src/print.cpp
- libs/pika/threading_base/src/print.cpp
Fixes part of #184.
This extends and replaces PR #204 (this PR is rebased onto current main branch)
Eager checks on send/recv calls are a useful improvement as mpi implementations may make use of `inject` semantics on some messages, which can complete immediately and therefore do not need to be polled for, including this does not impost a significant cost and can save time overall.
This PR adds throttling of MPI traffic to help prevent excessive message queues which can happen when a loop spwans many send or recv calls.
I addition, the PR includes a major cleanup of the mpi handling/polling code and also adds `testsome` in place of `testany` - which ought to be a slight performance improvement, but in timings does not seem to make any difference.
> Eagerly check for MPI request completion in `transform_mpi` and permit throttling

- libs/pika/execution/tests/unit/algorithm_when_all.cpp
> Add reference handling test for `when_all` sender adaptor

- .github/bors.toml
- .github/workflows/linux_tracy.yml
- libs/pika/thread_pools/include/pika/thread_pools/scheduling_loop.hpp
- libs/pika/threading_base/include/pika/threading_base/scoped_annotation.hpp
Fixes the build with Tracy, and since I managed to break the build in record time I'm also adding a simple GitHub actions workflow which builds examples and runs `hello_world`. We still can't run all executables because threads can't yield with the Tracy integration.
> Fix Tracy integration

- libs/pika/async_mpi/tests/unit/mpi_async_storage.cpp
Fixes things that were missed in #277.
@biddisco can you confirm that the mutex really was intended to be unused?
> Fix compilation of `mpi_async_storage` test

- .jenkins/cscs-perftests/Jenkinsfile
- .jenkins/cscs/Jenkinsfile
- .jenkins/cscs/env-common.sh
Fixes half of #299.
I've also moved the `SPACK_ROOT` definition to `env-common.sh` to 1. have it only in one place and 2. to have it together with the rest of the environment. It doesn't actually need to be set in the `Jenkinsfile`, unlike the GitHub credentials.
Edit: I updated this to only move the ccache directory for the moment. The spack user cache directory seems to be a bit more complicated...
> Move ccache directory to `jenkssl` scratch in Jenkins jobs

- libs/pika/async_cuda/include/pika/async_cuda/cuda_scheduler.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_on_host.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
Part 1/n to fix #302. This adds changes that in principle enable the use of `PIKA_WITH_P2300_REFERENCE_IMPLEMENTATION=ON` with CUDA. In practice it means that these changes can be correctly parsed when compiling host code but Cray's clang fails with an ICE when parsing `ranges`. Even though this is only part of the solution, as long as I'm not breaking any existing configuration I'd like to get this in separately. I will continue the hunt for a working clang configuration separately.
> Preliminary support for using the P2300 reference implementation with CUDA

- libs/pika/async_cuda/include/pika/async_cuda/detail/cuda_event_callback.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/src/cuda_event_callback.cpp
- libs/pika/async_cuda/tests/unit/cuda_scheduler.cu
Slight refactoring of the CUDA polling implementation. The actual polling mechanism is completely unchanged. I've only refactored the queues and free functions into a class so that it's easier to create multiple instances. There are now two polling queues, one for normal priority streams and one for high priority streams. The interface for adding callbacks is almost unchanged. The only difference is that it now requires a `cuda_stream` which has an embedded `pika::execution::thread_priority` instead of having to query a `cudaStream_t`.
Performance is minimally improved with small blocksizes in DLA-Future, so this is primarily about refactoring the code to be slightly more manageable, not a performance improvement.
> Add priorities for CUDA polling

- libs/pika/execution/include/pika/execution/algorithms/when_all.hpp
- libs/pika/execution/tests/include/algorithm_test_utils.hpp
- libs/pika/execution/tests/unit/algorithm_when_all.cpp
- libs/pika/execution/tests/unit/algorithm_when_all_vector.cpp
> Add `when_all` test and handling for const reference error types

- libs/pika/async_cuda/include/pika/async_cuda/detail/cuda_event_callback.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/src/cuda_event_callback.cpp
Unfortunately we still use `add_event_callback` for special purposes in DLA-Future. Until we decide if we make `add_event_callback` public or come up with another solution in DLA-Future I'm adding back an overload that takes a raw `cudaStream_t`. I changed it to take our wrapper `cuda_stream` in #286, but since `cuda_stream` is owning one can't use a self-created `cudaStream_t` with it. This allows that again for the time being.
> Add back overload taking a raw `cudaStream_t` for `add_event_callback`

- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
Leftover from #315. It didn't affect any builds since CUDA with the P2300 reference implementation is still untested and unsupported.
> Fix use of `tuple` and `variant` in `then_with_stream`

- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/tests/include/algorithm_test_utils.hpp
- libs/pika/execution/tests/unit/algorithm_split.cpp
- libs/pika/execution/tests/unit/algorithm_sync_wait.cpp
We already had it enabled in the header, but I had forgotten to remove the ifdefs in the test file. This also fixes part of #284 for `sync_wait` and `split` since those were broken after updating the test.
To do:
> Enable tests for P2300 reference implementation split

- .jenkins/cscs/batch.sh
The `$!` command was getting the result of the `cp` command instead of the `ctest` one.
> Fix position of the `ctest_exit_code` initialization in CI batch script

- .jenkins/cscs/install_spack_specs.sh
This is what I've been using to update/add Jenkins configurations. The script needs to be run in the `.jenkins/cscs` directory.
> Add script to install spack build environments for Jenkins

- libs/pika/async_cuda/include/pika/async_cuda/custom_gpu_api.hpp
- libs/pika/async_cuda/src/cuda_event_callback.cpp
Fixes the CUDA part of #184. However, this is untested and if it doesn't show any improvement (or worse, a performance drop) this shouldn't be merged.
Based on #286.
> Eagerly check completion of CUDA kernels

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
- libs/pika/execution/tests/unit/algorithm_bulk.cpp
- libs/pika/execution/tests/unit/algorithm_drop_value.cpp
- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
- libs/pika/execution/tests/unit/algorithm_let_error.cpp
- libs/pika/execution/tests/unit/algorithm_then.cpp
- libs/pika/execution/tests/unit/algorithm_transfer.cpp
> Handle reference error types in `ensure_started` and `let_error`

- libs/pika/concurrency/tests/unit/contiguous_index_queue.cpp
Increase the size of the range to reduce chance of false positives. This is to avoid these kind of test failures: https://cdash.cscs.ch/test/29487306.
> Reduce chance of false positives in `contiguous_index_queue` test

- libs/pika/algorithms/tests/unit/container_algorithms/foreach_tests.hpp
- libs/pika/async_cuda/tests/performance/synchronize.cu
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
- libs/pika/async_mpi/tests/unit/algorithm_transform_mpi.cpp
- libs/pika/execution/include/pika/execution/algorithms/start_detached.hpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/tests/unit/algorithm_start_detached.cpp
- libs/pika/execution/tests/unit/algorithm_sync_wait.cpp
- libs/pika/executors/tests/unit/std_thread_scheduler.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
- libs/pika/synchronization/tests/unit/async_rw_mutex.cpp
> Remove `operator|` overloads for `sync_wait` and `start_detached`

- .github/workflows/macos_debug.yml
I'm increasing the timeout to check if these timeouts https://github.com/pika-org/pika/runs/7692289838?check_suite_focus=true#step:6:237 are simply due to the test taking long to complete or if it really hangs. `partial_sort_copy_range` is one of the longer running tests so it's possible that it indeed just doesn't have enough time to finish (the timeout is 120 seconds and one of the later runs finished in 101 seconds: https://github.com/pika-org/pika/runs/7691710341?check_suite_focus=true#step:6:237).
> Increase timeout for container algorithms tests on macOS CI configuration

- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
Fixes the condition used for checking if a process mask should be used or not. Also adds a default `pika.ignore_process_mask = 0` option to the runtime configuration so that adding the option manually doesn't error out complaining about a nonexistent entry in the configuration.
Thanks @aurianer for noticing this.
> Fix use of `--pika:ignore-process-mask` command line option

- .github/workflows/macos_debug.yml
Follow-up to #352. Also increase the timeout for the algorithms tests. `partial_sort_copy` (like `partial_sort_copy_range`) takes long to complete, most likely just due to insufficient time.
> Increase algorithms tests timeout in macOS workflow

- libs/pika/program_options/include/pika/program_options/value_semantic.hpp
Fixes #350. It's slightly unclear to me why this is required as I assumed that a visibility attribute on the class itself would be enough, but it may be that the ruls for template specializations are different or something in that direction...
> Attempt to fix `program_options` visibility issue

- .github/workflows/linux_coverage.yml
Changing coverage CI job to only run on `main`.
> Only run coverage on `main` branch

- .github/bors.toml
- .github/workflows/linux_coverage.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_hip.yml
- .github/workflows/linux_release_fetchcontent.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/linux_tracy.yml
- .github/workflows/macos_debug.yml
This uses https://github.com/hendrikmuhs/ccache-action. Note that an explicit key is given for the cache since caches are otherwise shared between workflows.
> Use ccache in GitHub actions workflows

- .github/workflows/macos_debug.yml
In an attempt to make better use of the cache. The default limit is 500 MB and the cache is typically around 400 MB from one run. We may need to go back to the non-ccache, split setup for macOS if this doesn't work so well.
> Increase maximum ccache cache size on macOS workflow

- libs/pika/filesystem/docs/index.rst
- libs/pika/filesystem/src/filesystem.cpp
Part of #16. Not much to do here...
> Clean up filesystem module

- libs/pika/execution/tests/unit/algorithm_bulk.cpp
- libs/pika/execution/tests/unit/algorithm_let_error.cpp
Part of #284.
- Slightly changes the test for `bulk`
- Adds a `const_reference_sender` test for `let_error`
- Enables the `const_reference_error_sender` test for `let_error` with the P2300 reference implementation
Also note that I've listed what still needs to be checked/updated in #284.
> Fix a few more reference type sender issues

- libs/pika/async_cuda/tests/performance/cuda_scheduler_throughput.cpp
- libs/pika/async_cuda/tests/unit/cuda_sender.cu
- libs/pika/execution/tests/unit/algorithm_bulk.cpp
- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
- libs/pika/functional/tests/regressions/CMakeLists.txt
- libs/pika/functional/tests/regressions/bind_sfinae_5488.cpp
- libs/pika/functional/tests/unit/CMakeLists.txt
- libs/pika/functional/tests/unit/stateless_test.cpp
- libs/pika/functional/tests/unit/sum_avg.cpp
- libs/pika/futures/tests/regressions/CMakeLists.txt
- libs/pika/futures/tests/regressions/set_pika_limit_798.cpp
- libs/pika/iterator_support/tests/unit/CMakeLists.txt
- libs/pika/iterator_support/tests/unit/boost_iterator_categories.cpp
- libs/pika/synchronization/tests/unit/stop_token_cb2.cpp
- testing/include/pika/testing.hpp
- testing/src/testing.cpp
- Always print a message, even if no tests failed. This makes it easier to see that the test actually ran successfully. It also prints how many tests were run.
- Print a message and fail if `report_errors` is called but no tests were actually run.
Example outputs below. Success:
```
All tests passed. Ran 0 sanity checks and 150121 tests.
```
Failure:
```
Tests failed. 0/0 sanity checks and 1/13 tests failed.
```
No tests run:
```
No tests run. Did you forget to add tests?
```
Ideas to improve these messages are warmly welcome.
Related: #367. Not removing them yet, but I think we can quite safely remove the sanity checks (since they're unused).
Made a few tests that were triggering the "No tests run" case into compile-only tests. Added a few `PIKA_TEST(true)`s to others.
> Improve `report_errors` output

- CMakeLists.txt
- cmake/pika_option.cmake
- cmake/pika_print_summary.cmake
- libs/CMakeLists.txt
- libs/pika/coroutines/CMakeLists.txt
- libs/pika/coroutines/include/pika/coroutines/detail/context_windows_fibers.hpp
- libs/pika/iterator_support/include/pika/iterator_support/boost_iterator_categories.hpp
- libs/pika/topology/CMakeLists.txt
- libs/pika/topology/src/topology.cpp
The file was being potentially written for every module, and since some of the modules added options (that get written into the `config_defines.hpp` file) the file would be rewritten every CMake reconfiguration, but the contents would stay unchanged.
> Fix `config_defines.hpp` timestamp being updated on every CMake reconfiguration

- .github/workflows/linux_coverage.yml
Part of #353. From local testing this seems to include only the "right" files, i.e. no tests or examples. Let's see what codacy says once the reports are uploaded (this will only run once on `main`).
> Keep libpika source files for coverage reports, not tests or examples

- CMakeLists.txt
- cmake/pika_option.cmake
Fixes #317.
Also makes the `PIKA_WITH_TESTS_*` and `PIKA_WITH_EXAMPLES_*` options dependent on `PIKA_WITH_TESTS` and `PIKA_WITH_EXAMPLES`, respectively. If someone spots a possibility to use dependent options elsewhere don't hesitate to just change it.
I've kept the old `pika_option` implementation for non-`BOOL` types, and added new variants based on `option` and `cmake_dependent_option`. The `pika_option` function is now a macro because of the scope required for the "hidden" (helper) variables used by `cmake_dependent_option`.
> Allow making CMake options dependent on others

- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/init_runtime/tests/unit/CMakeLists.txt
- libs/pika/init_runtime/tests/unit/finalize_non_pika_thread.cpp
> Remove restriction to call `pika::finalize` on a pika thread

- .jenkins/cscs/env-common.sh
Closes the `SPACK_USER_CACHE_PATH` of #299.
> Move `SPACK_USER_CACHE_PATH` to Jenkins' scratch directory

- cmake/pika_setup_cuda.cmake
Also, don't set `CMAKE_CUDA_STANDARD` when finding pika (`cuda_std_xx` is meant to ensure that at least a minimum standard is available). Closes #392.
> Check `PIKA_CUDA_STANDARD` and `CMAKE_CUDA_STANDARD` compatibility only when building pika itself

- libs/pika/runtime/include/pika/runtime/runtime.hpp
- libs/pika/runtime/include/pika/runtime/shutdown_function.hpp
- libs/pika/runtime/include/pika/runtime/startup_function.hpp
- libs/pika/runtime/src/runtime.cpp
- Uses `std::function` instead of pika's `unique_function` for startup/shutdown functions
- Actually calls shutdown functions at shutdown
- Doesn't clear startup/shutdown functions registered before the runtime starts so that they are registered again if the runtime is restarted
This is preliminary work and will be followed up by better tests once I understand a bit better the requirements here. I'm experimenting with `pika::register_{startup,shutdown}_function` as a way to initialize/finalize a separate polling thread for CUDA polling (see #17 and #83).
> Use `std::function` for startup/shutdown functions and run shutdown functions at shutdown

- .github/workflows/linux_coverage.yml
This seems to be inhibiting ccache to cache compilations. This workflow has in principle the same problem as in #409 (i.e. it builds all tests and examples and is prone to full rebuilds), but since the non-cached builds are already a lot faster than on macOS there's less to be gained by splitting the workflow into multiple steps.
> Disable precompiled headers on coverage workflow

- .jenkins/cscs-ault/ctest.cmake
Based on #67.
Try to enable globbing for `ctest_test` command, globbing can't be used for building targets.
> Test all `async_cuda` tests on HIP CI

- .github/bors.toml
- .github/workflows/macos_debug.yml
`ccache` was not as effective as hoped because:
- The cache not shared across branches
- The workflow builds tests and examples, which means that changes to libpika typically lead to most tests and examples anyway being rebuilt.
This reverts the changes to the macOS workflow from #354, but keeps #370.
> Re-split macOS workflow job into multiple steps

- libs/pika/algorithms/include/pika/parallel/algorithms/detail/advance_to_sentinel.hpp
Mostly a style question, but I find the while version clearer to read.
> Slightly reformulate `advance_to_sentinel` to be more obvious

- libs/pika/algorithms/tests/unit/container_algorithms/sort_range_tests.hpp
- libs/pika/algorithms/tests/unit/container_algorithms/stable_sort_range_tests.hpp
When `N` is `0` writing into the vector at index `N - 1 == -1` is out of bounds.
> Fix out-of-bounds access in `(stable_)sort_range` tests

- libs/pika/algorithms/include/pika/parallel/algorithms/nth_element.hpp
- libs/pika/algorithms/tests/unit/container_algorithms/nth_element_range.cpp
- Make sure `nth_element` has no effect when `nth == last`
- Make sure tests explicitly check for above case
- Fix assertions in `nth_element` implementation
- Fix off-by-one mistakes in the inputs to the `nth_element_range` test
The non-range test doesn' suffer from the same off-by-one errors, but I will add the same tests to it as well (separately).
> Fix `nth_element` implementation and test

- .jenkins/cscs-ault/entry.sh
3 hours is a bit unnecessarily wrong (the job should usually finish in less than 10 minutes), so I'm reducing it to 30 minutes. In addition, the job launches still seem to be occasionally failing. This will trigger another build, so let's see how it goes...
> Reduce job time on ault CI jobs

- tools/pre-commit
Fixes : just useful info for any user who wants hooks to update automatically
> Update git hooks instructions to use symlink instead of copy

- cmake/pika_add_test.cmake
- libs/pika/async_mpi/CMakeLists.txt
- libs/pika/async_mpi/include/pika/async_mpi/mpi_polling.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/CMakeLists.txt
- libs/pika/async_mpi/tests/unit/mpi_async_storage.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
- libs/pika/resource_partitioner/examples/oversubscribing_resource_partitioner.cpp
- libs/pika/resource_partitioner/examples/simple_resource_partitioner.cpp
This work is not completely finished - I can still get deadlocks with the async storage test, but I would like to start the process of merging this, so I can test it more and use dlaf as a more advanced testing framework
```
Support throttling of mpi traffic using streams
Throttling using a single counter causes deadlocks as a
receive might be blocked by a send, or vice versa.
```
+ Some flyby cmake and cleanup fixes
> Add MPI streams

- libs/pika/execution/tests/unit/executor_parameters_timer_hooks.cpp
Fixes another false positive test failure (or rather significantly reduces the chances of false positives).
> Reduce chances of false positives in `executor_parameters_timer_hooks`

- libs/pika/format/include/pika/util/from_string.hpp
I skipped this earlier, but not doing the conditional use of `(nv_)diag*` ends up with annoying warnings about deprecated pragmas.
> Use `nv_diag_suppress` when available instead of `diag_suppress`

- libs/pika/async_cuda/src/cuda_event_callback.cpp
The probability of deep recursion (and in turn stack overflows) is too high compared to the almost zero performance benefit from it.
I'm still trying to understand why it's triggered so frequently in DLA-Future, but I think it's still fair to revert this for 0.8.0.
> Don't run CUDA continuations eagerly if stream is ready

- libs/pika/threading/tests/unit/tss.cpp
Fixes the occasional failures on the `tss` unit test. `promise::set_value` may occasionally suspend, and if it does the lock verification will throw unless the `tss_mutex` in the test is ignored from verification.
> Ignore lock in tss test

- .jenkins/cscs/env-clang-13.sh
- .jenkins/cscs/env-clang-14-cuda.sh
I've updated the Piz Daint spack commit to include the `p2300` and `whip` packages. This PR doesn't actually attempt to use them, but just adds them to the environment for #436 and #423. Will do ault separately.
@aurianer note that I haven't constrained the P2300 commit in any way. If you rebase #436 and it turns out that there are now build problems, it may due to bugs in P2300 that are not there in the pinned commit in `pika_setup_p2300.cmake`. We can either try an older commit or ideally try to fix the problems, if there are any.
> Add `+p2300` variant to Piz Daint Jenkins CI configurations

- libs/pika/execution/include/pika/execution/algorithms/bulk.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/just.hpp
- libs/pika/execution/include/pika/execution/algorithms/keep_future.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/make_future.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/include/pika/execution/algorithms/start_detached.hpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/include/pika/execution/algorithms/then.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/executors/include/pika/executors/thread_pool_scheduler_bulk.hpp
The dumb approach to #433. Reduces nesting locally since the detail namespaces are anyway implementation details.
On the `thread_pool_scheduler_test` the binary size went from around 61MB to 56MB with these changes (in debug mode).
> Reduce namespace nesting in sender adaptors

- .jenkins/cscs/env-clang-14-cuda.sh
- .jenkins/cscs/slurm-constraint-clang-14-cuda.sh
- cmake/pika_setup_cuda.cmake
- libs/pika/async_cuda/include/pika/async_cuda/then_on_host.hpp
- libs/pika/async_cuda/tests/performance/CMakeLists.txt
- libs/pika/async_cuda/tests/unit/cublas_matmul.cpp
Actually fixes #302. I never actually enabled CUDA on the clang 14 configuration. I expect this to fail at the moment. I have not tried the build myself.
> Fix CMake options for clang-14-cuda Jenkins config

- .github/workflows/linux_hip.yml
`CXX` is no longer set to `hipcc` in version 3 of the CI image.
> Don't use hipcc as `CXX` in `linux_hip` GitHub actions workflow

- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/runtime/include/pika/runtime/runtime.hpp
- libs/pika/runtime/src/runtime.cpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
Fixes #406.
Adds a configuration option `pika.install_signal_handlers` which defaults to off (`0`). Only forces the signal handlers to be installed if `--pika:attach-debugger=exception`. Also adds a missing default entry for `pika.diagnostics_on_terminate`.
> Make signal handlers optional

- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
Without #289 we need to pessimistically expect that all senders that get wrapped in a `(unique_)any_sender` may signal `set_stopped_t()`. This is one more tiny step towards using the reference implementation in DLA-Future.
> Add `set_stopped_t()` to `(unique_)any_sender` completion signatures

- .jenkins/cscs/env-cce.sh
- libs/pika/async_mpi/tests/unit/algorithm_transform_mpi.cpp
Attempt to fix #418 and #164.
For #418 we'll see what slurm says about launching jobs within jobs.
For #164 the problem seems to have been that OpenMPI and MPICH simply seem to have different definitions of what they consider to be errors. OpenMPI considers `-1` as a root rank to be a problem. MPICH doesn't. They both seem to consider `MPI_DATATYPE_NULL` as a data type to be an error, however, so I've updated the error-handling tests to use that instead to trigger errors. OpenMPI and MPICH also print different error messages, so they have to be handled separately.
> Run MPI tests with MPICH on Jenkins and fix error handling tests with MPICH

- .circleci/config.yml
- .github/workflows/linux_coverage.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release_fetchcontent.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/linux_tracy.yml
- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
- libs/pika/executors/tests/unit/std_thread_scheduler.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
Fixes #294. `ensure_started` now has a default implementation in the reference implementation. Not all the `ensure_started` tests can be enabled yet, because they also use `split`, which is not yet copyable in the reference implementation.
The CI environment still need to be updated for this to work there.
> Enable tests for `ensure_started` from P2300 reference implementation

- libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
- libs/pika/execution/tests/unit/algorithm_let_value.cpp
Add reference handling test for `let_value` sender.
Fix partially #284
> Add const reference handling test for `let_value`

- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/execution/tests/unit/algorithm_when_all_vector.cpp
Last part of #284. Fixes #284.
> Add tests for reference types to `when_all_vector`

- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
A thread created with transfer is not guaranteed to have a different id from the previous thread. A thread description may be created for the new thread, but the actual thread may be reused from the previous thread. This disables a couple of tests which assumed that the new thread would have a unique id.
This has been coming up quite often after the introduction of release mode builds in CI (e.g. https://cdash.cscs.ch/test/45953708).
> Avoid false positives in `thread_pool_scheduler` test

- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/futures/include/pika/futures/detail/future_data.hpp
To the best of my knowledge these are bogus warnings. I am not 100% sure about my analysis, but I've added an explanation for my understanding of the `-Warray-bounds` warning in the `any_sender` file. The `-Wstringop-overflow` warning I do not understand.
> Silence apparently bogus warnings in `any_sender` and `future_data`

- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
Makes sure values sent to `then_with_stream` are actually stored in the operation state (and released before notifying the next receiver). This is what #162 intended to do, but it seems like I completely missed doing the one thing the title of #162 said it should do...
> Fix `then_with_stream`

- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/tests/unit/algorithm_transform_mpi.cpp
- libs/pika/execution/include/pika/execution/algorithms/when_all.hpp
- libs/pika/execution/tests/unit/algorithm_when_all.cpp
- libs/pika/tag_invoke/include/pika/functional/detail/tag_fallback_invoke.hpp
- libs/pika/tag_invoke/include/pika/functional/detail/tag_priority_invoke.hpp
- libs/pika/tag_invoke/include/pika/functional/tag_invoke.hpp
This fixes three more reference handling problems that were not included in #284:
1. `when_all` needs to `decay`/`remove_cvref` the types that it sends to successors. Previously it would directly use the value types of predecessors for its own value types. Since it needs to store the values internally before sending them onward to successors (my move) it needs to decay the types.
2. `then_with_stream` and `transform_mpi` did not decay value types before storing them internally.
This adds tests for the above cases as well. This must go into 0.10.0.
> More reference type handling fixes to `when_all`, `then_with_stream`, and `transform_mpi`

- CMakeLists.txt
- cmake/pika_setup_allocator.cmake
> Make mimalloc the default allocator

- libs/pika/algorithms/tests/performance/foreach_scaling_helpers.hpp
- libs/pika/resource_partitioner/tests/unit/cross_pool_injection.cpp
- libs/pika/resource_partitioner/tests/unit/scheduler_priority_check.cpp
- libs/pika/runtime/include/pika/runtime/runtime_fwd.hpp
- libs/pika/runtime/src/runtime.cpp
- libs/pika/thread_manager/include/pika/modules/thread_manager.hpp
- libs/pika/threading_base/include/pika/threading_base/scheduler_base.hpp
- libs/pika/threading_base/src/scheduler_base.cpp
- tests/performance/local/future_overhead.cpp
- tests/performance/local/future_overhead_report.cpp
Fixes #455.
The main difference of the combined call compared to two separate calls is that there will be two atomic updates. However, I don't think these are in any way meant to be used in performance critical parts and there are other factors that make relying on this being atomic not a very good assumption (`add_remove_scheduler_mode` was not really atomic either).
> Remove `add_remove_scheduler_mode`

- .circleci/config.yml
- libs/pika/execution_base/include/pika/execution_base/p2300_forward.hpp
On top of #487 because it updates the CI image. #487 should go in first.
Fixes #490.
The only relevant change is https://github.com/pika-org/pika/commit/c72367920a33d7ce9015df0cde1535b5cc8a0045.
> Update deprecated `std::execution` namespace to `stdexec`

- README.rst
While lower versions than 5.2.0 may work, in practice we require an as up-to-date version as possible.
> Update minimum HIP version in README.rst

- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
Minor debugging help to catch cases where the request is accidentally unused in the callback.
> Check that `MPI_Request` was used in user callback in `transform_mpi`

- libs/pika/execution_base/tests/unit/CMakeLists.txt
- libs/pika/memory/tests/unit/CMakeLists.txt
It's not necessary (and potentially wrong) since they link to the `pika` target anyway.
> Don't do special linking for some unit tests

- .github/bors.toml
- .github/workflows/macos_arm64_debug.yml
- .github/workflows/macos_debug.yml
I suspect there was a reason for not using ccache on macOS, but I'm hoping I'm misremembering, so retrying.
> Attempt to use ccache on macOS CI workflows

- libs/pika/logging/src/format/formatter/thread_id.cpp
To work around problem in #540.
> Don't use `pthread_self`/`GetCurrentThreadId` where not needed in logging module

- .github/bors.toml
- .github/workflows/macos_debug.yml
Same fix as in https://github.com/pika-org/pika-algorithms/pull/12.
> Add workaround for failing brew upgrade on macOS CI workflow

- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
> Add `bool` conversion operator and `empty` member function to `(unique_)any_sender`

- libs/pika/executors/include/pika/executors/thread_pool_scheduler_bulk.hpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
Porting fix from https://github.com/STEllAR-GROUP/hpx/pull/6125.
> Make `thread_pool_scheduler` bulk sender be correctly l-value connectable

- libs/pika/synchronization/include/pika/synchronization/async_rw_mutex.hpp
- libs/pika/synchronization/tests/unit/async_rw_mutex.cpp
Changes a few essential and less essential things in `async_rw_mutex` for use in DLA-Future.
- The most important fix is in https://github.com/pika-org/pika/commit/ead0444d4ec1f41f40b2474e67436bb1e09d8ca7. It fixes deadlocks which happen if one tries to do a read-only access after a read-write access, and the read-only access is eagerly waited for with e.g. `sync_wait` in the same scope as the `async_rw_mutex` itself. This was caused by the `async_rw_mutex` holding on to shared states too long. I'm not 100% happy with the current fix (especially the `yield_while`), but it will do for now.
- This also makes read-only access senders connectable with l-value references.
- Removes the conversion operators from the wrapper types. They're gone because they cause problems when used in DLA-Future …
> `async_rw_mutex` enhancements

- .github/bors.toml
The Jenkins ault agent is currently down and blocking other PRs from merging.
> Disable Jenkins HIP configuration in bors configuration

- cmake/pika_setup_whip.cmake
Since whip `main` already had 0.1.0 as the version I think this will keep working in CI without changes.
> Require whip 0.1.0

- libs/pika/config/include/pika/config/compiler_fence.hpp
Fixes: https://github.com/pika-org/pika/issues/577
Existing one-size-fits-all PPC code breaks the build on Darwin. PR fixes it.
Also, ppc64 case should be accommodated.
> compiler_fence: fix PPC assembler for Darwin, unbreak the build

- cmake/pika_add_config_test.cmake
Attempts to fix #576.
The regular atomics test already had a fallback to use `libatomic`, but because the `REQUIRED` flag was set the default test fails immediately and never lets the fallback test run. This adds another flag `NOT_REQUIRED` which overrides `REQUIRED` and is used in the default atomics tests (the fallback test still uses plain `REQUIRED` if requested by the caller).
> Update atomics feature test to correctly use fallback test with libatomic

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
- libs/pika/execution_base/include/pika/execution_base/sender.hpp
A lot of sender adaptors use a `struct done_type {}` in variants to mark that `set_stopped` has been called. This:
- renames them to `struct stopped_type {}`, and
- moves them out of the sender definitions into a single, common definition (nesting them inside the senders increases debug bloat)
I've also renamed the helper visitors `done_error_value_visitor` to `stopped_error_value_visitor` to match the `done` to `stopped` change.
> Move nested `done_type` helper structs into common definition

- .github/bors.toml
- .jenkins/cscs-ault/env-hipcc.sh
- libs/pika/async_cuda/tests/unit/CMakeLists.txt
- libs/pika/async_cuda/tests/unit/cuda_sender.cu
Also removes gfx900, as all Vega10 have been removed from ault.
Fixes #384.
> Change gfx906 arch to xnack- to avoid conflict in rocblas

- libs/pika/async_cuda/include/pika/async_cuda/then_on_host.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/execution/include/pika/execution/algorithms/bulk.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/just.hpp
- libs/pika/execution/include/pika/execution/algorithms/keep_future.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/include/pika/execution/algorithms/then.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
- libs/pika/executors/include/pika/executors/thread_pool_scheduler.hpp
This makes no practical difference, but may prevent accidental moves from the reference in the future.
> Add `const` to l-value reference connect overloads

- libs/pika/async_cuda/tests/unit/cuda_sender.cu
The `cuda_sched_copy` variable was unused, `cuda_sched` was used instead. This simply uses the copy instead of the original scheduler. This shouldn't fix any bug or change the behaviour, but at least uses the variable.
> Minor fix in `cuda_sender` test

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/keep_future.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
This is an attempt to improve diagnostics when senders that should be moved aren't being moved in the right places. This PR adds static asserts that always fail in the l-value case with a hopefully useful error message to help understand what's gone wrong. With these changes GCC prints this:
```
/home/mjs/src/pika/libs/pika/execution/tests/unit/algorithm_split_tuple.cpp:170:51:   required from here
/home/mjs/src/pika/libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp:530:44: error: static assertion failed: Are you missing a std::move? The split_tuple sender is not copyable and thus not l-value connectable. Make sure you are passing an r-value reference of the sender.
530 |             static_assert(sizeof(Receiver) == 0,
|                           ~~~~~~~~~~~~~~~~~^~~~ …
```
> Add static asserts for senders that are not l-value connectable

- libs/pika/init_runtime/src/init_runtime.cpp
Part of #573. Initializes HIP early to avoid problems with concurrent initialization. CUDA does not seem to suffer from problems with concurrent initialization, so this is restricted to HIP only.
> Initialize HIP early to avoid concurrent initialization

- libs/pika/async_base/include/pika/async_base/scheduling_properties.hpp
- libs/pika/execution/include/pika/execution/algorithms/bulk.hpp
- libs/pika/execution/include/pika/execution/algorithms/transfer.hpp
- libs/pika/execution/include/pika/execution/scheduler_queries.hpp
- libs/pika/execution/tests/include/algorithm_test_utils.hpp
- libs/pika/execution_base/include/pika/execution_base/completion_scheduler.hpp
- libs/pika/execution_base/include/pika/execution_base/operation_state.hpp
- libs/pika/execution_base/include/pika/execution_base/receiver.hpp
- libs/pika/execution_base/include/pika/execution_base/sender.hpp
- libs/pika/executors/include/pika/executors/execution_policy_annotation.hpp
- libs/pika/properties/include/pika/properties/property.hpp
- libs/pika/properties/tests/unit/properties.cpp
- libs/pika/tag_invoke/include/pika/functional/detail/tag_fallback_invoke.hpp
- libs/pika/tag_invoke/include/pika/functional/detail/tag_priority_invoke.hpp
- libs/pika/tag_invoke/include/pika/functional/tag_invoke.hpp
- libs/pika/tag_invoke/tests/unit/tag_invoke.cpp
Part of #16 
Originally attempt to move tag_invoke in the detail namespace. It has been reverted because of potential namespace clash when defining tag_invoke overloads.
> Clean up `tag_invoke` module

- libs/pika/program_options/tests/unit/options_description.cpp
@biddisco this seems to be another failure case for the string-rejoining script to take into account.
> Readd blank strings to `options_description` test after string-rejoining script removed them

- libs/pika/debugging/include/pika/debugging/print.hpp
- libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp
- libs/pika/threading_base/src/print.cpp
A small fix to the scheduler where a wrong param is set, plus some debug cleanup that is needed for other cuda/mpi polling branches
> Clean up macros and fix bug in `shared_priority_queue_scheduler`

- libs/pika/affinity/include/pika/affinity/affinity_data.hpp
- libs/pika/resource_partitioner/src/detail_partitioner.cpp
This makes the error message more verbose when the default thread pool doesn't have any threads assigned to it.
In addition to saying "check your bindings/options" this will now also print the number of threads that pika is trying to use and the number of thread pools that it's configured to use. It will also print the process mask that pika has detected (if it's configured to use one). It will also print the value of `OMP_PROC_BIND` (if set). Finally, it prints two possible reasons for this happening. I hope this is an improvement, but I think there is still lots of room for improvement.
@rmeli, @albestro, @rasolca wishes and comments would be very much appreciated, even ones that may be a bit more difficult to implement. We may get to them some other day and it's good to know what …
> Add more verbose message when default thread pool doesn't have any threads assigned to it

- libs/pika/async_cuda/include/pika/async_cuda/cuda_polling_helper.hpp
- libs/pika/async_cuda/include/pika/async_cuda/detail/cuda_debug.hpp
- libs/pika/async_cuda/src/cuda_event_callback.cpp
Redesign the way polling for cuda events is handled
Cuda events are polled (by any thread on the pool on which polling is enabled) and passed to a lockfree queue when ready. The polling loop first checks ready events and invokes callbacks, and only then takes the lock and checks outstanding events which are placed on the ready queue. 
This means that as soon as events are ready, any thread can invoke the callback - a single polling thread can find N events are ready and place them in the ready queue and N other threads can start handling the completions - instead of only allowing the polling thread to handle them.
The locking and completion handling has been reworked significantly and gives much better results.
> Improve CUDA polling

- .circleci/config.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_hip.yml
- .github/workflows/linux_release_fetchcontent.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/linux_tracy.yml
- .github/workflows/macos_arm64_debug.yml
- .github/workflows/macos_debug.yml
I'm testing if this could replace bors. I'm not removing the bors branches or app yet, and we can quickly turn this off in the settings if it doesn't work as well as bors, but in theory it works exactly the same (except for the a missing `bors try` equivalent).
> Add GitHub merge queue branches to CI configurations

- libs/pika/executors/tests/unit/standalone_thread_pool_executor.cpp
- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/resource_partitioner/examples/guided_pool_test.cpp
- libs/pika/resource_partitioner/examples/oversubscribing_resource_partitioner.cpp
- libs/pika/resource_partitioner/examples/simple_resource_partitioner.cpp
- libs/pika/schedulers/docs/index.rst
- libs/pika/schedulers/include/pika/schedulers/deadlock_detection.hpp
- libs/pika/schedulers/include/pika/schedulers/local_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/local_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/lockfree_queue_backends.hpp
- libs/pika/schedulers/include/pika/schedulers/maintain_queue_wait_times.hpp
- libs/pika/schedulers/include/pika/schedulers/queue_holder_numa.hpp
- libs/pika/schedulers/include/pika/schedulers/queue_holder_thread.hpp
- libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/static_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/static_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/thread_queue.hpp
- libs/pika/schedulers/include/pika/schedulers/thread_queue_mc.hpp
- libs/pika/schedulers/src/maintain_queue_wait_times.cpp
- libs/pika/schedulers/tests/unit/schedule_last.cpp
- libs/pika/thread_manager/src/thread_manager.cpp
- libs/pika/thread_pools/src/scheduled_thread_pool.cpp
> Clean up schedulers module

- libs/pika/command_line_handling/include/pika/command_line_handling/parse_command_line.hpp
- libs/pika/command_line_handling/src/late_command_line_handling.cpp
- libs/pika/command_line_handling/src/parse_command_line.cpp
- libs/pika/ini/include/pika/ini/ini.hpp
- libs/pika/ini/src/ini.cpp
- libs/pika/init_runtime/include/pika/init_runtime/detail/init_logging.hpp
- libs/pika/init_runtime/src/init_logging.cpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/detail/create_partitioner.hpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/detail/partitioner.hpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/partitioner.hpp
- libs/pika/resource_partitioner/src/detail_partitioner.cpp
- libs/pika/resource_partitioner/src/partitioner.cpp
- libs/pika/runtime/src/runtime.cpp
- libs/pika/runtime_configuration/include/pika/runtime_configuration/init_ini_data.hpp
- libs/pika/runtime_configuration/include/pika/runtime_configuration/runtime_configuration.hpp
- libs/pika/runtime_configuration/src/init_ini_data.cpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
Part of #16.
Also move section member functions into cpp file.
> Move `ini` module functionality into detail namespace

- README.rst
- libs/pika/async_cuda/src/cuda_event_callback.cpp
- libs/pika/debugging/include/pika/debugging/print.hpp
- libs/pika/debugging/src/print.cpp
- libs/pika/debugging/tests/unit/print.cpp
- libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp
- Rename macros to be prefixed by `PIKA_DETAIL`
- Remove unnecessary casts in debug print macro calls
- Add note about meaning of detail to README
> Miscellaneous cleanup of debug print macros

- libs/pika/init_runtime/include/pika/init_runtime/detail/init_logging.hpp
- libs/pika/init_runtime/include/pika/init_runtime/init_runtime.hpp
- libs/pika/init_runtime/src/init_logging.cpp
- libs/pika/init_runtime/src/init_runtime.cpp
Part of #16.
Move functionality into `detail` namespace, move functions into cpp files.
> Clean up `init_runtime` module

- libs/pika/async_cuda/tests/performance/synchronize.cu
> Reuse empty lambda in synchronize test to reduce template instantiations

- .jenkins/cscs-ault/batch.sh
This means using depth-first search, which avoids having `find` try to access directories that have just been deleted. This also removes the redirection of errors to `/dev/null` since that shouldn't be needed anymore.
> Use `find`'s `-depth` option when finding directories to delete in CI

- README.rst
- libs/pika/include/CMakeLists.txt
- libs/pika/include/include/pika/async_rw_mutex.hpp
- libs/pika/synchronization/include/pika/synchronization/async_rw_mutex.hpp
- libs/pika/synchronization/tests/unit/async_rw_mutex.cpp
Fixes #646.
- Adds the header `pika/async_rw_mutex.hpp`
- Moves the `async_rw_mutex_access_type` enum out of the `detail` namespace
- Moves the `async_rw_mutex_access_wrapper` out of the `detail` namespace
> Make `async_rw_mutex` part of public API

- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/runtime_configuration/include/pika/runtime_configuration/runtime_configuration.hpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
- libs/pika/schedulers/include/pika/schedulers/deadlock_detection.hpp
- libs/pika/schedulers/include/pika/schedulers/local_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/local_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/queue_helpers.hpp
- libs/pika/schedulers/include/pika/schedulers/static_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/thread_queue.hpp
- libs/pika/schedulers/src/deadlock_detection.cpp
- libs/pika/threading_base/include/pika/threading_base/thread_data.hpp
- libs/pika/threading_base/src/thread_data.cpp
Rename the checks from `PIKA_HAVE_THREAD_MINIMAL_DEADLOCK_DETECTION` to `PIKA_HAVE_THREAD_DEADLOCK_DETECTION`.
Fixes #635.
> Fix checks for `PIKA_HAVE_THREAD_DEADLOCK_DETECTION`

- libs/pika/coroutines/include/pika/coroutines/detail/context_generic_context.hpp
This should fix problems seen on Apple M1/M2 systems.
> Make posix utility guards consistent in Boost coroutines implementation

- libs/pika/resource_partitioner/examples/guided_pool_test.cpp
- libs/pika/resource_partitioner/tests/unit/scheduler_priority_check.cpp
- libs/pika/schedulers/tests/unit/schedule_last.cpp
- libs/pika/thread_pools/include/pika/thread_pools/scheduling_loop.hpp
- libs/pika/threading_base/include/pika/threading_base/scheduler_mode.hpp
Fifth of N PRs to try to improve performance in DLA-Future. This is one of the changes in https://github.com/pika-org/pika/compare/main...disable-cruft-scheduler where we see up to 25% improvement in DLA-Future miniapps. This branch needs to be benchmarked to see if it makes a difference on its own.
One change that have in the `disable-cruft-scheduler` branch is to unconditionally enable stealing always. It may be worth checking if that makes a difference, though I suspect the effect may be small.
> Remove `fast_idle` and `delay_exit` scheduler modes and related scheduling loop checks

- libs/pika/threading_base/include/pika/threading_base/scheduler_mode.hpp
Second of N PRs to try to improve performance in DLA-Future. This is one of the changes in https://github.com/pika-org/pika/compare/main...disable-cruft-scheduler where we see up to 25% improvement in DLA-Future miniapps. This branch needs to be benchmarked to see if it makes a difference on its own.
https://github.com/pika-org/pika/tree/disable-idle-backoff-default-compile-time needs to be benchmarked together with this branch to ensure that its enough to disable idle backoff at runtime instead of compile time.
> Disable scheduler idle backoff by default at runtime

- libs/pika/thread_pools/include/pika/thread_pools/scheduling_loop.hpp
Below is an example of the performance bump seen in DLA-Future. Most algorithms don't have such a clear performance improvement, but this change also doesn't hurt the other algorithms. The dark blue line corresponds to the changes in this PR. The other lines contain other scheduler-related changes that don't seem to make a difference in DLA-Future. One of the other lines is pika main.
> Always steal tasks if scheduler mode allows for it

- libs/pika/thread_pools/include/pika/thread_pools/scheduling_loop.hpp
Reverts #670. It seems it introduced a performance regression, at least in the future overhead benchmark. It did show a small performance improvement in DLA-Future, so I'm guessing the effect of the change is very much workload dependent. We might instead have to consider tweaking the threshold when we enable stealing.
> Revert "Always steal tasks if scheduler mode allows for it" #670

- libs/pika/synchronization/include/pika/synchronization/async_rw_mutex.hpp
- libs/pika/synchronization/tests/unit/async_rw_mutex.cpp
Eagerly reset the shared state held by the operation state to allow continuations to run as early as possible. This fixes a deadlock that occurred in the added test case.
> Eagerly reset shared state in `async_rw_mutex`

- libs/pika/synchronization/src/detail/condition_variable.cpp
- libs/pika/threading_base/src/set_thread_state.cpp
This fixes deadlocks that started appearing after #672 which disabled yielding for `spinlock`.
(One of) the deadlock(s) was the following scenario:
| thread 1 | thread 2 |
|-|-|
| wait_until | |
| take lock | |
| add self to cv queue | | 
| release lock | |
| timed suspend | |
| | notify_all |
| | take lock |
| timed resume | attempt to set thread 1 to pending |
| attempt to take lock | fail because thread 1 is active |
| spin trying to take lock | spin waiting for thread 1 to not be active |
| deadlock | deadlock |
This PR changes `notify_all` to not hold the lock while resuming threads that need to be woken up. I see no reason to keep the lock for that time since there is anyway a delay between setting a thread to `pending` and the thread actually being run by a worker thread, with the …
> Fix deadlocks in `condition_variable`

- .jenkins/cscs/env-gcc-cuda-12.sh
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/tests/unit/cublas_handle.cu
- libs/pika/debugging/tests/unit/print.cpp
- libs/pika/execution/tests/unit/algorithm_bulk.cpp
- libs/pika/execution/tests/unit/algorithm_sync_wait.cpp
- libs/pika/execution/tests/unit/executor_parameters_dispatching.cpp
- libs/pika/executors/tests/unit/limiting_executor.cpp
- libs/pika/executors/tests/unit/std_thread_scheduler.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
- libs/pika/lcos/tests/unit/dataflow.cpp
- libs/pika/lcos/tests/unit/dataflow_executor.cpp
- libs/pika/lcos/tests/unit/dataflow_executor_additional_arguments.cpp
- libs/pika/lcos/tests/unit/dataflow_small_vector.cpp
- libs/pika/lcos/tests/unit/dataflow_std_array.cpp
- libs/pika/pack_traversal/tests/unit/unwrap.cpp
- libs/pika/program_options/tests/unit/options_exception.cpp
- libs/pika/resource_partitioner/tests/unit/scheduler_binding_check.cpp
- libs/pika/synchronization/tests/regressions/ignore_while_locked_1485.cpp
- libs/pika/synchronization/tests/unit/barrier.cpp
- libs/pika/synchronization/tests/unit/event.cpp
- libs/pika/synchronization/tests/unit/sliding_semaphore.cpp
- libs/pika/threading/tests/unit/error_callback.cpp
Fixes compilation by explicitly casting the enums to `int`s for printing, since they are no longer implicitly converted for printing by fmt 10.
Also adds fmt 10 to the CUDA 12 CI configuration.
Fixes #686.
> Allow compilation with fmt 10 with CUDA/HIP

- libs/pika/lock_registration/src/register_locks.cpp
- libs/pika/resource_partitioner/tests/unit/cross_pool_injection.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_pool.cpp
- libs/pika/synchronization/tests/performance/channel_mpmc_throughput.cpp
- libs/pika/synchronization/tests/performance/channel_mpsc_throughput.cpp
- libs/pika/synchronization/tests/performance/channel_spsc_throughput.cpp
- libs/pika/synchronization/tests/unit/async_rw_mutex.cpp
Also adds the option to one CI configuration.
> Fix `PIKA_WITH_VERIFY_LOCKS_BACKTRACE=ON` build

- .jenkins/cscs/env-clang-13.sh
- .jenkins/cscs/env-clang-14-cuda.sh
- .jenkins/cscs/env-gcc-13.sh
- .jenkins/cscs/env-nvhpc.sh
- libs/pika/async_cuda/include/pika/async_cuda/cuda_scheduler.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_on_host.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
- libs/pika/execution/include/pika/execution/algorithms/bulk.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/tests/include/algorithm_test_utils.hpp
- libs/pika/execution/tests/unit/algorithm_transfer.cpp
- libs/pika/executors/include/pika/executors/std_thread_scheduler.hpp
- libs/pika/executors/include/pika/executors/thread_pool_scheduler.hpp
- libs/pika/executors/include/pika/executors/thread_pool_scheduler_bulk.hpp
Fixes #683. Also makes all `get_env_t` overloads `noexcept` as that is required by the latest `stdexec` versions.
> Enable stdexec in GCC 13 CI configuration

- libs/pika/coroutines/src/thread_enums.cpp
- libs/pika/threading_base/src/reset_backtrace.cpp
- libs/pika/threading_base/src/reset_lco_description.cpp
Fix a couple of warnings/errors that appeared when unity build was disabled.
> Fix warnings about includes and `#pragma once`

- libs/pika/execution/include/pika/execution/algorithms/transfer.hpp
`transfer.hpp` needs to include `schedule_from.hpp` from since it uses it.
> Add missing include to `transfer.hpp`

- libs/pika/runtime/src/runtime_handlers.cpp
When an assertion is handled we optionally allow attaching a debugger before terminating. Currently on `main` the debugger can be attached before printing the error message. This PR moves `may_attach_debugger` to after the error message has been printed so that one can see the reason for failure before deciding to attach a debugger.
> Attach debugger after printing failure information

- libs/pika/runtime/src/runtime.cpp
- libs/pika/topology/src/topology.cpp
1. This slightly simplifies `handle_print_bind` by moving the printing of empty process masks into `topology`. When a mask is empty, the thread pool is also printed now to be consistent with the output when there is a mask. The output looks like this:
```
*******************************************************************************
rank: 0
0: thread binding disabled, on pool "default"
1: thread binding disabled, on pool "default"
2: thread binding disabled, on pool "default"
3: thread binding disabled, on pool "default"
```
2. Fixes the consistency check with hwloc. When binding is disabled, the check would previously fail because hwloc reported a full mask and pika an empty mask. Since the two are equivalent we let this pass by first transforming any empty masks to full masks before …
> Improve check for consistent process masks

- .circleci/config.yml
- .github/workflows/linux_coverage.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_hip.yml
- .github/workflows/linux_leaksanitizer.yml
- .github/workflows/linux_release_fetchcontent.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/linux_tracy.yml
- libs/pika/coroutines/include/pika/coroutines/detail/context_linux_x86.hpp
- libs/pika/coroutines/include/pika/coroutines/detail/context_posix.hpp
When stack overflow detection is enabled an alternate stack is allocated (where the signal handler can run; since if a stack overflow happens the regular stack can't be used anymore). However, that alternate stack was never freed.
This would lead to particularly bad memory leaks if pika is repeatedly restarted multiple times in the same process since we pre-allocate a number of stacks at startup. If they're never freed when shutting down we'll keep leaking memory and keep allocating more alternate stacks every time pika is started.
LeakSanitizer caught this so I'm adding a CI workflow with LeakSanitizer enabled. I only tested this on `hello_world`, but I'm tentatively running all examples in CI now. If there are a lot of other leaks I may reduce the test to only `hello_world` for now. I'm …
> Fix memory leak with stack overflow detection enabled

- libs/pika/coroutines/include/pika/coroutines/detail/posix_utility.hpp
When guard pages are disabled, we were still allocating an extra page as if we were using guard pages but then deallocating as if we're not using guard pages. This lead to memory leaks.
Fixes #715.
> Fix freeing stack when guard pages are disabled

- libs/pika/async_mpi/CMakeLists.txt
- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_helpers.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_polling.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/CMakeLists.txt
- libs/pika/async_mpi/tests/unit/mpi_async_storage.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
- libs/pika/coroutines/src/thread_enums.cpp
- libs/pika/debugging/src/print.cpp
- libs/pika/string_util/include/pika/string_util/case_conv.hpp
- libs/pika/threading_base/include/pika/threading_base/thread_data.hpp
Fixes #187 and partially addresses #557
This PR reworks extensively the mpi_polling, the most important feature is that continuations are not triggered under lock, and that they can be explicitly transferred to a new task/pool.
Throttling is possible on a per stream basis, initially disabled until dlaf testing requires it. 
The number of completions to handle per poll iteration may be controlled.
env vars that control behaviour are
`PIKA_MPI_COMPLETION_MODE` sets the mode to use for handling completions 
`PIKA_MPI_POLLING_SIZE` sets the number of completions to handle per poll iteration
`PIKA_MPI_MSG_THROTTLE` sets the number of messages (per stream) to allow in-flight (disabled by default)
> Improve MPI polling

- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
Adds `reset()` and `reset(Sender)` members to `{unique_,}any_sender` to reset the sender to the empty state or to reset it with a new sender.
> Allow explicitly resetting `{unique_,}any_sender`

- libs/pika/execution/CMakeLists.txt
- libs/pika/execution/include/pika/execution/algorithms/unpack.hpp
- libs/pika/execution/tests/unit/CMakeLists.txt
- libs/pika/execution/tests/unit/algorithm_unpack.cpp
Fixes #717.
This supports anything that `std::apply`/`std::get` supports, i.e. not only `tuple`s. Currently it supports sending only exactly one tuple-like type from the predecessor per variant (i.e. there can be more than one variant, but only one tuple-like per variant). The predecessor also can't send nothing, although in principle that would be straightforward to support by also sending nothing from this adaptor. I'm going to leave that as a potential future enhancement if there's a good use for it.
Feedback on the naming and/or supported use cases welcome.
> Add `execution::unpack` to unpack tuple-like types sent by predecessors

- README.rst
I didn't update the readme as part of https://github.com/pika-org/pika/pull/501.
> Fix mention of default allocator in README.rst

- .editorconfig
Some editors will pick this up for e.g. wrapping comments.
> Add `max_line_length` option to `.editorconfig`

- CMakeLists.txt
This only affects the _default_. The allocator can still be changed as before.
> Make mimalloc the default allocator on all systems

- .circleci/config.yml
Fixes the warning `W: --force-yes is deprecated, use one of the options starting with --allow instead.`
> Fix apt warning in arm64 CircleCI

- libs/pika/affinity/src/affinity_data.cpp
- libs/pika/affinity/src/parse_affinity_options.cpp
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/resource_partitioner/src/detail_partitioner.cpp
- libs/pika/runtime/src/runtime.cpp
- libs/pika/schedulers/include/pika/schedulers/local_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/local_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp
- libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool_impl.hpp
- libs/pika/threading_base/src/thread_pool_base.cpp
- libs/pika/topology/include/pika/topology/topology.hpp
- libs/pika/topology/src/topology.cpp
Part of #568. This is part one that helps work around problems when using pika together with OpenMP. This makes `topology` store the current CPU mask on construction that can then be retrieved using `get_cpubind_mask_main_thread`. This also makes sure that the `topology` object is constructed early in a global constructor so that the mask is actually read on the main thread.
This change helps if OpenMP sets the binding of the main thread when it first encounters a parallel region. LLVM OpenMP seems to behave this way. However, GNU OpenMP actually sets the binding in a global constructor (https://github.com/gcc-mirror/gcc/blob/7879f589af911ea6a910d08919014b0b2df1b4b1/libgomp/env.c#L2409), and since it's called in a shared library we can't directly influence when that happens I will open a …
> Read CPU mask of main thread early to avoid reading it after it's been reset by other libraries

- .circleci/config.yml
Uses the small class for things like configure and spellchecking to avoid wasting resources there, use the large class for building and running tests (we don't have access to larger than large on the free plan). inshpect uses the large class as well since it can run in parallel.
> Use more appropriate resource classes for jobs on CircleCI

- libs/pika/command_line_handling/include/pika/command_line_handling/command_line_handling.hpp
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/command_line_handling/src/parse_command_line.cpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
- libs/pika/topology/include/pika/topology/cpu_mask.hpp
- libs/pika/topology/include/pika/topology/topology.hpp
- libs/pika/topology/src/topology.cpp
- libs/pika/topology/tests/unit/CMakeLists.txt
- libs/pika/topology/tests/unit/from_string_cpu_mask.cpp
And corresponding `pika.override_process_mask` configuration option.
Part of #568.
This includes #738. #738 should be merged first.
This allows overriding the process mask detected by pika at startup, for the cases where we are not able to read the mask before e.g. OpenMP binds the main thread to a single core. The option accepts masks in hexadecimal form. The mask itself can be bigger than the number of cores available on the system, but I've now made it stop with an error if there are set bits outside of the number of available cores. E.g. on a 4-core system a mask of `0x0000f` is allowed, but `0x1000f` is not. Related, leading zeros are counted towards the size of the mask, but the internal check in `topology` normalizes it to the number of available cores (with a check).
I currently …
> Add `--pika:process-mask` command line option

- .jenkins/cscs/env-gcc-9.sh
- CMakeLists.txt
- README.rst
- cmake/pika_setup_boost.cmake
- libs/pika/config/include/pika/config/threads_stack.hpp
- libs/pika/coroutines/include/pika/coroutines/detail/context_impl.hpp
- libs/pika/coroutines/src/detail/context_posix.cpp
- libs/pika/coroutines/src/swapcontext.cpp
C.f. https://github.com/pika-org/pika/pull/723.
What do you think? Should we keep the old name? Is the new name better?
_If_ we change this option I would update the spack package to have a new variant `boost_context` which is enforced to be exactly the same as `generic_coroutines` so that one can still use the old variant.
> Rename `PIKA_WITH_GENERIC_CONTEXT_COROUTINES` to `PIKA_WITH_BOOST_CONTEXT`

- .github/bors.toml
- .github/workflows/docs.yml
- README.rst
- docs/_static/pika.css
- docs/api.rst
- docs/conf.py
- docs/index.rst
- docs/usage.rst
- shell.nix
This adds v0.0.1-gamma (i.e. the most very basic) of a documentation page using sphinx.
It more or less contains the contents of the current `README.rst` with a little added section about pika's relation to stdexec/std::execution.
This is deployed using a couple of GitHub actions that use deployments (https://github.com/pika-org/pika/deployments) which as far as I can tell keeps it away from the git history and environments (https://github.com/pika-org/pika/settings/environments) for branch protections.
In this PR I will still:
I will not:
- Add an API reference outside of the public headers
- Add examples
- Add other technical content (like explanations of how the CUDA/HIP/MPI integrations work, or how the thread pool works)
~The logo... leaves room for improvement. We may be better off …
> Add documentation with deployment to GitHub pages

- .jenkins/cscs-ault/env-hipcc.sh
I think the HIP jobs have been failing quite frequently because of OOM. This attempts to avoid that by only building with 16 jobs in the HIP configuration.
> Use fewer build jobs in Jenkins HIP configuration to avoid OOM

- libs/pika/schedulers/include/pika/schedulers/queue_helpers.hpp
- libs/pika/threading_base/include/pika/threading_base/thread_data.hpp
- libs/pika/threading_base/src/thread_data.cpp
> Remove `get_component_id` and `get_self_component_id` from `thread_data`

- libs/pika/init_runtime/include/pika/init_runtime/init_runtime.hpp
- libs/pika/init_runtime/src/init_runtime.cpp
This is equivalent to the `nullptr_t` overload that already exists.
We could arguably remove the `pika::init(nullptr_t, ...)` overload (since it's blocking, and providing no entry point is a bit weird), but I'm leaving it unchanged in light of #754.
> Add `pika::start` overload which takes no function

- docs/usage.rst
Fix wrong markup used in #763.
> Fix code markup in documentation

- CMakeLists.txt
- libs/pika/init_runtime/src/init_runtime.cpp
The signal handlers are already disabled by default at runtime and there's no good reason to hide this behind a compile-time option.
> Remove `PIKA_WITH_DISABLED_SIGNAL_EXCEPTION_HANDLERS` CMake option

- libs/pika/async_mpi/src/mpi_polling.cpp
Fix a hang introduced by the global activity count when using MPI polling
> Fix a missing global activity count

- .circleci/config.yml
It was added as a potential fix for the `std_thread_scheduler` test failing, but the test definitely still fails so I suspect the option isn't the source of the failures.
> Remove `GLIBC_TUNABLES` for `std_thread_scheduler` test fom CircleCI configuration

- docs/usage.rst
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/topology/src/topology.cpp
Fixes #743. However, this only special cases the handling for `PIKA_PROCESS_MASK` and doesn't fix the behaviour for any other configuration options. The proper fix would require doing #745. This also adds an additional check for empty process masks when set through `PIKA_PROCESS_MASK` or `--pika:process-mask` to give a better error message when the mask is empty.
> Add workaround to ensure `PIKA_PROCESS_MASK` is respected

- CMakeLists.txt
- libs/pika/coroutines/include/pika/coroutines/detail/posix_utility.hpp
This option can be controlled sufficiently at runtime.
> Remove `PIKA_WITH_THREAD_GUARD_PAGE` CMake option

- .jenkins/cscs/env-clang-14-cuda.sh
- .jenkins/cscs/env-gcc-cuda-12.sh
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all.hpp
The default implementation of `PIKA_FORWARD` doesn't actually use the type argument (the first argument), but instead uses `decltype` for the cast. This means that the first argument may actually be wrong and the compiler won't notice because it's unused. This means that if `PIKA_WITH_CXX_LAMBDA_CAPTURE_DECLTYPE` is off things will fail to compile because then the type argument is actually used. I think we introduced the fallback `PIKA_FORWARD` implementation mainly for MSVC but it doesn't hurt to check that it still works, so I've turned `PIKA_WITH_CXX_LAMBDA_CAPTURE_DECLTYPE` off in a few CI configurations.
It also turns out that nvcc fails to compile anything but the `PIKA_FORWARD` implementation with `decltype` in some situations, so I've hardcoded the choice in those cases.
> Fix a few instances of the wrong type being forwarded with `PIKA_FORWARD`

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
`nvcc` was mis-detecting the types used with the `PIKA_FORWARD` expression which made compilation fail since the receiver is not copyable (`PIKA_FORWARD` was resulting in a `const&` of the receiver). `PIKA_MOVE` fixes compilation, and fits the rest of the code better as well, since we know that the receiver is never a reference in that context.
> Fix `move`/`forward` mismatch in `ensure_started` and fix compilation with `nvcc` at the same time

- shell.nix
`pkgconfig` was for a long time an alias to `pkg-config`. Now the `pkgconfig` alias has been removed on unstable nixpkgs.
> Change `pkgconfig` to `pkg-config` in shell.nix

- .github/workflows/linux_valgrind.yml
- CMakeLists.txt
- cmake/pika_add_test.cmake
- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/tests/unit/CMakeLists.txt
- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
This makes sure that when resetting the continuation called by the `ensure_started` shared state it is not done on a potentially already freed shared state. This is circumvented by moving the continuation to a local variable before calling the continuation (similar to what is done in `split`). This adds a test that triggers the problem under valgrind. I've also added a small valgrind workflow to run some tests from the execution module under valgrind. This reproduces the error in CI before fixing the problem (https://github.com/pika-org/pika/actions/runs/6391142577/job/17345809634#step:8:98, https://gist.github.com/msimberg/c12961f11eba8ebed14a99a1815ae8fa).
> Fix use-after-free in `ensure_started`

- libs/pika/execution/tests/unit/algorithm_ensure_started.cpp
Assertions inside the latch can fire from reading variables that have gone out of scope after both uses of the latch have been arrived at. These are harmless for the test, but ensuring that the latch lives long enough in both threads means we avoid false positives in the test.
> Fix lifetime issue with latch in `ensure_started` test

- .github/workflows/linux_valgrind.yml
- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/executors/tests/unit/CMakeLists.txt
If the `ensure_started` sender is not connected (i.e. there are no continuations) the `ensure_started_receiver` holds the last reference to the shared state. This will be released when releasing the operation state until the `ensure_started` operation state, since the `ensure_started_receiver` will be released with the operation state. This happens because the `ensure_started_receiver` is taken by rvalue reference in `set_*`. This PR changes them to take the receiver by value, ensuring that the reference count stays non-zero also after the operation state has explicitly been reset.
This is another way to fix #795 but I'm keeping that change as it doesn't hurt. Importantly, this fixes a distinct bug that is reported by valgrind in the `std_thread_scheduler` test (the test that calls …
> Fix one more lifetime bug in `ensure_started` for cases when the sender is dropped without connecting it

- tools/roll_release.sh
When using a `GITHUB_TOKEN` with the wrong permissions, the tag is created but the release is not pushed. This allows to rerun the script to push the release even if the tag already exists.
> Check if release tag already exists before tagging

- libs/pika/runtime/CMakeLists.txt
- libs/pika/runtime/src/runtime.cpp
Until now we've been printing the locality in `--pika:print-bind` but it's always zero. This changes it to print the MPI rank (if pika was compiled with MPI support).
> Print MPI rank in place of locality in `--pika:print-bind`

- libs/pika/command_line_handling/src/command_line_handling.cpp
Process masks are not supported on macOS, so print a warning message about it.
> Print warning message if `--pika:process-mask` is used on macOS

- .github/workflows/linter.yml
Don't trigger linter on all pushes, and include merge queue branches.
> Update branch filters for yaml linter workflow

- .github/workflows/macos_debug.yml
The macOS test runner sometimes gets allocated three threads and sometimes four. Our tests expect to know the right number, so this sets the maximum number dynamically.
> Set maximum number of threads for macOS CI tests dynamically

- .circleci/config.yml
- .github/workflows/linux_leaksanitizer.yml
- .github/workflows/macos_debug.yml
- libs/pika/runtime/tests/unit/CMakeLists.txt
- libs/pika/runtime/tests/unit/process_mask_flag.cpp
- libs/pika/topology/src/topology.cpp
Process masks come in two flavours: using physical/OS indices and logical indices. The latter is what hwloc prefers to use for most operations, while the former is what the operating system reports (and what `taskset`, `hwloc-bind --get --taskset`, and slurm masks use). In pika we deal with logical masks. When reading the mask from the process, we already convert the mask from physical to logical indices. When I did https://github.com/pika-org/pika/pull/739 I didn't take this into account and simply used the mask passed to `--pika:process-mask` directly as if it contained logical indices. This adds the conversion from physical to logical indices before the explicit mask is stored.
The physical/OS/logical terminology is what's used in the hwloc manual. It contains more information about …
> Fix handling of explicitly specified process masks

- libs/pika/execution_base/tests/include/pika/execution_base/tests/algorithm_test_utils.hpp
Add `using is_receiver = void` and `using is_sender = void`.
> Opt-in senders and receivers used for tests to newer stdexec sender and receiver concepts

- .circleci/config.yml
A long time ago I enabled debug logs for tests on CircleCI in HPX. It was useful at the time, but hasn't been very useful for a long time since then. When failures happen, the logs are several GB large. Additionally, at the time tests were run one at a time which was good since the test logs were all appended into one file. Since then we've enabled parallel testing which means that logs from multiple tests get mixed. There are also signs that writing the logs may be leading to some test failures, but I'm not 100% sure about this. Finally, disabling logs will make the tests simply run faster.
If we find a need for this feature in the future the CMake option is staying and we can consider updating it to write test-specific log files or similar to make it useful. However, for the moment …
> Disable debug logs on CircleCI

- libs/pika/runtime/src/custom_exception_info.cpp
This is a follow-up to https://github.com/pika-org/pika/pull/805. Print the MPI rank (similarly to #805) instead of locality (which was always 0) when printing exception information.
> Print MPI rank if available instead of locality in exception information

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
Specify explicitly that r-value reference is not enough, a non-const r-value reference is required.
> Update error message when connect requires a movable sender

- .gitlab/docker/Dockerfile.spack_build
- .gitlab/includes/dockerhub_pipeline.yml
- .gitlab/includes/gcc11_pipeline.yml
Based on #814 
Fixes #829
- `ctest` now returns an error in case no tests are run.
- Removes `--verbose` option from `ctest` as `--output-on-failure` is sufficient.
- Make `-L` more exhaustive.
> Trigger error in CI pipeline if no tests run + small changes of ctest options

- CMakeLists.txt
- docs/usage.rst
- scripts/pika-bind.sh.in
- Add `pika-bind` helper script
`pika-bind` sets the `PIKA_PROCESS_MASK` environment variable based on process mask information found before the `pika` runtime is started.
`pika-bind` has been implemented by @msimberg. The differences between this PR and the [original implementation](https://gist.github.com/msimberg/15ffdc5f2d071afa6b853acbd24bac2e) are the following (related to #828):
```diff
11,12c11
< # TODO?
< version_message="pika-bind from pika version 0.19.0"
---
> version_message="pika-bind from pika version @PIKA_VERSION@"
22c21
<   pika-bind [-h|--help] [--version] [-v|--verbose] [-a|--allow-no-bind] [(-m|--method) (all|slurm|hwloc|taskset)] -- <command>"
---
>   pika-bind [-h|--help] [--version] [-v|--verbose] [-a|--allow-no-bind] [(-m|--method) (all|slurm|hwloc|taskset)] …
```
> Add pika-bind helper script

- .gitlab/includes/gcc11_pipeline.yml
`-R tests` is unecessary because all tests contain `tests` already, and `--exclude-regex tests.unit.build` is unnecessary because the build unit tests are only build targets, not tests (https://github.com/pika-org/pika/pull/830#issuecomment-1784777396).
@aurianer this would be useful to include in the other configurations in #835.
> Remove unnecessary ctest command line arguments from GCC 11 pipeline config

- .github/workflows/linux_coverage.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_hip.yml
- .github/workflows/linux_leaksanitizer.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/linux_tracy.yml
- .github/workflows/linux_valgrind.yml
Like the macOS runners, the Linux runners apparently also now can have different hardware configurations, and may have more than two threads as we've so far assumed. C.f. https://github.com/pika-org/pika/pull/810.
> Set maximum number of threads for GitHub actions Linux tests dynamically

- .github/workflows/linux_coverage.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_hip.yml
- .github/workflows/linux_leaksanitizer.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/linux_tracy.yml
- .github/workflows/linux_valgrind.yml
C.f. #842. Use processing units, not cores, as the maximum number of threads in tests because they are what `hardware_concurrency` report, and the actual maximum pika supports ignoring real oversubscription.
> Set maximum number of threads for GitHub actions Linux tests dynamically, take two

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/tests/regressions/CMakeLists.txt
- libs/pika/execution/tests/unit/CMakeLists.txt
Enables valgrind testing for all of the `execution` module. Description of the bug in https://github.com/pika-org/pika/commit/3291a045f9644591e97e2fe9d0c50f6f59fab5a6. The bug is very timing dependent and I can't think of a way to reproduce it with a unit test. However, for the record, here is a reproducer that triggers the problem easily: https://github.com/msimberg/pika/tree/split-continuation-clear-valgrind-reproducer. It relies on adding sleeps inside the implementation.
With these changes I've also cleaned up both `split` and `ensure_started`'s handling of clearing continuations, since in both cases the receiver holds a reference to the shared state now.
> Fix more lifetime bugs in `split`

- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
> Reuse `any_sender` storage when moving to a `unique_any_sender`

- .github/workflows/linux_valgrind.yml
- libs/pika/threading/tests/unit/CMakeLists.txt
- libs/pika/threading_base/tests/regressions/CMakeLists.txt
- libs/pika/threading_base/tests/unit/CMakeLists.txt
- libs/pika/topology/tests/unit/CMakeLists.txt
No issues reported locally, so simply enabling testing in CI.
> Opt-in `threading`, `threading_base`, and `topology` modules to valgrind testing

- .github/workflows/linux_valgrind.yml
- libs/pika/functional/tests/regressions/CMakeLists.txt
- libs/pika/functional/tests/unit/CMakeLists.txt
I have 2 errors locally for both `test_empty_ref()` and `test_exception()` in the unit test `functional_test`
> Enable valgrind testing for `functional` module

- .gitlab/includes/common_spack_pipeline.yml
I committed this when I added the rm on the tarball (with the spack commit unchanged), but this doesn't need to be here, we only need this step to run when the `SPACK_COMMIT` is changing now
> Remove `CSCS_REBUILD_POLICY` always

- .gitlab/docker/Dockerfile.spack_compiler
- .gitlab/includes/clang11_pipeline.yml
- .gitlab/includes/clang12_pipeline.yml
- .gitlab/includes/clang13_pipeline.yml
- .gitlab/includes/clang15_pipeline.yml
- .gitlab/includes/clang16_pipeline.yml
- .gitlab/pipeline.yml
> Add clang configurations for CSCS CI

- libs/pika/async_cuda/src/cuda_pool.cpp
Create number of streams based on `get_num_worker_threads` if the runtime is up, otherwise fall back to `hardware_concurrency`. This is intended to work around issues with HIP event creation being significantly slower if many streams are created. E.g. on an AMD EPYC system with 128 hardware threads (`hardware_concurrency == 128`) the `cuda_pool` would create `(3 + 3) * hardware_concurrency = 768` streams per rank, even if the runtime is only started with e.g. 8 threads (8 ranks per node, without hyperthreading). If the actual number of runtime threads is used, the number of threads created is instead 48. This can significantly improve performance if many kernels are submitted.
The `cuda_pool` still falls back to using `hardware_concurrency` if it's created before the pika runtime is …
> Don't create more streams than required in `cuda_pool`

- .gitlab/docker/Dockerfile.spack_build
In case the compiler image is already up-to-date on jfrog, this image is used and the spec is not printed, I find it handy to have it printed in the pika build step too
> Print spack spec in CSCS CI pika building step

- .gitlab/includes/clang11_pipeline.yml
- .gitlab/includes/clang12_pipeline.yml
- .gitlab/includes/clang13_pipeline.yml
- .gitlab/includes/clang15_pipeline.yml
- .gitlab/includes/clang16_pipeline.yml
- .gitlab/includes/gcc11_pipeline.yml
- .gitlab/includes/gcc12_pipeline.yml
- .gitlab/includes/gcc13_pipeline.yml
- .gitlab/includes/gcc9_pipeline.yml
As pointed by @msimberg the timeout in the binary semaphore tests might be due to oversubscription, this PR is an attemps to fix that
> Reduce test parallelism in CI to `$(nproc)/2`

- .gitlab/includes/common_pipeline.yml
As I have several draft PR open in parallel that would be nice to have this on main so that they can all use it
`test_common_gpu` was not used yet so it doesn't have an impact
> Update gpu machines common pipeline CSCS CI

- libs/pika/execution/CMakeLists.txt
- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
- libs/pika/execution/tests/unit/CMakeLists.txt
- libs/pika/execution/tests/unit/algorithm_require_started.cpp
- libs/pika/execution/tests/unit/algorithm_require_started_terminate.cpp
Fixes #790.
Comments on the name are especially welcome. I found `require_started` quite descriptive as it signals that the user is required to make sure that the sender is started. It also mirrors `ensure_started` which actually connects and starts a sender.
The `require_started` sender has an empty state to make it somewhat sensible to detect unstarted senders. E.g. `just()` is copyable, but it's also possible to connect it after moving it. This is not allowed by the `require_started` sender. The `require_started` sender stores the wrapped sender internally in an `optional`, and when moving a `require_started` sender the `optional` is emptied.
A `require_started` sender can be allowed to not be started, but it has to be explicitly asked for with `discard`.
When a `require_started` …
> Add `require_started` sender adaptor

- .gitlab/includes/gcc12_cuda12_pipeline.yml
- .gitlab/pipeline.yml
> Add GCC 12 CUDA 12 build pipeline in CSCS CI

- .gitlab/includes/clang11_pipeline.yml
- .gitlab/includes/clang12_pipeline.yml
- .gitlab/includes/clang13_pipeline.yml
- .gitlab/includes/clang14_cuda11_pipeline.yml
- .gitlab/includes/clang15_pipeline.yml
- .gitlab/includes/clang16_pipeline.yml
- .gitlab/includes/gcc11_pipeline.yml
- .gitlab/includes/gcc12_cuda12_pipeline.yml
- .gitlab/includes/gcc12_pipeline.yml
- .gitlab/includes/gcc13_pipeline.yml
- .gitlab/includes/gcc9_cuda11_pipeline.yml
- .gitlab/includes/gcc9_pipeline.yml
See https://gitlab.com/cscs-ci/ci-testing/containerised_ci_doc/-/blob/main/image_cleanup.md for documentation. `/base` images are kept longer, and cleaned up only after other images are cleaned up.
> Put CSCS CI base images into `/base` namespace to avoid cleanup

- .jenkins/cscs-perftests/launch_perftests.sh
- testing/performance_testing/include/pika/testing/performance.hpp
- testing/performance_testing/src/performance.cpp
- tests/performance/local/task_overhead_report.cpp
Separates some test cleanup that was originally part of #891.
- Remove the `--test-all` command line option from `task_overhead_report_test` since there is only one test, and it wasn't previously run by default (it is now always run)
- Remove the test-specific `executor` field from the performance test json output to allow generalization to other types of tests
> Task overhead cleanup

- tests/performance/local/CMakeLists.txt
- tests/performance/local/task_size.cpp
From the comment in the test:
> This test finds the smallest grain/task size that yields a parallel efficiency at least as large as the target efficiency. The timing is always compared to an ideal single-threaded execution, i.e. the number of tasks multiplied by the grain size. The search starts from the minimum grain size. The grain size is then grown geometrically until the efficiency of the parallel execution of the given number of tasks is above the target efficiency.
>
> This test is useful for finding an appropriate minimum task size for a system, i.e. one that gives resonable parallel efficiency.
I'm adding this for potential use in #891. The grain size is a useful compressed way of expressing how well pika performs on a system (or how well a system performs with pika). The smaller …
> Add `task_size` performance test

- .gitlab/includes/clang14_cuda11_pipeline.yml
- .gitlab/includes/common_spack_pipeline.yml
Includes https://github.com/spack/spack/pull/41578.
> Update spack commit to use patched version of fmt 10 for clang CUDA CSCS CI configuration

- .gitlab/includes/clang11_pipeline.yml
- .gitlab/includes/clang12_pipeline.yml
- .gitlab/includes/clang13_pipeline.yml
- .gitlab/includes/clang14_cuda11_pipeline.yml
- .gitlab/includes/clang15_pipeline.yml
- .gitlab/includes/clang16_pipeline.yml
- .gitlab/includes/common_spack_pipeline.yml
- .gitlab/includes/gcc11_pipeline.yml
- .gitlab/includes/gcc12_cuda12_pipeline.yml
- .gitlab/includes/gcc12_pipeline.yml
- .gitlab/includes/gcc13_pipeline.yml
- .gitlab/includes/gcc9_cuda11_pipeline.yml
- .gitlab/includes/gcc9_pipeline.yml
Uses the hash of the Dockerfile and all input arguments to Dockerfile as the tag to determine if an image needs rebuilding. Split out from #891.
> Ensure CSCS CI images are rebuilt if Dockerfile or input arguments change

- .gitlab/docker/Dockerfile.spack_base
- .gitlab/docker/Dockerfile.spack_build_performance
- .gitlab/includes/performance_gcc13_pipeline.yml
- .gitlab/pipeline.yml
- .gitlab/scripts/run_performance_benchmarks.sh
Pushes performance benchmark data to elastic (via logstash). The json blob that is sent is structured as follows:
```
{
"build_configuration": {
"ARCH": "linux-ubuntu22.04-broadwell",
"BUILD_TYPE": "Release",
"CMAKE_COMMON_FLAGS": "-GNinja -DPIKA_WITH_COMPILER_WARNINGS=ON -DPIKA_WITH_COMPILER_WARNINGS_AS_ERRORS=ON -DPIKA_WITH_CHECK_MODULE_DEPENDENCIES=ON -DPIKA_WITH_EXAMPLES=ON -DPIKA_WITH_TESTS=ON -DPIKA_WITH_PARALLEL_TESTS_BIND_NONE=ON",
"CMAKE_FLAGS": "",
"COMPILER": "gcc@13.1.0",
"SPACK_COMMIT": "27c0dab5ca1944d686894f17e2a05bc7ddac3061",
"SPACK_SPEC": "pika@main arch=linux-ubuntu22.04-broadwell %gcc@13.1.0 malloc=mimalloc cxxstd=20 ^boost@1.83.0 ^hwloc@2.9.1"
},
"ci": {
"CI_COMMIT_AUTHOR": "Mikael Simberg <mikael.simberg@iki.fi>",
"CI_COMMIT_BRANCH": "__CSCSCI__pr891", …
```
> Push performance benchmark data to elastic database

- .gitlab/includes/clang14_cuda11_pipeline.yml
With Jenkins this configuration was using Cray's clang. In the new CSCS CI setup this is no longer the case, and the test seems to be working with vanilla clang.
> Reenable build unit tests on clang 14/CUDA 11 CI configuration

- libs/pika/threading_base/tests/regressions/thread_stacksize_current.cpp
> Ensure disabled schedulers aren't used in `thread_stacksize_current` test when 128bit atomics are unavailable

- tools/perftests_ci/requirements.txt
The warning is not gone after requesting fonttools 3.43, I'm trying to set a minimum for matplotlib. The matplotlib version in the perftests environment is already satisfying the version requirement.
> Update matplotlib version

- libs/pika/runtime/tests/unit/CMakeLists.txt
The important aspect of the output is that the first two threads use physical PU numbers 0 and 1, the other indices can vary by machine.
> Relax regex used to check `process_mask_flag` test output

- libs/pika/concurrency/include/pika/concurrency/concurrentqueue.hpp
- libs/pika/schedulers/include/pika/schedulers/queue_holder_thread.hpp
This improves the performance of the scheduler on systems where lockfree 128-bit atomics are not available or can't be generated. GCC 12 and older on e.g. Nvidia Grace CPUs seems to still produce lockful 128-bit atomics.
> Use moodycamel queue also for terminated tasks in `shared_priority_queue_scheduler`

- libs/pika/config/include/pika/config/compiler_fence.hpp
- `isb` gives significantly better performance in spinloops because it reduces contention (by pausing for longer)
- The guards for ARM were updated to include 64-bit architectures
This gives significantly better performance on the `task_size` test with a barrier in #921.
> Use better pause for ARM in spinloops

- .gitlab/scripts/run_performance_benchmarks.sh
- libs/pika/executors/include/pika/executors/thread_pool_scheduler_bulk.hpp
- tests/performance/local/task_size.cpp
Adds two new methods (description in the code) and pushes results to elastic. The motivation for the new methods is to stress different parts of the runtime:
- The existing "task" test generally tests the schedulers
- The "barrier" test tests how well the barrier scales
- The "bulk" test tests how well latch and general scheduling works
> Add more task spawning methods to `task_size` performance test

- libs/pika/execution_base/src/this_thread.cpp
- libs/pika/threading_base/src/execution_agent.cpp
- In `yield_k`, pause every iteration before actually yielding
- In `spin_k`, add a simple backoff by spinning inside `spin_k` `k` times before returning
Especially the latter improves performance of contended barriers on Grace.
> Improve `spin_k` and `yield_k` performance by pausing more

- tests/performance/local/task_size.cpp
This can be used as an alternative metric to see how well the runtime is doing.
I've also added a `_s` suffix consistently to all the time fields in the csv output.
> Add estimated task overhead to `task_size` performance test output

- .gitlab/includes/common_pipeline.yml
- .gitlab/includes/hip_pipeline.yml
- .gitlab/pipeline.yml
Fixes partially #32.
Got [clang segfaulting](https://gist.github.com/aurianer/06d056088b7119a72fb36b0c64f2b593) when building dependencies with hip@5.3.3 so I now switched to hip@5.5
https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/479009878135925/5304355110917878/-/jobs/5651543294
> Add HIP configuration for CSCS CI

- .github/workflows/linux_valgrind.yml
- libs/pika/resource_partitioner/examples/CMakeLists.txt
- libs/pika/resource_partitioner/tests/regressions/CMakeLists.txt
- libs/pika/resource_partitioner/tests/unit/CMakeLists.txt
- libs/pika/schedulers/include/pika/schedulers/queue_holder_thread.hpp
@biddisco note the change in `queue_holder_thread.hpp`. This comes from a warning from valgrind about mismatching sizes between new/delete:
```
==817002== Thread 4:
==817002== Mismatched new/delete size value: 80
==817002==    at 0x4846702: operator delete(void*, unsigned long) (in /nix/store/drfy02sf3aqzk6cdrs4lyxa8a6jprl5q-valgrind-3.22.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==817002==    by 0x4C00733: std::__new_allocator<pika::threads::detail::thread_data>::deallocate(pika::threads::detail::thread_data*, unsigned long) (new_allocator.h:168)
==817002==    by 0x4BF7750: pika::threads::detail::queue_holder_thread<pika::threads::detail::thread_queue_mc>::deallocate(pika::threads::detail::thread_data*) (queue_holder_thread.hpp:515)
==817002==    by 0x4BE740C: …
```
> Enable valgrind testing in `resource_partitioner` module

- libs/pika/init_runtime/tests/unit/const_args_init.cpp
`std::vector` does nothing to add a null-terminator (and doesn't guarantee that the allocation will even have space for a null-terminator). 
I'm changing it to a regular `std::string` because since C++11 it is guaranteed to be null-terminated (https://en.cppreference.com/w/cpp/string/basic_string/data):
> The returned array is null-terminated, that is, data() and [c_str()](https://en.cppreference.com/w/cpp/string/basic_string/c_str) perform the same function.
> 
> If [empty()](https://en.cppreference.com/w/cpp/string/basic_string/empty) returns true, the pointer points to a single null character.
I'm using `basic_string::data` instead of `basic_string::c_str` because the latter is const, and we want a non-const array in the test.
This should also fix the failure seen in #878.
> Ensure test string is null-terminated in `const_args_init` test

- .github/workflows/linux_valgrind.yml
Since valgrind internally serializes execution of threads, we can run multiple tests concurrently.
> Run valgrind tests in parallel in CI

- libs/pika/synchronization/tests/unit/async_rw_mutex.cpp
The test can take near 300 seconds to run in release mode with valgrind. This reduces the number of iterations to something a bit more reasonable.
> Use fewer iterations in `async_rw_mutex` test with valgrind

- libs/pika/errors/include/pika/errors/exception_info.hpp
Fixes #868 in a very basic way. This trickles up to e.g. `report_exception_and_*` to report `std::exception::what()` instead of `<unknown>`. Non-`std::exception`s are still reported as `<unknown>`. This does not specialize for different types of `std::*_error`s and reports them all as `std::exception`.
The message will now be e.g.:
```
The pika runtime caught the following exception in the entry point (typically pika_main). The exception may be rethrown later by pika::init or pika::stop. The pika runtime will wait for all tasks to finish, but may be deadlocked because of the exception.
std::exception:
what():  hello
terminate called after throwing an instance of 'std::runtime_error'
what():  hello
```
where the first time is when `pika_main` catches the exception, and the second is when …
> Add fallback to `invoke_with_exception_info` to report `what()` from `std::exception`

- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/execution/tests/unit/algorithm_when_all_vector.cpp
If the call to the last child operation state of `when_all_vector` actually releases the `when_all_vector` operation state, the access to the number of predecessors from the `when_all_vector` operation state will be on freed memory. This PR reads the number into a stack-local variable before starting the child operation states and introduces a test that triggers the failure without the fix.
> Fix potential use-after-free in `when_all_vector`

- .gitlab/docker/Dockerfile.spack_compiler
- .gitlab/includes/gcc10_apex_pipeline.yml
- .gitlab/pipeline.yml
Fix #926. Allow deprecated packages (for apex 2.4.1), otherwise concretization is failing (see https://github.com/spack/spack/issues/42037). apex version will be updated separately, see #948.
> Add gcc10 apex pipeline in CSCS CI

- .circleci/config.yml
- .github/workflows/linux_leaksanitizer.yml
- .github/workflows/macos_debug.yml
- libs/pika/runtime/tests/unit/CMakeLists.txt
After #922 was merged, the test should now run pretty much in any CI environment. However, this was not quite the case. This PR further slightly relaxes the regex to not care about the socket and numa node indices. For macOS it introduces a completely separate regex which expects no bindings, because thread binding is not supported on macOS.
> Reenable `process_mask_flag` test everywhere in CI

- libs/pika/concurrency/src/barrier.cpp
- libs/pika/execution_base/src/this_thread.cpp
- libs/pika/runtime/src/runtime.cpp
- libs/pika/synchronization/include/pika/synchronization/shared_mutex.hpp
- libs/pika/synchronization/tests/regressions/ignore_while_locked_1485.cpp
- libs/pika/synchronization/tests/unit/shared_mutex/shared_mutex1.cpp
- libs/pika/synchronization/tests/unit/shared_mutex/shared_mutex2.cpp
This is mostly a question of style, but it gets rid of annoying warnings that have to be suppressed with `NOLINTNEXTLINE`, and is generally a bit more compact than the manual while-loop.
> Prefer using predicated `condition_variable::wait`

- libs/pika/execution_base/src/this_thread.cpp
Similarly to #976, this expands the lock to cover the call to `condition_variable::sync_wait`.
> Expand locking in `default_agent` when notifying to avoid suspend returning too soon

- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
This fixes a bug that has been there since the beginning of pika in `sync_wait`. More details are in the commit message, but briefly the notifying thread (one that has received one of the `set_*` channels) can end up releasing the lock after the `sync_wait` operation state (including the mutex that is unlocked) is released. This was an overeager optimization that I thought was a good idea at the time, in an attempt to avoid taking the lock sometimes.
An example of the data race (between the destructor of the the operation state and the unlocking of the mutex, a write) reported by thread sanitizer:
```
WARNING: ThreadSanitizer: data race (pid=2582947)
Write of size 8 at 0x7b24000049b0 by main thread:
#0 operator delete(void*, unsigned long) <null> (libtsan.so.2+0x880ce)
#1 …
```
> Fix waiting in `sync_wait`

- .jenkins/cscs/Jenkinsfile
Now that we have pretty extensive, and well-working, coverage of CI configurations on CSCS's CI system it makes little sense to keep configurations in both Jenkins and CSCS CI. This is an attempt at disabling the debug configurations in Jenkins, except for CCE and NVHPC, which are not (yet) covered by the CSCS CI setup.
Based on https://www.jenkins.io/blog/2019/11/22/welcome-to-the-matrix/.
> Disable Jenkins configurations covered by CSCS CI

- libs/pika/threading_base/include/pika/threading_base/thread_pool_base.hpp
Storing it by reference is a huge footgun as it requires the user to make sure the name stays alive long enough. This changes the member to a regular value to avoid surprises. The member doesn't need to be a reference for performance or other reasons. The `standalone_thread_pool_scheduler` test did not keep the name alive long enough (it was passed as a prvalue).
> Store thread pool name by value instead of reference in `thread_pool_init_parameters`

- libs/pika/threading_base/include/pika/threading_base/thread_data.hpp
- libs/pika/threading_base/src/thread_data.cpp
Full description in the commit message. The variable can be read and written without synchronization, leading to data races. This is reported by thread sanitizer e.g. as (stacktraces abbreviated):
```
==================
WARNING: ThreadSanitizer: data race (pid=3562)
Read of size 8 at 0x7b44000116f0 by thread T2:
#0 pika::threads::detail::thread_data::get_last_worker_thread_num() const /__w/pika/pika/libs/pika/threading_base/include/pika/threading_base/thread_data.hpp:430:74 (libpikad.so.0+0x6b11cd) (BuildId: 1ac0dcbdeb864e0b)
#1 pika::threads::detail::execution_agent::do_resume(char const*, pika::threads::detail::thread_restart_state) /__w/pika/pika/libs/pika/threading_base/src/execution_agent.cpp:187:69 (libpikad.so.0+0x79f590) (BuildId: 1ac0dcbdeb864e0b)
#2 …
```
> Store `last_worker_thread_num` of `thread_data` as atomic variable

- libs/pika/debugging/src/print.cpp
Move debugging helper `print_info` from a global to function-local static. This avoids a dependence on static initialization order with current_thread_print_helper global. Reported by address sanitizer (with the `strict_init_order=1` option) as:
```
=================================================================
==2690384==ERROR: AddressSanitizer: initialization-order-fiasco on address 0x7f7542609ec0 at pc 0x55ca03e14355 bp 0x7ffd495b1790 sp 0x7ffd
495b0f50
READ of size 16 at 0x7f7542609ec0 thread T0
#0 0x55ca03e14354 in __asan_memcpy (/home/mjs/src/pika/build/nix-clang/bin/runtime_initialized_test+0x11e354)
#1 0x7f7541407aaf in std::enable_if<__and_<std::__not_<std::__is_tuple_like<std::_Any_data>>, std::is_move_constructible<std::_Any_dat
a>, …
```
> Fix initialization order issue with `print_info`

- .circleci/config.yml
- .devcontainer/devcontainer.json
- .github/workflows/linux_coverage.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_hip.yml
- .github/workflows/linux_leaksanitizer.yml
- .github/workflows/linux_release_fetchcontent.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/linux_tracy.yml
- .github/workflows/linux_valgrind.yml
- .gitlab/includes/dockerhub_pipeline.yml
Bump base to 21, HIP to 14. Importantly includes the version bump of `libpam` from https://github.com/pika-org/pika-ci-image/pull/41.
> Bump CI image tags

- .github/workflows/linux_asan_ubsan_lsan.yml
- .github/workflows/linux_tsan.yml
- libs/pika/config/include/pika/config/compiler_specific.hpp
- libs/pika/functional/include/pika/functional/bind.hpp
- libs/pika/schedulers/include/pika/schedulers/local_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/local_queue_scheduler.hpp
- tests/performance/local/task_overhead_report.cpp
- tools/asan.supp
- tools/tsan.supp
- tools/ubsan.supp
Adds two new CI pipelines with sanitizers:
- One with address (and leak, implicitly) and undefined behaviour sanitizers
- One with thread sanitizer
The existing sanitizer CI configurations are unchanged.
The address sanitizer setup seems to pass for all tests, with some suppressions. `detect_stack_use_after_return` seems problematic so it's currently disabled (#992). Additionally, the `task_overhead_report` seems to trigger very high memory usage with address sanitizer. `detect_stack_use_after_return` may be triggering similar problems in other tests. A potential use-after-scope has been suppressed for now in `bind` (#993).
For thread sanitizer I've suppressed data races coming from various lockfree queues (#990), the MPSC queue (#989). I've also disabled stealing of pending threads on …
> Add address, undefined behaviour, and thread sanitizer CI configurations

- libs/pika/async_cuda/include/pika/async_cuda/then_on_host.hpp
- libs/pika/execution/include/pika/execution/algorithms/then.hpp
- libs/pika/execution/tests/unit/algorithm_then.cpp
The result of the callable in `then` (and `cuda::then_on_host`) was previously taken by universal reference (`auto&&`) but then moved into the successor receiver. This would be wrong when the return type of the callable is a reference, and fail to compile if the successor receiver also expects a reference. This moves the call of the callable to simply directly pass the result into `set_value` instead of going via an intermediate local variable. This also adds a regression test for `then`.
> Fix forwarding of return type from `execution::then` callable

- libs/pika/synchronization/src/detail/condition_variable.cpp
#689 was a bit too eager in relaxing locks in `condition_variable`. Thread sanitizer reported a race between `wait` checking if the `agent_ref` had already been reset by notify, and `notify_all` resetting the `agent_ref`. The latter was happening without a lock (after #689). This PR slightly rearranges `notify_all` (and hopefully simplifies it as well). The lock is now held while working on the queue and the individual entries, but released when resuming a thread.
This is reported as the following race by thread sanitizer:
```
WARNING: ThreadSanitizer: data race (pid=3967134)
Read of size 8 at 0x7f5d7ac9ab68 by thread T4:
#0 pika::execution::detail::agent_ref::operator bool() const /home/mjs/src/pika/libs/pika/execution_base/include/pika/execution_base/agent_ref.hpp:40 …
```
> Change notification of waiting threads in `condition_variable`

- .gitlab/docker/Dockerfile.spack_base
Attempt to fix the missing Python.h include (example https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/479009878135925/5304355110917878/-/jobs/6027637946)
Applying fix suggested in: https://github.com/spack/spack/issues/42315#issue-2102133765
> Add `python-dev` to base CI image

- .gitlab/docker/Dockerfile.spack_dependencies
The concretization is now printed by default by spack on the install step. This removes the print of the concretization as it is now printed twice (https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/479009878135925/5304355110917878/-/jobs/6061783815#L51).
> Removing the concretization step since already in install step

- .gitlab/docker/Dockerfile.spack_build
- examples/jacobi_smp/jacobi_nonuniform_omp.hpp
Spack disables `-Werror` flags by default. This makes some sense for building dependencies in pika, but is not so good for CI. This enables `-Werror` flags again for the build stage of pika itself, but not while building pika dependencies.
> Keep `-Werror` flags in CSCS CI builds of pika

- .github/workflows/linux_valgrind.yml
- libs/pika/thread_manager/src/thread_manager.cpp
- libs/pika/thread_manager/tests/unit/CMakeLists.txt
- libs/pika/thread_manager/tests/unit/thread_num.cpp
The (thread-pool-)local thread number was being set as the global thread number. When using only one thread pool this has no impact since the local and global numbers are the same. When using multiple pools (e.g. an MPI pool) the global thread number will be wrong on all but one pool. This is especially problematic if using the global thread number to index into data structures, like in #872.
This adds a test that checks that the pool and the local/global thread numbers are correct one every pool, when creating one pool for each PU.
This also changes the callbacks in the thread manager to use more explicit lambdas instead of `bind` with placeholders. This is where the wrong number was being passed to `init_tss`.
> Fix setting of global thread number

- libs/pika/resource_partitioner/tests/unit/CMakeLists.txt
Silences the following error reported by address sanitizer, by simply disabling lock registration in the `cross_pool_injection` test. I couldn't convince address sanitizer to ignore the error with the suppression file/ignorelist.
This may be a real error, but it's not at all clear what the issue would be in that case. The error is triggered inside standard library headers.
```
5: Starting suspending 20
=================================================================
==4462==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fac09ebd8e0 at pc 0x7fac180ca6ff bp 0x7fac09ebd890 sp 0x7fac09ebd888
WRITE of size 8 at 0x7fac09ebd8e0 thread T28
#0 0x7fac180ca6fe in std::_Rb_tree_iterator<std::pair<void const* const, pika::util::detail::lock_data>> std::_Rb_tree<void const*, …
```
> Silence potential false positive address sanitizer error in `cross_pool_injection` test

- .gitlab/docker/Dockerfile.spack_build
- .gitlab/includes/clang11_pipeline.yml
- .gitlab/includes/clang12_pipeline.yml
- .gitlab/includes/clang13_pipeline.yml
- .gitlab/includes/clang14_cuda11_pipeline.yml
- .gitlab/includes/clang15_pipeline.yml
- .gitlab/includes/clang16_pipeline.yml
- .gitlab/includes/clang17_pipeline.yml
- .gitlab/includes/common_spack_pipeline.yml
- .gitlab/includes/gcc10_apex_pipeline.yml
- .gitlab/includes/gcc11_pipeline.yml
- .gitlab/includes/gcc12_cuda12_pipeline.yml
- .gitlab/includes/gcc12_hip5_pipeline.yml
- .gitlab/includes/gcc12_pipeline.yml
- .gitlab/includes/gcc13_pipeline.yml
- .gitlab/includes/gcc9_cuda11_pipeline.yml
- .gitlab/includes/gcc9_pipeline.yml
- .gitlab/includes/performance_gcc13_pipeline.yml
- Use the matrix functionality to run both Debug and Release builds for each configuration.
- We are using 2 different jobs for the test stage (one release and one debug). 
The `image:` field of a gitlab CI job doesn't allow customization with a variable (build type for example). Since it's evaluated before running the script of the same job, a scripting logic to change the image name is not possible either. That's why we currently have 2 jobs for the test step (one for the release mode, the other for the debug mode)
> Run debug and release builds for each CSCS CI configuration

- .jenkins/cscs/Jenkinsfile
Disable more jenkins configurations since they are now covered by CSCS CI. I'm leaving cce and nvhpc still since the nvhpc PR pipeline is not yet merged.
> Disable more Jenkins configurations in CI

- CMakeLists.txt
- cmake/pika_add_config_test.cmake
- cmake/pika_perform_cxx_feature_tests.cmake
- cmake/pika_setup_cuda.cmake
- cmake/tests/cxx23_static_call_operator.cpp
- cmake/tests/cxx23_static_call_operator.cu
- cmake/tests/cxx23_static_call_operator.hip
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/config/CMakeLists.txt
- libs/pika/config/include/pika/config.hpp
- libs/pika/config/include/pika/config/static_call_operator.hpp
- libs/pika/coroutines/include/pika/coroutines/thread_id_type.hpp
- libs/pika/datastructures/include/pika/datastructures/detail/variant.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_operation_state.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/just.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/include/pika/execution/scheduler_queries.hpp
- libs/pika/iterator_support/include/pika/iterator_support/zip_iterator.hpp
- libs/pika/memory/include/pika/memory/intrusive_ptr.hpp
- libs/pika/program_options/include/pika/program_options/detail/config_file.hpp
- libs/pika/tag_invoke/include/pika/functional/detail/tag_fallback_invoke.hpp
- libs/pika/tag_invoke/include/pika/functional/detail/tag_priority_invoke.hpp
- libs/pika/tag_invoke/include/pika/functional/tag_invoke.hpp
- libs/pika/threading/include/pika/threading/thread.hpp
- libs/pika/type_support/include/pika/type_support/empty_function.hpp
Fixes #676.
Introduces a macro that can be used in place of `operator()`. Expands to `static operator()(...)` when the feature is available, `operator()(...) const` otherwise.
This uses a feature testing macro both for host and device compilers. The feature is only enabled if both support it as this should have an effect on how functions are called, and I don't think we want to be mixing translation units with mixed support.
> Use static call operator when available

- .gitlab/includes/clang15_pipeline.yml
- libs/pika/schedulers/include/pika/schedulers/queue_holder_thread.hpp
- libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/thread_queue.hpp
When not using `mmap` for thread stacks we can rely on the allocator to do performant recycling instead of us manually recycling threads. In some situations it seems like not using `mmap` and relying on the allocator recycling memory is faster than us recycling threads. I'm leaving `mmap` as the default though as it's not clear if it's always faster to not use `mmap`.
> Disable recycling of threads when `PIKA_WITH_THREAD_STACK_MMAP` is disabled

- libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool.hpp
- libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool_impl.hpp
This doesn't make a measurable difference in performance, but the counters occasionally show up in `perf c2c` output and it makes sense to separate them to different cache lines.
> Store scheduler counter data on separate cache lines

- libs/pika/coroutines/include/pika/coroutines/detail/context_posix.hpp
Previously enabling address sanitizer under the POSIX context switching implementation would fail to compile. This ports over the address sanitizer support from the x86_64 context switching implementation to the POSIX implementation. The POSIX implementation is what is used on e.g. ARM systems.
> Add support for address sanitizer when using POSIX context switching implementation

- .github/workflows/linux_tsan_blacklist.txt
These tests also occasionally fail with thread sanitizer segfaults, not data races or similar.
> Add `jthread1` and `thread_mf` tests to tsan blacklist in CI

- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
- libs/pika/execution/tests/unit/algorithm_require_started.cpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
Using senders with `noexcept(false)` destructors (such as `require_started`) with `any_sender` otherwise fails to compile because of mismatching exception specifications on the base class (`noexcept`) and the deriving class (`noexcept(false)`). This adds a test which attempts to compile `require_started` senders in `any_sender`.
> Explicitly mark destructors of `any_sender` and related classes `noexcept`

- .github/workflows/linux_asan_ubsan_lsan.yml
- .github/workflows/linux_tsan.yml
GitHub actions runners increased the number of bits used for ASLR in jobs (https://github.com/actions/runner-images/issues/9491) and this breaks thread sanitizer (https://github.com/google/sanitizers/issues/1716). It seems like this has been fixed in LLVM 17 (https://github.com/llvm/llvm-project/commit/fb77ca05ffb4f8e666878f2f6718a9fb4d686839) while we're currently using LLVM 16 in CI. The change to the number of bits may also be rolled back.
The workaround is to decrease the number of bits explicitly in the job.
> Reduce number of bits for ASLR in sanitizer CI jobs to work around GitHub runner change

- libs/pika/tag_invoke/include/pika/functional/detail/tag_fallback_invoke.hpp
- libs/pika/tag_invoke/include/pika/functional/detail/tag_priority_invoke.hpp
- libs/pika/tag_invoke/include/pika/functional/tag_invoke.hpp
This replaces the use of `std::invoke_result` to compute `tag_invoke_result*` with a direct use of `decltype`. At least with libstdc++ `std::invoke_result` results in three levels of template instantiations. Since we in these cases know that we are only making direct function calls, never member function calls, we don't need the more expensive `std::invoke_result`. This very slightly improves compile times in DLA-Future.
> Avoid use of `std::invoke_result` in `tag_invoke_result` and variants

- .gitlab/includes/clang11_pipeline.yml
- .gitlab/includes/clang12_pipeline.yml
- .gitlab/includes/clang13_pipeline.yml
- .gitlab/includes/clang14_cuda11_pipeline.yml
- .gitlab/includes/clang15_pipeline.yml
- .gitlab/includes/clang16_pipeline.yml
- .gitlab/includes/clang17_pipeline.yml
- .gitlab/includes/common_pipeline.yml
- .gitlab/includes/dockerhub_pipeline.yml
- .gitlab/includes/gcc10_apex_pipeline.yml
- .gitlab/includes/gcc11_pipeline.yml
- .gitlab/includes/gcc12_cuda12_pipeline.yml
- .gitlab/includes/gcc12_pipeline.yml
- .gitlab/includes/gcc13_pipeline.yml
- .gitlab/includes/gcc9_cuda11_pipeline.yml
- .gitlab/includes/gcc9_pipeline.yml
- .gitlab/includes/nvhpc23_9_pipeline.yml
- .gitlab/includes/performance_gcc13_pipeline.yml
- .gitlab/pipelines_on_push.yml
- libs/pika/runtime/tests/unit/CMakeLists.txt
The maintenance is ending on the 5th of may 2024, we move back the CI to daint for this period.
> Move CSCS CI to daint during the maintenance

- .github/workflows/docs.yml
- RELEASE_PROCEDURE.rst
- docs/changelog.md
- docs/conf.py
- docs/index.rst
- shell.nix
- tools/roll_release.sh
This adds the current `CHANGELOG.md` to the documentation, at the same time moving it to `docs/changelog.md`. While the documentation is primarily written in restructuredText, I'm keeping the changelog as a markdown file because it's easier to do the checks for dates etc. we currently do in `roll_release.sh`. This requires another sphinx extension, `recommonmark`.
> Add changelog to documentation

- .circleci/config.yml
Fixes #514. The issue reported in #514 seems to be no longer an issue.
> Reenable precompiled headers in CircleCI ARM configuration

- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution_base/include/pika/execution_base/completion_scheduler.hpp
- libs/pika/execution_base/include/pika/execution_base/sender.hpp
- libs/pika/functional/CMakeLists.txt
- libs/pika/functional/include/pika/functional/detail/invoke_result_plain_function.hpp
In the spirit of #1058, add a `invoke_result_plain_function` type trait for use in cases where we know that the function is not a member function and we don't need the full `std::invoke_resutl`. This is true at least in cases where we're checking if a CPO is invocable. More generic cases where the callable comes from the user continue to use `std::invoke_result`.
> Add faster `invoke_result` for cases where we know we're not dealing with member functions

- .circleci/config.yml
- .devcontainer/devcontainer.json
- .github/workflows/linux_asan_ubsan_lsan.yml
- .github/workflows/linux_coverage.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_release_fetchcontent.yml
- .github/workflows/linux_tracy.yml
- .github/workflows/linux_tsan.yml
- .github/workflows/linux_valgrind.yml
- .gitlab/includes/dockerhub_pipeline.yml
- libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool_impl.hpp
When using `--pika:print-bind` the runtime checks that the mask reported by hwloc and the mask supposedly used by pika are the same. When `--pika:bind=none` is used we store an empty mask for worker threads. In this case we also don't set bindings for the worker threads, because we assume that the process has no binding set. However, in the case that the full process already has a mask set (e.g. with `hwloc-bind` or slurm) the worker threads will inherit that mask even with `--pika:bind=none`. The worker threads then end up with a non-full process mask even if the user asked for a full process mask (no binding).
This fixes the issue by always setting a mask, even if the mask is empty/full. This also adds a simple `hello_world` test to the CircleCI configuration. I'm not adding this a …
> Fix use `--pika:print-bind`, `--pika:bind=none`, and a non-full process mask on the process together

- libs/pika/async_cuda/include/pika/async_cuda/cuda_pool.hpp
- libs/pika/async_cuda_base/include/pika/async_cuda_base/cublas_handle.hpp
- libs/pika/async_cuda_base/include/pika/async_cuda_base/cuda_stream.hpp
- libs/pika/async_cuda_base/include/pika/async_cuda_base/cusolver_handle.hpp
- libs/pika/coroutines/include/pika/coroutines/thread_enums.hpp
- libs/pika/coroutines/include/pika/coroutines/thread_id_type.hpp
- libs/pika/errors/include/pika/errors/error.hpp
- libs/pika/execution_base/include/pika/execution_base/agent_ref.hpp
- libs/pika/logging/include/pika/logging/level.hpp
- libs/pika/memory/include/pika/memory/intrusive_ptr.hpp
- libs/pika/schedulers/include/pika/schedulers/local_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/local_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/static_priority_queue_scheduler.hpp
- libs/pika/schedulers/include/pika/schedulers/static_queue_scheduler.hpp
- libs/pika/threading/include/pika/threading/thread.hpp
- libs/pika/threading_base/include/pika/threading_base/scheduler_base.hpp
- libs/pika/threading_base/include/pika/threading_base/thread_description.hpp
- libs/pika/threading_base/include/pika/threading_base/thread_pool_base.hpp
This is apparently required for `std::formatter` specializations, and the current fmt master branch has started requiring the same (https://github.com/fmtlib/fmt/commit/d70729215fba1d54862e407b626abf86ddf409bf).
> Mark `fmt::formatter` `format` member functions `const`

- .github/workflows/macos_debug.yml
Pin the macos workflow to use the `macos-12` runner (which supposedly still uses intel CPUs) while `macos-latest` is gradually being rolled out to use `macos-14` (supposedly based on the M* CPUs). This also fixes an error which happens during `brew upgrade` where `xcbeautify` cannot be upgraded due to other conflicting packages.
> Explicitly use macos-12 image in GitHub macos workflow

- CMakeLists.txt
- libs/src/dummy_main.cpp
When defining the `pika` CMake target we need a dummy cpp file since we don't otherwise have any source files for the `pika` target, only object files that are added later. For this we've so far reused a `dummy.cpp` file which has `main` defined. This means that `libpika.so` actually has `main` defined as well. Depending on where `main` is otherwise defined by an application using pika (another shared library or in the executable itself) the application may end up using the empty `main` defined in `libpika.so`. `main` should never have been in `libpika.so` in the first place, and this PR removes it from `libpika.so` by using an empty `dummy.cpp` file for `libpika.so` and a separate `dummy_main.cpp` with `main` defined for precompiled headers for executables (never exposed to consumers of …
> Make sure `main` is never defined in `libpika.so`

- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
- libs/pika/logging/include/pika/logging/message.hpp
- libs/pika/logging/src/format/formatter/high_precision_time.cpp
- libs/pika/logging/src/format/formatter/thread_id.cpp
Fix #1026.
Current fmt `master` has deprecated `fmt/core.h` in favour of `fmt/base.h` or `fmt/format.h` (https://github.com/fmtlib/fmt/blob/12acd7988b5eef3df060f321f61982221ec45d26/include/fmt/core.h). I've updated includes of `fmt/core.h` to use `fmt/base.h` if the latter is available (with `__has_include`). In cases where `fmt/format.h` is anyway included I've simply removed the `fmt/core.h` include.
> Replace includes of `fmt/core.h` with `fmt/base.h`

- .gitlab/docker/Dockerfile.sloc_base
- .gitlab/includes/sloc.yml
- .gitlab/pipelines_on_push.yml
- .gitlab/scripts/sloc.sh
This reports the number of lines of code to elastic using https://github.com/flosse/sloc. I filter out the line counts for individual files before sending the data. I also only send the data for the `lib/pika` directory, excluding tests and examples. What remains are the total lines of code in `libpika`, optionally categorized by filetype and type of line (source line, comment, empty line etc.).
The CI job runs on the CSCS CI infrastructure to be able to send data to elastic. The `sloc` tool now runs on a compute node, which is somewhat overkill. An alternative would be to run that step on rosa as well, but it leads to a slightly more complicated job description (since only whitelisted images are allowed to run on rosa, it would require running docker inside docker, which is awkward in …
> Report lines of code to elastic

- docs/conf.py
Suppresses the following warning, treated as error:
```
Warning, treated as error:
cannot cache unpickable configuration value: 'html_context' (because it contains a function, class, or module object)
```
More information in https://github.com/sphinx-doc/sphinx/issues/12300.
> Suppress harmless warnings about caching in documentation build

- .circleci/config.yml
Updates the base image to Ubuntu 22.04. This is not yet enough to install fmt from the repositories (22.04 still has fmt 8, whereas we require 9 or newer).
> Install cmake from repositories in ARM CircleCI configuration

- .circleci/config.yml
The test seems to no longer be failing the same way it was before. Going to test this on `main` for a while and revert if needed.
> Reenable `condition_variable2` test on ARM CircleCI configuration

- libs/pika/config/include/pika/config.hpp
After https://github.com/pika-org/pika/pull/927 `spin_k` and `yield_k` go through iterations much slower. This means that the spinlock deadlock warnings may not be printed in any reasonable time with the old limits. This reduces the error limit by an order of magnitude, and the warning limit by two orders of magnitude (since this is typically the interesting message, and it's harmless when printed). The limits can still be changed with configuration options as before, and the detection is still opt-in.
> Reduce spinlock detection limits now that spinlocks do backoff

- .gitlab/includes/gcc11_pipeline.yml
- libs/pika/init_runtime/src/init_runtime.cpp
Also enabled a CI configuration which ensures that this configuration keeps building in the future.
> Fix build with `PIKA_HAVE_THREAD_DEADLOCK_DETECTION_ENABLED`

- .gitlab/includes/common_spack_pipeline.yml
- .gitlab/includes/gcc10_apex_pipeline.yml
- cmake/pika_add_test.cmake
- libs/pika/async_mpi/tests/unit/CMakeLists.txt
- libs/pika/threading_base/tests/unit/CMakeLists.txt
- tools/sort-output.sh
Fixes #948. This also adds a little wrapper script around the APEX annotation test that sorts the output so that we can use later versions of APEX in unit tests to check for the correct output; later versions of APEX don't sort timers alphabetically anymore, but by time leading to the output potentially changing between runs.
> Test APEX 2.6.5 in CI

- .gitlab/includes/gcc13_pipeline.yml
Enables `_GLIBCXX_DEBUG` and related options in the GCC 13 CI configuration (debug and release): https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html#debug_mode.using.mode.
> Use `_GLIBCXX_DEBUG` in CI

- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_helpers.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
- libs/pika/debugging/include/pika/debugging/demangle_helper.hpp
- libs/pika/debugging/include/pika/debugging/print.hpp
- tools/clang-reformat.sh
part 1 : Simplifies the debug helper code by removing ifdefs and using `__has_include` for c++ name demmangling
part 2 : declutter some of the mpi code for example by moving a namespace check into a macro so it doesn't need to be used in many places.
pushing this PR because it is in my incoming MPI change PR and can be reviewed separately
Note that removing the debug code and replacing it with `fmt::` is a next step.
> Minor debug cleanup

- .gitlab/includes/gcc12_hip5_pipeline.yml
- .gitlab/pipelines_on_push.yml
Tests remain disabled due to clariden still being unavailable, but we can already test that builds work.
> Reenable HIP CI builds in CSCS CI

- .github/workflows/linux_asan_ubsan_lsan.yml
- .github/workflows/linux_tsan.yml
- .github/workflows/linux_valgrind.yml
- tools/tsan.supp
- tools/valgrind/memcheck.supp
Enables MPI support in valgrind and sanitizer CI configurations. Since OpenMPI seems to be unhappy running under thread sanitizer, I've switched OpenMPI to MPICH in all the sanitizer configurations. I think it probably makes sense to keep testing both OpenMPI and MPICH in different configurations (so far we've had no MPICH CI configuration). Uninstalling OpenMPI and installing MPICH in the CI job takes ~10 seconds, so at the moment I'm not bothering with a separate container image.
I've had to suppress memory leaks in ORTE (OpenMPI) and data races in `boost::lockfree::stack` (used in one of the tests, same issue as https://github.com/pika-org/pika/issues/990).
> Enable MPI support in valgrind and sanitizer CI configurations

- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_helpers.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_polling.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
This PR contains a number of improvements to the mpi polling and continuation handling
1) If a request is not being handled inline, then it must be transferred to the polling pool - but if the polling pool has been disabled, then this extra transfer can be elided. We remove some unwanted transfers
2) If the polling pool is enabled and no other thread can participate in the handling of requests/continuations, then the polling loop can be simplified to remove some locks and queues as they are unnecessary
3) Remove all stream based operations (they will be reinstated in a later PR)
4) Consistently handle high priority boosts for tasks that are transferred/injected to the polling loop or back to the work queues.
> More MPI polling improvements

- .github/workflows/linux_asan_ubsan_lsan_blacklist.txt
`cross_pool_injection` and `suspend_thread` tests have been failing more frequently lately. They need looking into, but I'm blacklisting them for now to make progress with other PRs.
> Blacklist two more tests in address sanitizer CI configuration

- libs/pika/async_mpi/include/pika/async_mpi/mpi_polling.hpp
nvc++ warns about unreachable statements. Since the breaks are preceded by returns the breaks are not needed.
> Remove unnecessary breaks from `mpi_polling.hpp`

- libs/pika/threading_base/src/set_thread_state.cpp
`set_thread_state` reports events that can occur under normal circumstances as warnings. This downgrades those messages to info messages.
> Downgrade `set_thread_state` warnings to info messages

- .gitlab/docker/Dockerfile.spack_base
- .gitlab/includes/clang18_pipeline.yml
- .gitlab/includes/common_spack_pipeline.yml
Use Boost 1.85.0 in clang 18 CI configuration. Also updates the spack commit used in CI to include the upstream change have spdlog as a dependency.
> Use Boost 1.85.0 in CI

- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
Avoids some unnecessary move constructions. Could further be refactored to simply pass a reference to the operation state and access the receiver through that, but leaving that for a separate PR.
> Access receiver by reference in `split`, `split_tuple`, and `ensure_started` visitors

- libs/pika/debugging/src/print.cpp
- libs/pika/init_runtime/CMakeLists.txt
- libs/pika/init_runtime/src/init_logging.cpp
This fixes some minor issues with the logging output related to hostnames and ranks:
- The hostname was printed twice in multi-rank runs.
- The thread and pool indices were printed as hexadecimal which in my opinion doesn't make much sense; they're now printed as decimal.
- The MPI rank is retrieved with `MPI_Comm_rank` first, if MPI is initialized.
- If the MPI rank can't be retrieved with `MPI_Comm_rank`, the way environment variables are checked is slightly changed to prioritize environment variable names that are more likely to contain the rank.
> Minor logging fixes

- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
> Fix inconsistency and store another receiver by reference in `split_tuple`

- libs/pika/resource_partitioner/include/pika/resource_partitioner/partitioner_fwd.hpp
- libs/pika/resource_partitioner/src/partitioner.cpp
- libs/pika/resource_partitioner/tests/unit/cross_pool_injection.cpp
- libs/pika/resource_partitioner/tests/unit/shutdown_suspended_pus.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_pool.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_pool_external.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_runtime.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_thread.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_thread_external.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_thread_timed.cpp
Also adds a `fmt::formatter` specialization for `pika::resource::scheduling_policy` to be able to print the scheduler.
I'm adding this to aid in understanding if a particular scheduler is more likely to fail in CI.
> Print scheduler in suspension unit tests

- .gitlab/includes/clang11_pipeline.yml
- .gitlab/includes/clang12_pipeline.yml
- .gitlab/includes/clang13_pipeline.yml
- .gitlab/includes/clang14_cuda11_pipeline.yml
- .gitlab/includes/clang15_pipeline.yml
- .gitlab/includes/clang16_pipeline.yml
- .gitlab/includes/clang17_pipeline.yml
- .gitlab/includes/clang18_pipeline.yml
- .gitlab/includes/gcc10_apex_pipeline.yml
- .gitlab/includes/gcc11_pipeline.yml
- .gitlab/includes/gcc12_cuda12_pipeline.yml
- .gitlab/includes/gcc12_hip5_pipeline.yml
- .gitlab/includes/gcc12_pipeline.yml
- .gitlab/includes/gcc13_pipeline.yml
- .gitlab/includes/gcc9_cuda11_pipeline.yml
- .gitlab/includes/gcc9_pipeline.yml
- .gitlab/includes/nvhpc23_9_pipeline.yml
Changes `commmon` to `common`.
> Fix typo in CI job names

- .gitignore
- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_helpers.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_polling.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
Some cleanups to the main mpi polling routines and API - quite a lot of redundant use removed and some minor api changes to make things clearer.
And ...  support for mpi-continuations using the openmpi extension. 
we check for the extension using
```
#if __has_include(<mpi-ext.h>)
``` 
so code is only enabled if `OMPI_HAVE_MPI_EXT_CONTINUE` is found in `<mpi-ext.h>` 
Some optimizations are added to handle single/multiple threaded polling
> Add support for MPI continuations

- .circleci/config.yml
Tests are currently built in CI. This disables building fmt tests.
> Explicitly disable building tests and documentation for fmt in CI

- .github/workflows/linux_coverage.yml
- .github/workflows/linux_coverage_upload.yml
We currently only run the coverage workflow on `main`. This enables it for pull requests and the `release-*` branches as well.
Since PRs don't have access to secrets this uses a `workflow_run` workflow, which does have access to secrets, to upload the coverage report. The PR itself simply generates the coverage report and stores it in GitHub artifacts and then the `workflow_run` workflow downloads the file and pushes it to codacy.
> Run coverage on PRs

- .github/workflows/linux_coverage_upload.yml
#1170 had an unnecessary change of working directory to a non-existent directory. This removes the change of working directory and uses the default.
> Fix coverage report upload job

- docs/api.rst
- docs/index.rst
- docs/usage.rst
This also changes the hyperlinks in the documentation to anonymous hyperlinks (`__` instead of `_`) to avoid rst target name conflicts when the link text is the same.
> Add "More resources" section to documentation

- examples/balancing/thread_phase.cpp
Fix issue reported in snyk: https://app.snyk.io/org/aurianer/project/d4ed2629-64fe-44d9-abaa-66f15e7df793#issue-bce65bf9-47be-48ea-85c0-5dd53ac4846c
Update thread_phase to use the new barrier
> Add assert to ensure the rhs parameter of modulo is not zero

- docs/api.rst
- docs/usage.rst
Also links to "More resources" in "API reference" section.
> Add link to cppreference.com execution documentation

- libs/pika/ini/src/ini.cpp
- libs/pika/ini/tests/unit/CMakeLists.txt
- libs/pika/ini/tests/unit/parse.cpp
snyk emits a warning when using the operator- in `std::string::substr`
https://app.snyk.io/org/aurianer/project/d4ed2629-64fe-44d9-abaa-66f15e7df793#issue-f1446f1e-dfef-4c06-837b-1f64300d28ce
this is an attempt to fix the warning
> Attempt to fix integer overflow snyk warning

- libs/pika/execution/tests/unit/algorithm_unpack.cpp
This was likely used for testing at some point, but is not supposed to be there permanently.
> Remove stray `tag_invoke` deletion in unpack test

- docs/Doxyfile
- docs/api.rst
- examples/documentation/CMakeLists.txt
- examples/documentation/split_tuple_documentation.cpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
Adds `split_tuple` to the API reference under `pika/execution.hpp`. Includes the doxygen docstring and a small example program that uses `split_tuple`.
I'm starting to document the `pika::execution` functionality that is not available in P2300 or stdexec, since documentation for what is in P2300 can be looked up elsewhere.
> Add documentation for `split_tuple`

- libs/pika/async_mpi/include/pika/async_mpi/mpi_polling.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/CMakeLists.txt
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/command_line_handling/src/parse_command_line.cpp
- libs/pika/init_runtime/CMakeLists.txt
- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
- tools/valgrind/memcheck.supp
Fixes #1142, except for testing the MPI continuations modes. Those will be enabled separately (https://github.com/pika-org/pika/issues/1150).
This:
- Adds a `--pika:mpi-completion-mode` flag for setting the mode via command line options. This isn't intended as the primary way to change the mode for users, but is mostly there for the unit test. CMake's `ENVIRONMENT` property on tests allows setting an environment variable. I originally intended to use this, but the variables are not exported so sub-processes don't see the value, and since the tests are run through `mpirun`/`mpiexec` the variable isn't applied.
- Decrements MPI counters before calling the user-provided callback. This fixes a race in the test checking for zero MPI requests in flight. The assertion is also changed to use …
> Test `mpi_ring_async_sender_receiver` with all MPI completion modes

- .gitlab/scripts/run_performance_benchmarks.sh
- tests/performance/local/CMakeLists.txt
- tests/performance/local/task_yield.cpp
The added benchmark simply times how long a yield and reschedule takes, i.e. two context switches and adding and removing the task from a queue.
This also adds the benchmark to CI with both `--pika:threads=1` and `--pika:threads=2`. The one-thread version runs significantly faster, probably due to less contention from other threads trying to steal tasks. Running with more than one worker thread and the static scheduler gives roughly the same timings as a single worker thread with the default scheduler.
> Add task yield benchmark

- .gitlab/includes/gcc10_apex_pipeline.yml
- CMakeLists.txt
- cmake/pika_add_library.cmake
- libs/CMakeLists.txt
- testing/performance_testing/CMakeLists.txt
- testing/testing/CMakeLists.txt
Fixes #491.
With this change, all libraries follow `BUILD_SHARED_LIBS` to decide whether they'll be static or shared. Object libraries are still used internally. One CI configuration has `BUILD_SHARED_LIBS` disabled, otherwise `BUILD_SHARED_LIBS` is enabled by default.
> Allow compiling libpika as a static library

- tools/valgrind/memcheck.supp
Suppresses for example leaks like these:
```
==4005== 
==4005== HEAP SUMMARY:
==4005==     in use at exit: 150,473 bytes in 456 blocks
==4005==   total heap usage: 25,629 allocs, 25,173 frees, 5,781,499 bytes allocated
==4005== 
==4005== 40 bytes in 1 blocks are possibly lost in loss record 128 of 265
==4005==    at 0x4845828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==4005==    by 0x4C396F1: hwloc_alloc_setup_object (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3)
==4005==    by 0x4C71CB6: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3)
==4005==    by 0x4C6AB08: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3)
==4005==    by 0x4C67055: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3)
==4005==    by 0x4C42B7A: hwloc_topology_load (in …
```
> Suppress another OpenMPI/`orte_init` leak reported by valgrind in MPI tests

- .gitlab/includes/gcc10_apex_pipeline.yml
- .gitlab/includes/gcc11_pipeline.yml
I suspect that something related to static libraries are causing problems on the APEX CI configuration: https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/479009878135925/5304355110917878/-/jobs/7312229099#L133. This PR moves `BUILD_SHARED_LIBS=OFF` to another CI configuration to see if that's the case.
> Use static libraries on a CI configuration without APEX enabled

- libs/pika/include/include/pika/execution.hpp
- tests/performance/local/condition_variable_overhead.cpp
Adds `pika/condition_variable.hpp` to the condition variable overhead test and the `execution_base` module header explicitly to `pika/execution.hpp`.
> Add missing includes

- tools/valgrind/memcheck.supp
There are more `orte_init` leaks in the style of https://github.com/pika-org/pika/pull/1201 reported in the MPI tests. This makes the suppression more generic.
> Make `orte_init` memcheck suppressions more generic

- .gitlab/includes/common_spack_pipeline.yml
Also sets `SPACK_REPO` as a build argument in the spack base image stage (the default in the Dockerfile was the same as the value we were setting in the configuration, so no change is expected from this change).
> Separate x86 and ARM CSCS CI pipelines to be completely independent

- libs/pika/command_line_handling/src/command_line_handling.cpp
This fixes the `PIKA_MPI_COMPLETION_MODE` environment variable not being taken into account.
> Get fallback MPI completion mode from runtime configuration

- docs/api.rst
- examples/documentation/CMakeLists.txt
- examples/documentation/when_all_vector_documentation.cpp
- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
I should note that writing this highlighted to me the design decision to make `when_all_vector` require that senders send exactly zero or one values. This need not be the case in general, and we can consider changing `when_all_vector` or adding a new algorithm to instead send a `vector<tuple<Ts...>>` or even `vector<variant<tuple<T1s...>, tuple<T2s...>, ...>>` as more generic versions of the current implementation. This is similar to how there's a `sync_wait` and `sync_wait_with_variant` in P2300. I will not change the behaviour here, just highlight the possibility for the future.
> Add documentation for `when_all_vector`

- .gitlab/scripts/utilities.sh
- Only show errors, not progress, when curling to logstash
- Ignore errors when submitting to logstash (as a failure in submission shouldn't affect the pass/fail of the job as a whole; we don't mind if some submissions fail)
> Make logstash submissions quieter

- libs/pika/affinity/src/affinity_data.cpp
- libs/pika/affinity/src/parse_affinity_options.cpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/mpi_async_storage.cpp
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/resource_partitioner/examples/oversubscribing_resource_partitioner.cpp
- libs/pika/resource_partitioner/examples/simple_resource_partitioner.cpp
- libs/pika/resource_partitioner/examples/simplest_resource_partitioner_2.cpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/detail/partitioner.hpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/partitioner.hpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/partitioner_fwd.hpp
- libs/pika/resource_partitioner/src/detail_partitioner.cpp
- libs/pika/resource_partitioner/src/partitioner.cpp
- libs/pika/resource_partitioner/tests/unit/cross_pool_injection.cpp
- libs/pika/resource_partitioner/tests/unit/named_pool_executor.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_pool.cpp
- libs/pika/resource_partitioner/tests/unit/suspend_thread_external.cpp
- libs/pika/thread_manager/tests/unit/thread_num.cpp
Still a draft. Tested on Grace-Hopper system to give correct results. This is only the minimal change needed which changes uses of topology `*numa_node*` functionality to `*socket*`.
Fixes #1223.
When dealing with thread affinity, this now uses sockets instead of numa nodes. This also means that the following changes:
- the resource partitioner helper object `resource::numa_domain` is now called `resource::socket` instead, including all related variables
- the `--pika:bind` option `numa` is now called `socket`
The following hasn't changed:
- The `numa-balanced` mapping is still called `numa-balanced`. Should we rename it `socket-balanced`?
- The `numa-sensitive` command line/config option is still called `numa-sensitive`. I think this still makes sense (even though many schedulers don't …
> Use sockets, not NUMA nodes, when dealing with CPU masks

- .gitlab/includes/common_spack_pipeline.yml
- cmake/pika_setup_boost.cmake
Fixes #1222
We require Boost version >= 1.71 in pika, `BoostConfig.cmake` is available in boost installations since 1.70, so only changing module to config was necessary.
> Adapt to `FindBoost` deprecation with CMake 3.30

- .gitlab/includes/gcc12_hip6_pipeline.yml
- .gitlab/pipelines_on_merge.yml
- .gitlab/pipelines_on_push.yml
- libs/pika/async_cuda_base/include/pika/async_cuda_base/custom_lapack_api.hpp
- libs/pika/async_cuda_base/src/cublas_exception.cpp
- libs/pika/async_cuda_base/src/cusolver_exception.cpp
- libs/pika/program_options/tests/unit/variable_map.cpp
Fixes #1164. The newly added GCC 12/HIP 6 configuration is now run on pushes and replaces the old GCC 12/HIP 5 which is still run on merges.
GCC (libstdc++) 13 and newer are incompatible with HIP for now: https://github.com/spack/spack/pull/46291.
> Add GCC 12 and HIP 6 CI configuration

- libs/pika/async_cuda/include/pika/async_cuda/cuda_pool.hpp
- libs/pika/async_cuda/src/cuda_pool.cpp
This changes the `cuda_pool` to only use "synchronized" handles, no matter which thread is using the handle (worker thread or non-worker thread). Each handle is protected by a mutex which must be held until a cuBLAS/SOLVER operation has been submitted (this part is unchanged for synchronized handles; previously worker thread handles did not use a mutex at all). The default values are 16 of each type of handle. In DLA-Future this seems to give virtually identical performance to the previous implementation using additional handles per worker thread.
16 handles by default was chosen based on DLA-Future showing that more handles don't improve performance any more. I tried 1 to 128 handles on the eigensolver miniapp. 8 handles already gave almost the best performance so I took one more step …
> Use fewer cuBLAS/SOLVER handles in `cuda_pool`

- libs/pika/runtime/tests/unit/CMakeLists.txt
This further relaxes the regex used to check thread bindings. We really only care that the first thread is bound to the first PU. This separates the updated check from https://github.com/pika-org/pika/pull/1130.
> Relax thread bindings test

- .gitlab/includes/common_spack_pipeline.yml
This is intended to work around occasional rate limiting happening in CI when pulling base images. Since CI uses anonymous access before this PR, often from the same nodes, the chances of being rate limited are higher. CI jobs fail when rate limiting happens.
Using credentials gives us our own rate limit. The rate limit is also higher than the anonymous usage. From https://www.docker.com/increase-rate-limits/:
> The rate limits of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts are now in effect. Image requests exceeding these limits will be denied until the six hour window elapses.
> Use dockerhub credentials for pulling base image in CI

- .github/workflows/linux_asan_ubsan_lsan.yml
- libs/pika/resource_partitioner/tests/unit/CMakeLists.txt
The apparent false-positive that was occuring in the cross_pool_injection test is also sometimes triggered in other tests, so I'm disabling lock registration completely on the address sanitizer CI configuration.
> Disable lock registration on address sanitizer CI configuration

- libs/pika/async_mpi/CMakeLists.txt
We already print:
```
-- Performing Test PIKA_WITH_MPIX_CONTINUATIONS - Failed
```
when performing the feature test itself. I propose to remove the trailing:
```
-- MPIx Continuations not detected
```
since:
- it says the same as the previous line (admittedly a bit nicer, but still)
- we only print the `Performing Test PIKA_WITH...` line for all other feature checks
> Remove unnecessary status messages when detecting MPI continuations support

- .gitlab/includes/common_spack_pipeline.yml
The clang 11 CI configuration is currently failing with
```
==> Error: ProcessError: Command exited with status 1:
'./b2' '--clean' '-j' '16' '--user-config=/tmp/root/spack-stage/spack-stage-boost-1.72.0-qnonvjuixruadplceoy4zl42eaku6tac/spack-src/user-config.jam' 'variant=release' '--disable-icu' 'link=static,shared' '--layout=system' 'toolset=clang' 'cxxstd=17' 'pch=off' 'visibility=hidden'
1 error found in build log:
23    
24       - Boost.Build documentation:
25         http://www.boost.org/build/
26    
27    ==> [2024-09-10-12:28:55.608406] FILTER FILE: /tmp/root/spack-stage/
spack-stage-boost-1.72.0-qnonvjuixruadplceoy4zl42eaku6tac/spack-src/
project-config.jam [replacing "^\s*using clang.*"]
28    ==> [2024-09-10-12:28:55.611217] './b2' '--clean' '-j' '16' '--user- …
```
> Update spack commit in CI to fix clang 11 configuration

- libs/pika/command_line_handling/src/late_command_line_handling.cpp
- libs/pika/coroutines/include/pika/coroutines/detail/context_posix.hpp
- libs/pika/coroutines/include/pika/coroutines/detail/context_windows_fibers.hpp
- libs/pika/coroutines/include/pika/coroutines/detail/posix_utility.hpp
- libs/pika/coroutines/include/pika/coroutines/stackless_coroutine.hpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/tests/unit/algorithm_require_started.cpp
- libs/pika/execution/tests/unit/algorithm_when_all.cpp
- libs/pika/execution_base/tests/unit/basic_schedule.cpp
- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/iterator_support/tests/performance/stencil3_iterators.cpp
- libs/pika/lock_registration/include/pika/lock_registration/detail/register_locks.hpp
- libs/pika/program_options/tests/unit/parsers.cpp
- libs/pika/schedulers/include/pika/schedulers/queue_holder_numa.hpp
- libs/pika/synchronization/include/pika/synchronization/condition_variable.hpp
- libs/pika/synchronization/include/pika/synchronization/latch.hpp
- libs/pika/synchronization/src/detail/condition_variable.cpp
- libs/pika/synchronization/src/mutex.cpp
- libs/pika/thread_manager/src/thread_manager.cpp
- libs/pika/thread_support/include/pika/thread_support/assert_owns_lock.hpp
Removes unused `pika/type_support/unused.hpp` includes and removes some unnecessary uses of `PIKA_UNUSED`.
> Replace `PIKA_UNUSED` by `[[maybe_unused]]`

- .gitlab/includes/common_spack_pipeline.yml
This should be temporary, but is required for at least a month or so.
> Set slurm account/reservation for gh200 CI configurations

- CMakeLists.txt
- libs/pika/async_mpi/CMakeLists.txt
- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_helpers.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_polling.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/mpi_async_storage.cpp
- libs/pika/include/include/pika/mpi.hpp
- libs/pika/init_runtime/src/init_logging.cpp
- libs/pika/mpi_base/CMakeLists.txt
- libs/pika/mpi_base/include/pika/mpi_base/mpi.hpp
- libs/pika/mpi_base/include/pika/mpi_base/mpi_environment.hpp
- libs/pika/mpi_base/include/pika/mpi_base/mpi_exception.hpp
- libs/pika/mpi_base/src/mpi_environment.cpp
- libs/pika/mpi_base/src/mpi_exception.cpp
- libs/pika/runtime/src/custom_exception_info.cpp
- libs/pika/runtime/src/runtime.cpp
Remove unused features/functions/variables.
Most of mpi_base was brought in from HPX which needs MPI for it's internal communication (active messages) and it must therefore guarantee initialization and certain setup defaults whenever it might be used in a multi node environment.
pika only uses MPI when the user explicitly requests MPI and therefore the setup/teardown is always directed by the user and we can remove some unnecessary code/checks.
Replace some duplicated mpi initialized/rank fetch calls in pika body with reused functions from mpi_environment.
> Clean up `mpi_base` module

- .gitlab/includes/common_spack_pipeline.yml
> Remove slurm reservation and account used in CI

- libs/pika/synchronization/tests/unit/condition_variable.cpp
Such as https://github.com/pika-org/pika/actions/runs/11160644254/job/31021523469#step:7:423:
```
205/222 Test #142: tests.unit.modules.synchronization.condition_variable ..............................***Timeout 120.02 sec
/Users/runner/work/pika/pika/libs/pika/synchronization/tests/unit/condition_variable.cpp(487): test 'data->condition.wait_for(lock, std::chrono::milliseconds(100), pred_rel)' failed in function 'void condition_test_waits(condition_test_data *)'
/Users/runner/work/pika/pika/libs/pika/synchronization/tests/unit/condition_variable.cpp(489): test 'pred_rel()' failed in function 'void condition_test_waits(condition_test_data *)'
/Users/runner/work/pika/pika/libs/pika/synchronization/tests/unit/condition_variable.cpp(490): test 'data->notified == 5' failed in function 'void …
```
> Attempt to increase wait time in condition variable test to avoid timeouts

- .gitlab/includes/gcc12_cuda12_pipeline.yml
- cmake/pika_add_config_test.cmake
- cmake/pika_perform_cxx_feature_tests.cmake
- cmake/tests/cxx20_trivial_virtual_destructor.cu
- cmake/tests/cxx20_trivial_virtual_destructor.hip
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
Adds a configuration check to see if the GPU compiler supports trivial virtual destructors that can be used in constexpr contexts. nvcc at least up to version 12.6 does not support it (https://compiler-explorer.com/z/4hfvrnzcG).
> Use C++20 in CUDA 12 CI configuration

- libs/pika/async_cuda_base/include/pika/async_cuda_base/detail/cuda_debug.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/mpi_async_storage.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
- libs/pika/debugging/include/pika/debugging/print.hpp
- libs/pika/schedulers/include/pika/schedulers/shared_priority_queue_scheduler.hpp
Avoid using `static` as each translation unit will end up with its own instance. Functionally there should be no difference, but `inline constexpr` is more idiomatic. This also changes one function-level `static` to `static constexpr`.
> Make `print_threshold` helper variables `inline constexpr`

- cmake/pika_add_test.cmake
The `EXECUTABLE` argument was not properly taken into account. For e.g. the MPI unit tests that test many different modes, the linking happened because we have a generic test without the `EXECUTABLE` argument that simply tests the default mode. This test was opting into the linking for all the other tests as well, but the other tests were not explicitly linking against `pika_testing`. It happened to work because they all use the same executable.
> Fix logic for linking to `pika_testing`

- libs/pika/debugging/include/pika/debugging/print.hpp
Fixes #1273 
Recent merge missed a `const` modifier on the eval function
> Add `const` to `eval` function in debug print functionality

- tools/valgrind/memcheck.supp
Suppresses warnings like:
```
==3585== 
==3585== HEAP SUMMARY:
==3585==     in use at exit: 150,459 bytes in 456 blocks
==3585==   total heap usage: 25,548 allocs, 25,092 frees, 5,775,479 bytes allocated
==3585== 
==3585== 24 bytes in 1 blocks are possibly lost in loss record 94 of 266
==3585==    at 0x4845828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==3585==    by 0x4C46D29: hwloc_bitmap_dup (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3)
==3585==    by 0x4C3DAE7: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3)
==3585==    by 0x4C3DA75: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3)
==3585==    by 0x4C3DA75: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3)
==3585==    by 0x4C3DA75: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.15.6.3) …
```
> Suppress `hwloc_topology_load` leak reported by valgrind

- libs/pika/async_mpi/CMakeLists.txt
- libs/pika/async_mpi/include/pika/async_mpi/mpi_helpers.hpp
- libs/pika/async_mpi/include/pika/async_mpi/mpi_polling.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/CMakeLists.txt
- libs/pika/async_mpi/tests/unit/algorithm_transform_mpi.cpp
- libs/pika/async_mpi/tests/unit/mpi_async_storage.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
- libs/pika/async_mpi/tests/unit/pool_creation.cpp
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/command_line_handling/src/parse_command_line.cpp
- libs/pika/init_runtime/include/pika/init_runtime/init_runtime.hpp
- libs/pika/init_runtime/src/init_runtime.cpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/detail/partitioner.hpp
- libs/pika/resource_partitioner/include/pika/resource_partitioner/partitioner_fwd.hpp
- libs/pika/resource_partitioner/src/detail_partitioner.cpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
Add a configuration option to enable/disable creation of MPI pool. This removes the need for the user to setup a polling pool manually.
Move many functions into `detail` namespace to designate them as being for internal use only and not for general user consumption.
Clean up some of the enum flags and options that are used to setup pools and polling modes etc.
Change the default mode to "continuation mode" + "inline completion" + "high priority". The MPI pool is disabled by default. Fix #1143.
> Allow pika to automatically create MPI pool on startup

- tools/valgrind/memcheck.supp
Suppress both malloc and realloc leaks.
> Make valgrind memcheck suppressions more generic

- .github/workflows/linux_asan_ubsan_lsan.yml
- libs/pika/async_mpi/tests/unit/algorithm_transform_mpi.cpp
- libs/pika/config/include/pika/config/compiler_specific.hpp
- tools/lsan.supp
It's not really clear if we've just gotten lucky or if something else was going on in that test, but we should be initializing MPI with `MPI_THREAD_MULTIPLE` to be on the safe side.
Thank you @RMeli for noticing this.
> Use `MPI_Init_thread` in `algorithm_transform_mpi` test

- libs/pika/datastructures/include/pika/datastructures/detail/small_vector.hpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/functional/include/pika/functional/detail/vtable/vtable.hpp
`aligned_storage(_t)` is deprecated starting with C++23. Replace uses with `alignas(...) unsigned char[...]`.
> Remove uses of `aligned_storage_t`

- .inshpect.toml
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/command_line_handling/src/command_line_handling.cpp
- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
- libs/pika/runtime/src/runtime.cpp
- libs/pika/schedulers/include/pika/schedulers/thread_queue.hpp
- libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool_impl.hpp
Also adds an inshpect rule to check that when `PIKA_LOG` is used `pika/logging.hpp` is included.
All output that was changed in this PR are now warnings. Please comment if you feel like they should be using a different logging level.
> Move manual `std::cerr` output to use `PIKA_LOG`

- .gitlab/includes/common_spack_pipeline.yml
- .jenkins/cscs-perftests/env-perftests.sh
- cmake/pika_setup_allocator.cmake
- docs/usage.rst
- Add some notes on tweaking mimalloc performance with environment variables
- Add warnings about always benchmarking, and mimalloc not always being the best choice
- Update uses of `MIMALLOC_LARGE_OS_PAGES` to `MIMALLOC_ALLOW_LARGE_OS_PAGES` (the former being an old, deprecated, spelling and the latter being the preferred spelling; the latter should also work on mimalloc 1.X).
> Add more documentation on using custom allocators

- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
I missed this leftover newline in #1291 and was a bit too eager in merging #1291.
> Remove stray newline in `require_started` sender adaptor error message

- docs/Doxyfile
- libs/pika/init_runtime/include/pika/init_runtime/init_runtime.hpp
- libs/pika/runtime/include/pika/runtime/runtime.hpp
- Use `EXTRACT_ALL = YES` to make sure references can be resolved
- Use explicit function signatures e.g. for `pika::start` so that a link is actually generated (since there are multiple overloads)
- Fix the wrong `@pika::stop` syntax (missing `@ref`)
- For consistency: use `@ref pika::stop()`, i.e. empty parentheses for functions that don't take any parameters
As a bonus: adds `@brief` to the first lines of the documentation for each function.
> Fix references in documentation

- libs/pika/execution/tests/unit/CMakeLists.txt
With APEX enabled, APEX's output may be interleaved between the logging messages and the terminate message, so allow for output to come in between the two.
Also allows any output at the end of the output.
Another follow-up to #1291 and #1296.
> Relax regex for the `require_started_terminated` test

- .gitlab/includes/clang19_pipeline.yml
- .gitlab/includes/common_spack_pipeline.yml
- .gitlab/pipelines_on_merge.yml
- libs/pika/concurrency/include/pika/concurrency/deque.hpp
Also enables libc++'s hardening mode (https://libcxx.llvm.org/Hardening.html).
I've initially enabled the strongest mode (`_LIBCPP_HARDENING_MODE_DEBUG`) but what checks are actually enabled seems to depend on the actual ABI used to compile libc++, so I don't know if all checks are actually enabled.
clang 19 warns about `aligned_storage_t` being deprecated, so this requires #1280.
clang 19 also diagnoses member functions that can't be instantiated, even if they're unused. `deque_anchor` had a few unused functions that could not be instantiated, but according to the standard they're allowed to not be instantiated. clang 19 diagnoses these even when unused leading to compilaton failures. This PR removes the unused member functions. A similar issue is …
> Add clang 19 CI configuration

- libs/pika/execution/tests/regressions/split_continuation_clear.cpp
Disable test for now until https://github.com/NVIDIA/stdexec/issues/1426 is fixed.
Opened #1305 as a reminder to revisit this in the future.
> Disable `split_continuation_clear` test with stdexec enabled

- docs/api.rst
- docs/usage.rst
- Add more links to other implementations
- Mention that sender adaptors are CPOs
- Mention the namespace used by pika and the forwarding of stdexec functionality
- Mention that standardized adaptors are documented elsewhere
> Expand `execution` documentation

- .github/workflows/docs.yml
Currently the doxygen output is put in the same directory as the html files generated by sphinx. Since they don't need to be kept together, and the doxygen output isn't needed for the final artifact, this PR moves the doxygen output to a separate directory that is not uploaded by the documentation workflow.
> Don't include doxygen output in documentation output artifact

- cmake/tests/cxx11_std_atomic.cpp
- cmake/tests/cxx11_std_atomic_128bit.cpp
> Expand `std::atomic` feature tests to include `compare_exchange`, `fetch_add`, etc.

- .gitlab/includes/clang15_pipeline.yml
- .gitlab/includes/clang17_pipeline.yml
- .gitlab/includes/gcc12_pipeline.yml
See #1316 for more details. This PR works around the issue by disabling stacktrace collection on the CI configurations that disable mmap for stacks. I've also disabled mmap for stacks on one GCC CI configuration, to make sure we don't test it only using clang.
A more permanent solution may be to use libunwind for stacktrace collection, as noted in #1316. Considering using mmap for stacks is the default I won't make that change in this PR.
> Work around occasional resource partitioner test segfaults

- libs/pika/async_mpi/src/mpi_polling.cpp
Downgrades the exception to a warning, unless the pool creation mode is `mode_force_create` (in which case it's still an error to not have MPI initialized).
> Don't throw exception when `PIKA_MPI_ENABLE_POOL` is enabled without MPI initialized

- tools/pre-commit
- Simplifies the pre-commit script
- Use pika-ci-base image to have the updated clang-format and cmake-format version
The previous pre-commit script supposed that we had clang-format and cmake-format installed on the system. It also supposed that we update it each time we decide to upgrade the versions.
This PR is using the docker image used in CI, pulls it if it's not available locally. The requirement here is podman, but the user can also remove podman from the pre-commit script if he prefers, the simplified commands run within podman can be run locally
> Update pre-commit to use CI base image

- tools/pre-commit
- tools/pre-commit-podman
Fixes #1327.
Also updates `/bin/bash` to `/usr/bin/env bash` in `pre-commit` hook, as in #1307 (https://github.com/pika-org/pika/pull/1307#discussion_r1825608405).
> Revert #1307 but keep podman-based pre-commit hook in pre-commit-podman

- docs/api.rst
- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
> Use `versionadded` directive in rst to document `require_started` version

- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/tests/unit/algorithm_transform_mpi.cpp
- libs/pika/config/include/pika/config/compiler_specific.hpp
The `transform_mpi` sender adaptor was not ensuring that the references passed to user-provided MPI callables are kept alive until the MPI request completes. This fixes that by adding an explicit `let_value` around the helper adaptors of `transform_mpi`. This PR also adds a number of new tests that trigger the issue if the `let_value` is not in place.
> Test and fix lifetimes of `transform_mpi` values

- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/execution/include/pika/execution/algorithms/bulk.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_operation_state.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
- libs/pika/execution/include/pika/execution/algorithms/start_detached.hpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/include/pika/execution/algorithms/then.hpp
- libs/pika/execution/include/pika/execution/algorithms/unpack.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/include/pika/execution_base/receiver.hpp
- libs/pika/execution_base/tests/include/pika/execution_base/tests/algorithm_test_utils.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
- libs/pika/execution_base/tests/unit/basic_receiver.cpp
- libs/pika/execution_base/tests/unit/basic_sender.cpp
- libs/pika/executors/include/pika/executors/thread_pool_scheduler_bulk.hpp
- libs/pika/executors/tests/unit/std_thread_scheduler.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
Part of #1204. Changes the `set_value` CPO to dispatch to `set_value` member functions instead of using `tag_invoke`. No compatibility is provided for receivers still wishing to use `tag_invoke`.
The `set_value` member is _mandated_ to be noexcept, so we `static_assert` inside the CPO to check that this is the case.
Consistently changes all `set_value` members to move the receiver by value into the `set_value` function scope, to emulate taking the receiver by value. With `tag_invoke` this was easily done by taking the receiver by value as a function parameter, but with a member function this isn't possible (without deducing this https://wg21.link/p0847), so we do the next best thing. I have not changed receivers in tests to consistently move the receiver into the function scope.
The …
> Change `set_value` CPO to use member functions instead of `tag_invoke`

- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/execution/include/pika/execution/algorithms/bulk.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_operation_state.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
- libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/include/pika/execution/algorithms/split.hpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
- libs/pika/execution/include/pika/execution/algorithms/start_detached.hpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/include/pika/execution/algorithms/then.hpp
- libs/pika/execution/include/pika/execution/algorithms/unpack.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/include/pika/execution_base/receiver.hpp
- libs/pika/execution_base/tests/include/pika/execution_base/tests/algorithm_test_utils.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
- libs/pika/execution_base/tests/unit/basic_receiver.cpp
- libs/pika/execution_base/tests/unit/basic_sender.cpp
- libs/pika/executors/include/pika/executors/thread_pool_scheduler_bulk.hpp
- libs/pika/executors/tests/unit/std_thread_scheduler.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
The PR passed pika's tests, but leads to uses of empty `any_sender`s in DLA-Future. It's still unclear if the mistake is in DLA-Future or pika. Reverting the change in `let_value` is enough to make DLA-Future's tests pass again, but reverting the whole PR until I've investigated it further (other algorithms may have issues that we don't trigger in DLA-Future).
> Revert #1295

- .circleci/config.yml
The xsl file previously used for conversion has been removed from the CDash repository. Instead of copying the file over to this repository, we can use ctest's built-in functionality to output a junit file. This functionality exists since 3.21 (see https://cmake.org/cmake/help/latest/manual/ctest.1.html#cmdoption-ctest-output-junit).
> Use ctest's built-in junit support

- libs/pika/runtime/src/runtime.cpp
#1290 set the pthread name for all threads that are used by pika, including the main thread. Since we don't create or "own" the main thread, this PR removes setting the name for the main thread. E.g. in GDB the main thread will simply inherit the name of the binary, which I think is a lot more accurate.
For example, `hello_world` in `pika_main`:
```
(gdb) info threads
Id   Target Id                                        Frame
1    Thread 0x7ffff4efb9c0 (LWP 711869) "hello_world" 0x00007ffff4b1739d in __clone3 () from /nix/store/3bvxjkkmwlymr0fssczhgi39c3aj1l7i-glibc-2.40-36/lib/libc.so.6
2    Thread 0x7ffff14ff6c0 (LWP 711952) "pika/w/d/0"  0x000055555596d8d3 in std::vector<pika::concurrency::detail::cache_aligned_data<pika::threads::detail::thread_queue<std::mutex, …
```
> Don't set thread name on main thread

- examples/documentation/.clang-format
- examples/documentation/drop_operation_state_documentation.cpp
- examples/documentation/drop_value_documentation.cpp
- examples/documentation/hello_world_documentation.cpp
- examples/documentation/init_hpp_documentation.cpp
- examples/documentation/require_started_documentation.cpp
- examples/documentation/split_tuple_documentation.cpp
- examples/documentation/unpack_documentation.cpp
- examples/documentation/when_all_vector_documentation.cpp
The regular limit of 100 is slightly too wide to have the examples fit in the documentation main body text without horizontal scrollbars. This overrides the value to 80 only for the documentation examples.
> Format examples shown in documentation to 80 columns to fit better in text

- CITATION.cff
- docs/developer.rst
- tools/roll_release.sh
Pulls in many of the release script improvements that were made in DLA-Future.
- Adds checks for `CITATION.cff`
- Uses regexes instead of just the version number to check that the version is set correctly.
- Check for today's date in the changelog and `CITATION.cff`.
Also adds a note in the release procedure to update the `CITATION.cff` file.
I also did not update the `CITATION.cff` file for 0.30.0 and 0.30.1. I've updated the entries manually on zenodo.org, and updated the file here for 0.30.1.
I obviously haven't tested the updated release script on a full release, but testing until the tagging phase seems work to catch errors e.g. in the `CITATION.cff` file.
> Update release procedure and script

- libs/pika/async_cuda/include/pika/async_cuda/cuda_pool.hpp
- libs/pika/async_cuda/src/cuda_pool.cpp
The idea is that the thread-local streams (three by default) may limit concurrency of kernels within a worker thread. Using a single but larger shared pool of streams should lead to more possible concurrency, especially if many independent kernels are submitted quickly after each other from the same worker thread. At the same time, having e.g. three thread-local streams per thread on a Grace CPU is fake concurrency: CUDA will not actually allow allow a concurrency of 3×72=216. Using a shared pool limits the number of created streams to something a bit more manageable, and does not scale unnecessarily with the number of worker threads. Finally, using the same streams concurrently from different threads should not create thread-safety issues.
This change does not noticeably change the …
> Use shared pool of CUDA streams instead of thread-local pools

- .gitlab/includes/gcc10_apex_pipeline.yml
I believe https://github.com/UO-OACISS/apex/issues/182 is what has been causing occasional test failures on the APEX CI configuration. In the hope that the issue is resolved quite quickly upstream, I'm going to use the very large hammer of allowing anything in the test stage to fail at the moment, for simplicity.
https://github.com/pika-org/pika/issues/1353 tracks disallowing failures again.
> Allow failure on test stage of APEX CI configuration

- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/transform_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
This PR is a proposal for some small refactorings of how the `transform_mpi` adaptor is composed of `dispatch_mpi` and `trigger_mpi`.
There are two goals with the changes:
- handle the "early polling" in one place and one place only: the `trigger_mpi` receiver
- remove nesting of `let_value` and extra type-erasure with `unique_any_sender`
The early check for `MPI_REQUEST_NULL` was done in at least two places, and the early polling was done in `dispatch_mpi`. I've moved the early poll to `trigger_mpi` where I think it fits semantically.
> Minor `transform_mpi` refactoring

- .gitlab/includes/common_pipeline.yml
Adds a timestamp to every line of log output. The raw log has the full timestamp. See https://docs.gitlab.com/runner/configuration/feature-flags.html for details. This feature is only available for gitlab runners 16.11 and newer, which at the time of the PR is not all CSCS CI runners, but I'm enabling the flag globally anyway, so that when they're updated, we'll have the timestamps there.
> Enable timestamps in CSCS CI output

- .circleci/config.yml
- .gitlab/scripts/collect_file_sizes.sh
- .gitlab/scripts/run_performance_benchmarks.sh
- .gitlab/scripts/utilities.sh
- .jenkins/cscs-perftests/batch.sh
- .jenkins/cscs-perftests/comment_github.sh
See commit description for more details. I'm leaving the other formatting checks as before.
> Check that all shell scripts are formatted with `shfmt`

- .gitlab/docker/Dockerfile.spack_base
Since one can't install new packages when running in a container (since it runs as user, not root), e.g. on Alps, add `gdb` to the list of packages available in the image by default.
> Install GDB in base image for CSCS CI for easier debugging

- .gitlab/scripts/collect_ctest_metrics.sh
- .gitlab/scripts/collect_file_sizes.sh
- .gitlab/scripts/run_performance_benchmarks.sh
- .gitlab/scripts/utilities.sh
Some uploads can take up to 15 minutes, because we upload each entry separately. This PR batches the uploads in the hope that it will be significantly faster.
Batching is done by combining a file of multiple json documents into a file of an array of the same json documents. This is equivalent to uploading each document separately. The logstash documentation for the `json` codec says (https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json.html):
> If the data being sent is a JSON array at its root multiple events will be created (one per element).
> Batch logstash uploads to speed up CI jobs

- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/src/any_sender.cpp
Complement to #1281. Fixes #845.
Adds more indirection so that the concrete receiver type doesn't have to be type-erased. It can instead be stored directly in the operation state type, and then a reference/pointer to a base class is passed to connect instead. This does not avoid the indirection/virtual function dispatch, but only requires passing a pointer-sized receiver to connect.
> Store receiver in `any_operation_state` to avoid dynamic allocation for receiver

- docs/Doxyfile
- docs/api.rst
- examples/documentation/CMakeLists.txt
- examples/documentation/async_rw_mutex_documentation.cpp
- libs/pika/synchronization/include/pika/synchronization/async_rw_mutex.hpp
> Add documentation for `async_rw_mutex`

- libs/pika/execution_base/include/pika/execution_base/receiver.hpp
The documentation is outdated after `set_value` was changed to use member functions. Remove the whole documentation until we can document it properly.
> Fix the documentation for `set_value`

- .gitlab/docker/Dockerfile.spack_build
- .gitlab/includes/clang14_cuda11_pipeline.yml
- .gitlab/includes/clang19_pipeline.yml
- libs/pika/async_cuda/include/pika/async_cuda/cuda_scheduler_bulk.hpp
- libs/pika/async_cuda/tests/unit/cublas_matmul.cpp
- libs/pika/async_cuda_base/include/pika/async_cuda_base/cuda_stream.hpp
Enabling on the clang/CUDA pipeline and the latest clang (19 at the time of the PR) pipeline.
> Enable clang-tidy checks on CSCS CI clang pipelines

- .gitlab/docker/Dockerfile.spack_build
Since the environment is already concretized, calling it without an explicit spec simply prints the spec of anything that is in the environment. Calling it with an explicit spec will reconcretize. It will concretize to the right thing, unless something very strange happens, since all the dependencies are installed, but it takes significantly longer to print the spec with an explicit spec.
> Call `spack spec` without an explicit spec in CI

- libs/pika/synchronization/include/pika/synchronization/async_rw_mutex.hpp
- libs/pika/synchronization/tests/unit/CMakeLists.txt
- libs/pika/synchronization/tests/unit/async_rw_mutex_yielding.cpp
See test for a description of what exactly is being tested.
Just for reference, the debugging was done with this branch: https://github.com/pika-org/pika/compare/main...msimberg:pika:debugging-async-rw-mutex-yield. It adds logging, extra sleeps to trigger the issue reliably. It modifies `hello_world` as the test case.
> Add test case and fix to trigger yielding when accessing `async_rw_mutex` senders in particular ways

- .gitlab/scripts/run_performance_benchmarks.sh
- libs/pika/synchronization/tests/performance/CMakeLists.txt
- libs/pika/synchronization/tests/performance/async_rw_mutex_scheduling.cpp
Adds a simple benchmark which repeats read-write and read-only accesses (in new tasks) a configurable number of times. Also adds the benchmark to CI.
> Add `async_rw_mutex` benchmark

- .gitlab/includes/gcc10_apex_pipeline.yml
2.7.1 includes which https://github.com/UO-OACISS/apex/commit/cde877d0b01ded4c4c328c026454bfff6fe1714d should fix https://github.com/UO-OACISS/apex/issues/182.
Fixes #1353.
> Use apex 2.7.1 in CI which fixes shutdown use-after-free

- libs/pika/async_cuda/include/pika/async_cuda/cuda_scheduler.hpp
- libs/pika/async_cuda/include/pika/async_cuda/then_with_stream.hpp
- libs/pika/async_cuda/tests/unit/then_with_stream.cu
- libs/pika/async_mpi/include/pika/async_mpi/dispatch_mpi.hpp
- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/execution/include/pika/execution/algorithms/bulk.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_operation_state.hpp
- libs/pika/execution/include/pika/execution/algorithms/drop_value.hpp
- libs/pika/execution/include/pika/execution/algorithms/require_started.hpp
- libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
- libs/pika/execution/include/pika/execution/algorithms/split_tuple.hpp
- libs/pika/execution/include/pika/execution/algorithms/sync_wait.hpp
- libs/pika/execution/include/pika/execution/algorithms/then.hpp
- libs/pika/execution/include/pika/execution/algorithms/unpack.hpp
- libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
- libs/pika/execution/tests/unit/algorithm_execute.cpp
- libs/pika/execution/tests/unit/algorithm_transfer.cpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
- libs/pika/execution_base/include/pika/execution_base/sender.hpp
- libs/pika/execution_base/tests/include/pika/execution_base/tests/algorithm_test_utils.hpp
- libs/pika/execution_base/tests/unit/any_sender.cpp
- libs/pika/execution_base/tests/unit/basic_receiver.cpp
- libs/pika/execution_base/tests/unit/basic_schedule.cpp
- libs/pika/execution_base/tests/unit/basic_sender.cpp
- libs/pika/executors/include/pika/executors/std_thread_scheduler.hpp
- libs/pika/executors/include/pika/executors/thread_pool_scheduler.hpp
- libs/pika/executors/include/pika/executors/thread_pool_scheduler_bulk.hpp
- libs/pika/executors/tests/unit/std_thread_scheduler.cpp
- libs/pika/executors/tests/unit/thread_pool_scheduler.cpp
Part of #1204. Also a step towards reducing debug bloat.
> Change `get_env` CPO to use member functions

- docs/usage.rst
#1397 bumped the official minimum requirements to GCC 11 and CUDA 12. Older versions may still work, but will not be actively tested, so let's mention what we do test in the documentation.
> Update documentation to mention GCC 11 and CUDA 12 as minimum requirements

- .gitlab/scripts/run_performance_benchmarks.sh
- tests/performance/local/resume_suspend.cpp
- tests/performance/local/start_stop.cpp
This adds support to the two tests for printing the json used in elastic. This also removes the scheduling of tasks from the two tests, as that's somewhat orthogonal to starting/stopping/resuming/suspending. We have other tests for benchmarking the time to schedule a task.
> Add start-stop and resume-suspend performance benchmarks to performance CI runs

- tests/performance/local/start_stop.cpp
I wrongly updated the test to use the header from resume-suspend in #1399.
> Fix csv header in start-stop

- .gitlab/includes/common_spack_pipeline.yml
Using https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html for more test statistics on GitLab.
> Store ctest JUnit XML files as artifacts in GitLab CI pipelines

- docs/requirements.txt
sphinx 8.2.0 is currently incompatible with breathe: https://github.com/breathe-doc/breathe/pull/1010. breathe main branch already has a fix, but a new version is required: https://github.com/breathe-doc/breathe/issues/1022.
> Pin sphinx version for documentation

- libs/pika/coroutines/include/pika/coroutines/detail/context_linux_x86.hpp
- libs/pika/coroutines/include/pika/coroutines/detail/context_posix.hpp
Minor cleanup. There's no need for the value to be a preprocessor definition, so make it a function local constexpr variable instead. Also makes it a round 2^10 bytes instead of 1000 bytes.
> Make stackoverflow epsilon value function-local constexpr instead of macro define

- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
- libs/pika/async_mpi/src/mpi_polling.cpp
- libs/pika/async_mpi/tests/unit/mpi_ring_async_sender_receiver.cpp
- libs/pika/resource_partitioner/tests/unit/cross_pool_injection.cpp
- libs/pika/synchronization/include/pika/synchronization/async_rw_mutex.hpp
- libs/pika/thread_manager/src/thread_manager.cpp
- libs/pika/thread_pools/include/pika/thread_pools/scheduled_thread_pool_impl.hpp
- libs/pika/threading/tests/unit/jthread1.cpp
- libs/pika/threading_base/src/scheduler_base.cpp
- tests/performance/local/task_size.cpp
- tests/regressions/threads/thread_rescheduling.cpp
This makes the spinlock deadlock detection much more useful when it reports a failure, since the label will be printed on failure.
> Add non-nullptr labels to all `yield_while` calls

- libs/pika/coroutines/include/pika/coroutines/detail/context_linux_x86.hpp
- libs/pika/coroutines/include/pika/coroutines/detail/posix_utility.hpp
- libs/pika/runtime_configuration/src/runtime_configuration.cpp
- tests/regressions/stack_size_config_4543.cpp
- Removes unnecessarily strict stack size restrictions (e.g. small stack size has to be smaller than `PIKA_SMALL_STACK_SIZE`)
- Adjusts the assertion when watermarking stacks to allow stack size == page size
- Refactor "stack-size-is-multiple-of-page-size` checks to be used for both the x86 and posix context implementations
> Refactor stack size checks

- cmake/pika_add_config_test.cmake
Fixes a bad check for MPIX continuations when using openmpi without compiler wrappers
> Add MPI include dir before performing mpix continuations test

- .github/workflows/linux_asan_ubsan_lsan.yml
- .github/workflows/linux_tsan.yml
> Add workaround for broken MPICH in ubuntu 24.04 to sanitizer CI configurations

- libs/pika/async_mpi/include/pika/async_mpi/trigger_mpi.hpp
This overload is currently unused, so this would not so far have caused any known bugs, but the flags should still be propagated.
> Add missing `completion_mode_flags` in l-value reference connect overload of `trigger_mpi`

- .gitlab/includes/gcc12_hip6_pipeline.yml
- .gitlab/includes/gcc13_pipeline.yml
- cmake/pika_add_config_test.cmake
- cmake/pika_perform_cxx_feature_tests.cmake
- cmake/tests/stdexec_env.cpp
- libs/pika/execution/tests/unit/CMakeLists.txt
- libs/pika/execution/tests/unit/algorithm_continues_on.cpp
- libs/pika/execution_base/include/pika/execution_base/stdexec_forward.hpp
Updates one CI configuration to use latest stdexec main, another to use the `nvhpc-25.03.rc1` tag, and leaves the rest on 24.09 (available in spack).
> Use newer stdexec commit in CI

- .github/workflows/linux_valgrind.yml
- libs/pika/command_line_handling/src/command_line_handling.cpp
Prefer environment variables over command line options.
> Refer to environment variables in warning about starting runtime with only one worker thread

- .circleci/config.yml
- .github/workflows/linux_debug.yml
- .github/workflows/linux_hip.yml
- .github/workflows/linux_release_fetchcontent.yml
- .github/workflows/linux_tracy.yml
- .github/workflows/linux_valgrind.yml
- .gitlab/includes/common_pipeline.yml
- CMakeLists.txt
Don't set it always when available, and especially not for consumers of pika.
> Only set `-Wl,-z,defs` in CI for testing

- libs/pika/execution/include/pika/execution/async_rw_mutex.hpp
- libs/pika/execution_base/include/pika/execution_base/any_sender.hpp
This fixes warnings such as 
```
pika/libs/pika/execution/include/pika/execution/async_rw_mutex.hpp:144:16: warning: 'struct pika::execution::experimental::detail::async_rw_mutex_operation_state_base' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
144 |         struct async_rw_mutex_operation_state_base
|                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
and
```
pika/libs/pika/execution_base/include/pika/execution_base/any_sender.hpp:394:12: warning: 'struct pika::execution::experimental::detail::any_receiver_ref_base<>' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
394 |     struct any_receiver_ref_base
|            ^~~~~~~~~~~~~~~~~~~~~
```
> Fix warnings about non virtual destructors

- libs/pika/coroutines/include/pika/coroutines/detail/coroutine_self.hpp
Removes 40 bytes of storage for the unique_function.
> Remove unused `yield_decorator` functionality from `coroutine_self`
